### ISSUE TITLE
지원 화면에 대한 개발 이슈를 정리한다. - 9월 3일(목)

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#10]

**Comment by LTTTTTE** [comment]
### 공고 목록 페이지 (메인) 만들기

- 전체 공고를 띄우는 기능을 구현한다.
    - 전체 공고 get api 요청
    - 공고 이름 표시
    - 공고 기간 표시
- 전체 공고에 필터 기능을 구현한다.
    - (필터) 모집 중인 공고만 띄운다.
        - 기간 + 활성화 여부
    - (필터) 모집 종료된 공고만 띄운다.
- 공고 기간별로 지원버튼이 변경되도록 구현한다.
    - 기간 내의 공고는 지원하기 버튼으로 전환
    - 기간 외의 공고는 모집 종료 버튼으로 전환
- 지원하기 버튼을 클릭하면 공고 id를 params로 하여 지원자 등록 페이지로 이동한다.

### 지원자 확인 페이지 만들기

- 입력 폼을 작성한다.
    - 이메일 입력 필드
    - 패스워드 입력 필드
    - 확인 버튼
        - 지원자 token get요청
        - 내 지원서 목록 페이지로 redirect

### 내 지원서 목록 페이지 만들기

- 내가 지원한 공고만 띄워주는 기능을 구현한다.
    - 내가 지원한 공고 get api 요청 with token ( 없거나 만료 시 지원자 확인 페이지로 리다이렉트
    - 공고 이름
    - 공고 기간
- 공고 제출 여부, 기간 별로 지원 버튼 변경되도록 한다.
    - 기간 내의 공고는 '지원서 수정'
    - 기간이 끝난 공고는 '기간만료'
    - 기간과 상관없이 제출이 완료된 공고는 '제출함'

### 지원자 등록 페이지 만들기

- 입력 필드 띄운다.
    - 이름
    - 전화번호
    - 이메일
    - 생년월일
    - 성별
    - 비밀번호
    - 비밀번호 확인
    - 개인정보 수집 및 이용 동의란 띄워 주기
- 다음을 누를 시 지원자 정보를 지원서 제출 전까지 홀딩 한다.

### 지원서 작성 페이지 만들기

**공통**

- 지원자 이름을 readonly 입력 필드로 추가한다.
- 지원 문항을 서버로부터 받아 입력 필드로 추가한다.
    - 최대 문자 수를 제한할 수 있다.
- 파일 첨부 기능을 추가한다.
    - 첨부 가능한 포맷: pdf, doc, docx, txt, hwp
    - 첨부 가능한 최대 파일 사이즈: 10MB
- URL을 입력하는 필드를 추가한다.
    - 개인 블로그나 github 링크 등을 자유롭게 입력할 수 있다.
- 취소 버튼을 누르면 입력한 폼 데이터를 초기화 한다.
- 임시 저장 버튼을 누르면 서버에 지원서를 저장한다.
- 제출 버튼을 누르면 Confirm 모달 창을 띄운다.
- Confirm 모달 창에서 확인을 누르면 서버로 지원서를 제출 한다.
    - 지원서 제출 post api 요청
    - 필수 입력 필드를 모두 입력해야 한다.
    - 제출 이후 수정할 수 없다.

**수정**

- 임시 저장한 데이터를 불러와 입력 필드에 값을 넣는다.

**Comment by toneyparky** [comment]
지원시 사실여부 체크박스를 프론트에서만 관리하는 방향으로 처리하셨군요~ 좋습니다!

입력 required, optional로 표시되었던 부분도 명확하게 수정된 점이 이해하기 좋네요!

또한 vuex와 같은 프레임워크 종속적인 언어가 아니라 전역 상태라는 보편적인 언어를 사용하였기에 프레임워크를 모르더라도 이해하기 쉬울 것 같습니다. (물론 이번 지원 화면은 뷰로 개발되지만요..!)

마지막으로 이슈 나눠주신 항목들을 바로 이슈 제목과 내용으로 사용되어도 좋을 만큼 잘 정리하셨네요! 😬👍

방학인데도 수고많았어요 다들..!

이만 이슈 닫아도 될 것 같네요.
남은 방학을 즐겨보자구요!
