### ISSUE TITLE
ApplicationForm의 이름에 대해 논의한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#101]
- Curriculum Vitae(이력서)
- Resume(이력서)
- Cover Letter(커버 레터)
- Application(지원서)
- Apply Paper

**Comment by ddaaac** [comment]
일전에 토니가 제안한 `ApplyPaper`도 괜찮은 것 같아요. 
`Applicant`랑 앞글자가 같아서 연관성을 보여주기에 괜찮다고 생각합니다

**Comment by dks301** [comment]
개인적으로 Application이 이미 익숙해서 그런지 Application을 그대로 사용해도 좋을 것 같습니다 :)
개발하면서도 제이슨이 말씀하신 것처럼 `Recruitment -> RecruitmentForm`과 같이 `ApplicationForm`도 `Application`이 아닌 것 같은 느낌을 받았어요

**Comment by toneyparky** [comment]
ApplyPaper로 바꾼다면 Dto가 ApplyPaperForm이 되겠군요. 
이 부분에 대해 거부감이 없으시다면 이대로 진행해도 괜찮을 거 같아요.

**Comment by woowahan-pjs** [comment]
Cover letter 혹은 Application letter 중 하나를 선택하면 어떨까요?

- [부담스러운 커버레터(Cover letter), 알고 보면 별거 아니야!](http://newsletter.toeic.co.kr/webzine/pdf/20170506/16.pdf)
- [신입 소프트웨어 엔지니어의 커버 레터 작성하기 - Sujin Lee](https://sujinlee.me/cover-letter)
- [Cover letter](https://en.wikipedia.org/wiki/Cover_letter)

**Comment by toneyparky** [comment]
둘중 하나라면 Cover Letter는 의미 자체가 다르다 생각하기에 후자에 한표를 던지겠습니다.

**Comment by woowahan-pjs** [comment]
`ApplicationLetter`로 결정하겠습니다.

**Comment by woowahan-pjs** [comment]
> 영미권에서 자기소개서와 가장 의미가 비슷한 말을 뽑으라면 Personal statement라는 표현이 가장 적절하다. 의미상으로 자기 자신과 자기 자신의 경험에 대해 소개하는 내용으로 같은 의미가 되는 글을 이름 붙이자면 personal statement가 맞다. 다만 정작 영미권에서 생활할때는 Personal statement라는 표현은 대학이나 기업에 들어갈때 요구되는 경우는 적을 것이다. 예를 들어, 미국 대학 입학등에 요구하는 자소서는 Essay라고 부른다. 반대로 취업할때 기업에게 보내는 자소서는 Cover letter라고 부른다.

- https://namu.wiki/w/%EC%9E%90%EA%B8%B0%EC%86%8C%EA%B0%9C%EC%84%9C
- https://ko.dict.naver.com/#/entry/koko/d1ae526071c5475d910599a6351cdde3
- https://www.jobkorea.co.kr/company/1882711/keyword

**Comment by dks301** [comment]
저도 ApplicationLetter에 한 표하겠습니다 :)
