### ISSUE TITLE
관리자 페이지에서 평가하기 모달의 파일명에 대해 논의한다.

### ISSUE THREAD

**Issue by ddaaac** [woowacourse/service-apply#103]
요구 사항 명세서를 보면 평가의 정의는 아래와 같습니다.
> 평가(evaluation): 모집에 대한 전체 지원자 중 최종 합격자를 선정하기 위한 여러 과정

이번에 구현한 평가하기는 이의 동사형에 가까운데 이와 관련된 dto 및 파일 이름을 어떻게 해야할지 의견 주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/43440195/94431663-8b7d4480-01d0-11eb-8957-5dcd47b80403.png)
동사형이라서 `EvaluateRequest` 이렇게 지어봤었는데 기존의 `EvaluationRequest`랑 좀 헷갈리는 거 같더라고요.

후보
1. `EvaluateRequest`, `EvaluateForm`
1. `DoEvaluationRequest`, `DoEvaluationForm`

**Comment by woowahan-pjs** [comment]
DTO의 이름에 대해서는 아래 코멘트를 참고하세요.
https://github.com/woowacourse/service-apply/pull/92#discussion_r496462472

**Comment by ddaaac** [comment]
그럼 평가 + 하기로 `DoEvaluationRequest` 괜찮을까요?
아니면 채점이라는 의미로 `ScoreEvaluation`이나 `GradeEvaluation`은 어떨까요?

**Comment by toneyparky** [comment]
judgeEvaluation은 어떤가요?
판단하다라는 의미라 100% 맞진 않지만 제안해봅니다.
