### ISSUE TITLE
지원하기 흐름을 검토하여 수정한다.

### ISSUE THREAD

**Issue by lalize** [woowacourse/service-apply#118]
- [x] 푸터의 Github 아이콘에 걸린 링크를 `3기 모집 안내문` 링크로 수정한다.
- [x] 지원자 등록 페이지에서 `개인정보 수집 및 이용 약관`을 수정한다. [참조](https://github.com/woowacourse/service-apply/issues/118#issuecomment-703423536)
- [x] 지원서 작성 페이지에서 `지원서 작성 내용 사실 확인 설명`을 추가한다.
  `기재한 사실 중 허위사실이 발견되는 즉시, 교육 대상자에서 제외되며 향후 지원도 불가능합니다.`
- [x] #143 이슈를 해결한다.
- [x] 존재하지 않는 모집에 대해 지원할 수 없도록 수정한다.
  - 방어 로직이 누락되어 있어 추가하였다.
- [x] 모집중이 아닌 지원에 대해 저장, 제출하지 못하도록 수정한다.
  - 방어 로직이 누락되어 있어 추가하였다.
- [x] 이미 작성중인 지원서가 존재하는 경우 지원하기를 통해 접근하면 메인 페이지로 이동한다.
  - 기존에는 임시 저장 / 제출을 해야 지원서 존재 여부를 검사했다. 지원서가 있는 경우 메인 페이지로 이동하기 때문에 작성한 내용을 저장하지 못했다.
  - 지원하기로 접근하면 빈 지원서 작성 요청을 하여 문제를 해결했다.
- [x] `/index.html` 요청시 `/`로 리다이렉션하도록 수정한다.
- [x] RecruitmentResponse 모집 시작 날짜와 모집 종료 날짜 순서가 잘못된 부분을 수정한다.
- [x] 우아한테크코스 favicon으로 수정한다.
- [x] 사이트 제목을 `우아한테크코스 지원하기`로 수정한다.
- [x] production/development에 따라 API 주소를 설정한다.
  - `VUE_APP_BACKEND_URL=주소 npm run build`를 통해 인라인으로 설정할 수도 있다.
- [x] 프런트쪽 더미 데이터가 API 요청에 실패했을 때 사용하게 되어있어 예외 상황을 파악하기 어렵게 한다. 따라서 프런트쪽 더미 데이터를 제거한다. 
- [x] 지원자 등록 페이지에서 선택한 모집을 보여준다.
- [x] 항목에 대한 답변이 존재하지 않는 경우 콘솔 에러를 수정한다.
- [x] 모집을 불러온 후 view를 렌더링 하도록 수정
  - 비동기 요청이기 때문에 완료되지 않은 상태에서 view가 그려지는 경우 콘솔 에러가 발생한다.
- 발견한 버그를 수정하고 전체적으로 코드를 리팩토링한다.
  - 변경사항은 해당 이슈에 기록한다.

**Comment by woowahan-pjs** [comment]
```
우아한형제들은 개인정보보호법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 등 관련 법령 상의 개인정보보호 규정을 준수하며, 개인정보의 보호에 최선을 다하고 있습니다.

1. 개인정보의 수집·이용 목적
- 우아한테크코스 지원자 모집 및 대상자 선정

2. 개인정보 수집 항목
- [필수] 이름, 이메일, 연락처, 성별, 생년월일

3. 개인정보 보유 및 이용기간
- 우아한테크코스 2기 교육 대상자 선정 이후 파기


위 개인정보 수집·이용에 동의하지 않으실 수 있으며, 동의하지 않으실 경우 우아한테크코스 지원이 제한됩니다.
```
