### ISSUE TITLE
엑셀 다운로드 뒤, 화면이 멈추는 버그를 해결한다.

### ISSUE THREAD

**Issue by ddaaac** [woowacourse/service-apply#131]
엑셀 파일 다운로드는 아래 코드를 통해 실행됩니다. 엑셀 파일을 저장하는 임시 주소를 `resourceUri`에 저장해두고 해당 페이지를 방문하면 다운로드 되는 방식이죠.
`UI.getCurrent().page.setLocation(registration.resourceUri)`

문제는 `setLocaiton` 메서드가 **현재 페이지**의 주소를 바꾸는데 있습니다. 그래서 엑셀 파일을 다운로드 받으면 페이지가 멈추게 됩니다,
따라서 새 탭에서 페이지를 열면 해결 됩니다.

`UI.getCurrent().page.open(registration.resourceUri.toString())`
![image](https://user-images.githubusercontent.com/43440195/95329798-814efa80-08e2-11eb-8ac5-81cfafca7bca.png)

**Comment by toneyparky** [comment]
오 깔끔하게 동작하네요...!

빠른 해결책까지!

이 부분은 엑셀 관련 pr 때에 반영하시도록 놔두겠습니다👍
