### ISSUE TITLE
원격 빌드 중에 발생하는 테스트 실패의 원인을 찾아 제거한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#144]
> EvaluationTargetServiceTest > 평가 대상을 평가(채점)한 적이 없을 때, 채점 정보를 불러온다() FAILED
    java.lang.NoClassDefFoundError at EvaluationTargetServiceTest.kt:285

`every { evaluationRepository.findByIdOrNull(EVALUATION_ID) } returns evaluation`

> EvaluationTargetServiceTest > 이전 평가가 없고 저장 된 평가 대상자가 없을 경우 저장하고 불러온다() FAILED
    java.lang.NoClassDefFoundError at EvaluationTargetServiceTest.kt:99

`every { evaluationRepository.findByIdOrNull(any()) } returns firstEvaluation`

**Comment by toneyparky** [comment]
무슨일이지요. 제가 작성하면서 연관되게 짜놓은 부분이 있으려나요. 로컬상에서는 괜찮은데말이죠. 

검색해보니 [라이브러리 문제](https://nhj12311.tistory.com/84)일 수 있다고 하는 부분이 있구요. 서버 환경에 mockK가 적용 안되는 걸까요? 그렇다기에는 다른 친구들은 돌아가고 말이죠. 

`createEvaluation` 메서드에서 생성해주는 데에서 연관이 생겼으려나요. 

[이 친구](https://donghyeon.dev/articles/2019-04/java.lang.NoClassDefFoundError-%EC%98%A4%EB%A5%98%ED%95%B4%EA%B2%B0)와 [이 친구](https://www.jetbrains.com/help/idea/configure-web-app-deployment.html)를 참고해봐도 좋을 것 같아요!

**Comment by woowahan-pjs** [comment]
빌드 환경에서 UTF-8을 사용하도록 로케일을 설정해서 문제가 해결되었습니다.
