### ISSUE TITLE
평가 대상자를 다운로드하였을 때 0점이 누락된다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#159]
현상: 화면에 0이 표시 되더라도 엑셀을 다운로드 할 때 비어 있거나 잘못된 값이 포함되어 있다.
재현 스텝: 선발 과정 > 모집 > 평가 > 다운로드
예상되는 원인: 점수가 등록되어 있지 않기 때문에 한 컬럼씩 당겨지는 것으로 예상된다.
스크린샷:
[프리코스 대상자 선발.xlsx](https://github.com/woowacourse/service-apply/files/5368317/default.xlsx)
![bug](https://user-images.githubusercontent.com/48229284/95803618-888b6380-0d3b-11eb-8e21-adabfec6ea17.png)

**Comment by ddaaac** [comment]
더미 데이터에서 각각 2,0,1점을 갖는 평가 점수를 생성해야하는데 2,1점 만 생성해서 나타나는 일입니다.

![image](https://user-images.githubusercontent.com/43440195/95804626-3992fd80-0d3e-11eb-9c2d-abdf1506449c.png)
위와 같이 0점을 나타내는 평가 점수를 추가하면 정상적으로 작동합니다.
[프리코스 대상자 선발.xlsx](https://github.com/woowacourse/service-apply/files/5368390/3.xlsx)

실제로 채점을 할 때는 0점인 평가점수 객체도 모두 생성돼서 문제 없이 작동합니다.

-------------------------------

별도로, 평가항목의 순서가 변경되고 -> 채점을 하지 않은 평가대상자가 있으면 -> 엑셀 다운로드 받을 때 그 평가대상자들의 점수 순서가 올바르지 않게 엑셀에 기록되는 문제가 생깁니다.

평가 점수(`EvaluationAnswer`)에는 순서가 따로 없어서 생기는 문제인데, 어떻게 해결하면 좋을지 얘기를 나눠보면 좋을 것 같아요.

제 생각에는 평가 항목을 불러오는 로직을 수정해서 모든 평가 대상을 지우고 새로 저장하는 방식을 사용하고(현재는 수정이 필요한 평가 대상만 업데이트하죠)

평가항목 순서를 변경했으면 다시 불러오기를 누르라고 notice를 주는 방식이 좋을 것 같은데, 다들 어떻게 생각하시나요?

**Comment by woowahan-pjs** [comment]
평가 항목의 경우 평가 대상자를 이미 불러왔다면 제목과 설명만 수정할 수 있고, 모든 평가 대상자를 삭제하는 기능이 있으면 좋겠네요.
