### ISSUE TITLE
모집 일시가 지나도 수정할 수 있어야 하지 않을까?

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/service-apply#160]
모집 일시가 지나는 경우 자동 종료는 좋은데, 관리툴에서 수정 가능해야 하지 않을까?

**Comment by woowahan-pjs** [comment]
@pobiconan 
어떤 경우에 수정이 필요할까요?

**Comment by pobiconan** [comment]
@woowahan-pjs 
운영할 때 수정이 필요한 경우가 있을지 모르겠지만 테스트 상황에서는 너무 불편한데..
혹시라도 종료일이 끝난 후에 다시 연장하고 싶은 경우가 생긴다면 수정이 힘들기는 할 것 같은데...
지금 관리툴이 누구에게나 오픈되어 있듯이 수정 기능을 오픈해 놓는 것이 편의상 좋지 않을까?
