### ISSUE TITLE
내 지원서를 보기 위한 로그인 정보

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/service-apply#161]
내 지원서를 보기 위해 로그인해야하는 정보가 너무 많은 것 아닐까?
굳이 생년월일이 필요할까?
더 제외한다면 이름도 필요없지 않을까?

**Comment by woowahan-pjs** [comment]
우아한형제들 인재채용을 참고하였습니다. 이메일과 비밀번호로 충분하다는 말씀이시죠?
https://www.woowahan.com/#/recruit/result

**Comment by pobiconan** [comment]
@woowahan-pjs 
그 정도면 충분하지 않을까?
