### ISSUE TITLE
내 지원서 보기시 이름이 보이지 않는다

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/service-apply#162]
내 지원서 보기에서 로그인 성공하는 경우 첨부한 이미지와 같이 이름이 보이지 않는다.
로그인에 성공 했는데 비밀번호를 입력하는 창이 다시 뜨고 있다.

![스크린샷 2020-10-13 오후 3 03 25](https://user-images.githubusercontent.com/45650838/95821705-5d1d6e80-0d65-11eb-851d-22c12899b172.png)

**Comment by woowahan-pjs** [comment]
@pobiconan 
제출을 위해 비밀번호를 다시 입력하는 건데 흐름이 이상하게 느껴질 수 있겠네요. 이름이 보이지 않는 문제는 수정하겠습니다.

**Comment by woowahan-pjs** [comment]
임시 비밀번호가 발급된 후 비밀번호를 다시 입력하여 수정할 수 있도록 다시 비밀번호를 입력 받았다. 임시 비밀번호를 발급하지 않은 사용자는 혼란스러울 수 있다.

- 이름과 비밀번호, 비밀번호 확인란을 지운다.
- 비밀번호를 수정할 수 있는 페이지를 따로 만든다.
