### ISSUE TITLE
내 지원서 탭에서도 상위 탭이 보여야 하지 않을까?

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/service-apply#163]
내 지원서 탭과 다른 탭의 상위 탭이 달라 페이지 간의 이동을 하는데 불편함이 있다.
내 지원서 탭과 다른 탭의 상위 탭을 같은 방식으로 이동할 수 있도록 개선하는 것이 좋지 않을까?

## 내 지원서 페이지
![스크린샷 2020-10-13 오후 3 10 45](https://user-images.githubusercontent.com/45650838/95822200-66f3a180-0d66-11eb-9845-03b5a36a3565.png)

## 내 지원서 페이지 외 탭 메뉴
![스크린샷 2020-10-13 오후 3 10 59](https://user-images.githubusercontent.com/45650838/95822222-71ae3680-0d66-11eb-9cfe-e8fc811ec078.png)

**Comment by woowahan-pjs** [comment]
지원서 페이지의 탭 메뉴를 내 지원서 페이지에도 적용한다.
