### ISSUE TITLE
비밀번호 찾기를 했는데, 이메일로 임시 비밀번호가 오지 않는다.

### ISSUE THREAD

**Issue by eastjun** [woowacourse/service-apply#164]

**Comment by LTTTTTE** [comment]
이메일 보낼때 사용되는 계정에 대해
[구글2단계인증]( https://accounts.google.com/b/0/SmsAuthConfig?hl=ko ) 이후 앱별 비밀번호 설정을 새로 해줘야 합니다.

[앱별 비밀번호 설정](https://security.google.com/settings/security/apppasswords?pli=1)
![image](https://user-images.githubusercontent.com/7259103/95832696-9eb61580-0d75-11eb-975a-f0d666d87e6b.png)

---

앱은 `메일`
기기는 `기타`
![image](https://user-images.githubusercontent.com/7259103/95832791-c1e0c500-0d75-11eb-9116-5168925907be.png)

`비밀번호가 생성됩니다.`

기존 이메일사용하되
비밀번호는 생성된 비밀번호를 사용하면됩니다.
