### ISSUE TITLE
최종 제출 후 내 지원서 보기 기능이 없다.

### ISSUE THREAD

**Issue by eastjun** [woowacourse/service-apply#165]
최종 제출 후 자신의 지원서 내용을 확인할 수 없어, 지원자 입장에서 제출 후 불안감이 드는것 같아요. 자신이 제출한 내용을 볼 수 있으면 좋을 것 같아요!

**Comment by woowahan-pjs** [comment]
제출된 신청서를 얼마나 오래 볼 수 있게 할지 고민이네요. 종료 일시 이후에 볼 수 없거나, 최종 제출할 때 볼 수 없다고 문구를 추가해 볼 수 있겠어요.

> 이메일, 홈페이지를 통해 제출된 서류 및 지원자가 자발적으로 제출한 서류는 채용절차공정화에 관한 법률 제 11조에 의거 반환의무가 없음을 안내드립니다.
