### ISSUE TITLE
홈에서 상위 탭 버튼 링크를 하나로 통일하는 것은 어떨까요?

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/service-apply#166]
현재 : 상단 탭 '우아한테크코스 / 지원하기' 링크 상이. 우아한테크코스를 누르면 새 창- 홈페이지로 이동

링크를 통일하는 것은 어떨까요? 어디를 누르든 지원하기 페이지에 머무를 수 있도록 하는 것이 좋을 것 같아요.

![스크린샷 2020-10-13 오후 4 31 19](https://user-images.githubusercontent.com/47649580/95829801-b68b9a80-0d71-11eb-9d84-2df6182d62fd.jpg)

홈페이지는 아래 바닥글에 깃헙/유튜브 아이콘이 있는 것 처럼 홈페이지 아이콘을 하나 추가해도 좋을 것 같습니다!

**Comment by toneyparky** [comment]
로고와 타이틀(지원하기) 모두 3기 모집 플랫폼 메인(/recruits)으로 이동하도록 처리했습니다.

둘을 `div`로 묶어서 공통의 클릭 범위로 지정해봤지만 타이틀의 지정 범위가 너무 커지는 느낌이라 기각되었습니다.
![image](https://user-images.githubusercontent.com/37579660/95857705-f9ac3480-0d96-11eb-8645-3f8dbfa96eea.png)
(너무 큰 클릭 범위)
