### ISSUE TITLE
지원서 작성 페이지 > 여러 URL을 올릴 수 없다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/service-apply#167]
![image](https://user-images.githubusercontent.com/46308949/95830612-ebe4b800-0d72-11eb-97ca-14ec6884031a.png)

여러 URL을 기재할 수 있어야 할 것 같습니다!

**Comment by woowahan-pjs** [comment]
> 블로그, GitHub, 포트폴리오 주소 등을 입력해 주세요.
(여러 개라면 Notion, Google docs 등을 활용하여 하나로 묶어 주세요.)

**Comment by dks301** [comment]
![image](https://user-images.githubusercontent.com/32732560/95857695-f4e78080-0d96-11eb-935c-3635cec740bf.png)

### 문제점
아래 괄호 안의 문장이 두 줄로 표시된다.

### 해결방법
폰트 사이트를 줄여서 해결!
