### ISSUE TITLE
지원한 이력이 있는 경우의 사용자 경험이 불편합니다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/service-apply#168]
## 재현 방법
지원하기 > 지원서 작성 후 임시 저장 > 다시 지원하기 버튼을 눌러 지원을 할 경우

## 이슈 내용
1. 기존에 입력한 내역으로 지원하기를 누를 경우 이전에 기록한 내역이 있다고 한 뒤 뒤로 튕깁니다.
2. 기존에 작성한 정보와 다르면 "요청 정보가 기존 지원자와 일치하지 않습니다"라는 문구가 노출됩니다.

## 제안하는 내용
1. 기존에 입력한 정보를 똑같이 입력한 경우 그대로 로그인을 한 뒤 진행하는 것과 같이 이어서 진행할 수 있게 하면 어떨까요?
2. 기존에 입력한 정보와 다르게 입력한 경우 지원서 작성한 이력이 있다고 알려준 다음 로그인 페이지로 이동 시키면 어떨까요?

![image](https://user-images.githubusercontent.com/46308949/95831262-c86e3d00-0d73-11eb-8cae-1890d4bb7f0e.png)

**Comment by woowahan-pjs** [comment]
- 기존 정보와 일치한다: **해당 지원에 동일한 이메일이 존재**하고 나머지 정보도 모두 일치한다.
- 기존 정보와 다르다: **해당 지원에 동일한 이메일이 존재**하고 나머지 정보 중 일부가 다르다.

"이미 신청서를 작성했습니다. 로그인 페이지로 이동합니다."라고 보여 주고 로그인 페이지로 리다이렉션한다.
