### ISSUE TITLE
AWS SES를 사용하여 이메일을 보낸다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#177]

**Comment by LTTTTTE** [comment]
https://jojoldu.tistory.com/246
블로그는 발신인이 특정주소인데
테스트해보니 발신인에 특정 도메인도 가능하더군요!

**Comment by woowahan-pjs** [comment]
- [AWS 자격 증명 작업](https://docs.aws.amazon.com/ko_kr/sdk-for-java/v1/developer-guide/credentials.html)
- [Amazon SES에서 이메일 전송 테스트](https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-email-simulator.html)
- [Amazon Simple Email Service 개발자 가이드](https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/ses-dg.pdf)

**Comment by woowahan-pjs** [comment]
- [SendEmailRequest](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html)
- [SendTemplatedEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendTemplatedEmail.html)

**Comment by woowahan-pjs** [comment]
### `wooteco@gmail.com`

#### Gmail

<img width="300" alt="" src="https://user-images.githubusercontent.com/48229284/96222158-afa99580-0fc6-11eb-8fce-e92907dc059f.png">

#### NAVER

<img width="300" alt="" src="https://user-images.githubusercontent.com/48229284/96222267-e97a9c00-0fc6-11eb-9213-6b9a6f541735.png">

### `woowa_course@woowahan.com`

#### Gmail

<img width="300" alt="" src="https://user-images.githubusercontent.com/48229284/96222243-dd8eda00-0fc6-11eb-9511-112c5e924abb.png">

#### NAVER

<img width="300" alt="" src="https://user-images.githubusercontent.com/48229284/96222087-96084e00-0fc6-11eb-864c-8085d1e94ba8.png">
