### ISSUE TITLE
지원서 작성 페이지 가로 길이가 조금 더 넓으면 어떨까요?

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/service-apply#186]
복사 붙여넣기를 하는 경우가 많겠지만 굳이 좁을 필요는 없을 것 같아서요 ^^;;

## AS IS 
![image](https://user-images.githubusercontent.com/46308949/96225718-7542f700-0fcc-11eb-974e-e8740fb1d14d.png)

## TO BE
![image](https://user-images.githubusercontent.com/46308949/96225506-22693f80-0fcc-11eb-9ac7-6e17ecef231a.png)

**Comment by toneyparky** [comment]
오 브라운 컨트리뷰터하시는 건가요 😬
