### ISSUE TITLE
지원서 작성 화면에서 새로고침 시 로그인이 풀립니다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/service-apply#187]
재현 스텝: 로그인 > 지원서 작성 > 새로고침

**Comment by woowahan-pjs** [comment]
http://blog.knowgari.com/state%EC%B4%88%EA%B8%B0%ED%99%94%EB%A7%89%EA%B8%B0

**Comment by woowahan-pjs** [comment]
https://github.com/woowacourse/service-apply/issues/44
