### ISSUE TITLE
지원이 완료되면 지원 완료 메일을 보내는 기능을 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#237]

**Comment by MyaGya** [comment]
아론과의 페어중 문제 발생

1. 메일 시스템은 AWS SES를 사용하고 있다 ([SES를 사용하도록 변경](https://github.com/woowacourse/service-apply/pull/185))
2. 이 시스템에서는 키가 필요하나 현재 키가 존재하지 않는다
3. 구현은 `AwsMailSender.Class`가 구현하고 있으며 실제 사용 키는 스프링이 관리하여 주입시켜 사용한다
![image](https://user-images.githubusercontent.com/38939015/124221021-d9e1ba00-db39-11eb-9baf-d4933dde724e.png)
![image](https://user-images.githubusercontent.com/38939015/124221030-dd754100-db39-11eb-98a3-7615f5d2217f.png)

4. 해당 키는 application.properties에 존재해야 한다. 현재는 존재하지 않는 듯 보인다
![image](https://user-images.githubusercontent.com/38939015/124221091-faaa0f80-db39-11eb-947e-83f9aed33580.png)


5. 따라서 키를 발급해서 사용하려 했으나 권한이 존재하지 않는다.
![image](https://user-images.githubusercontent.com/38939015/124221053-e6fea900-db39-11eb-85ee-1b67585fb18e.png)


추가 참고링크
https://jojoldu.tistory.com/246
https://github.com/woowacourse/service-apply/pull/107/files

**Comment by MyaGya** [comment]
권한을 받거나 키 자체를 받아야 할 것 같아요

**Comment by Sehwan-Jang** [comment]
현재 테스트를 돌려보거나 postman으로 메일 발송 요청 시 
![image](https://user-images.githubusercontent.com/68985748/124221678-32fe1d80-db3b-11eb-8178-05a66cd6ccb0.png)
위와 같이 `InvalidClientTokenId` 에러가 발생하게 되고 메일도 발송이 안되는데 
저랑 마갸는 키의 문제라고 생각하고 있습니다.
