### ISSUE TITLE
지원서 제출 완료 후 내 지원서 내용 확인하기 기능 

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#238]
- 현재 지원 완료 후에는 확인 불가
- 기능 자체의 필요성부터 논의
   - 필요한 경우 지원서 페이지 Vue->React 마이그레이션 완료 이후 추가 수정 진행 (w/백엔드)
   - 필요하지 않은 경우 그대로 close

**Comment by SunYoungKwon** [comment]
@woowahan-pjs
지원 완료 후 지원서를 다시 확인할 수 없으므로 이 이슈는 닫아도 될 것 같습니다!
