### ISSUE TITLE
지원자 등록 시 생년월일 입력 방식 개선

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#240]
- 생년월일을 달력으로 입력 받으면 어떨까?
- 달력 형식이 아니더라도 사용성 개선을 위한 방법 고려

**Comment by jho2301** [comment]
datalist 태그를 이용해 추천리스트를 제공하는 것이 가장 적합할 것 같습니다.

### datalist의 장점

- html에서 제공하는 스펙으로 별도의 js 제어가 필요하지 않음
- 사용자 입력에 따라 추천 목록이 바뀜

### 적합하다 생각하는 이유

- 기존 input이 연월일 3개로 분리되어 있다.
- 달력 UI는 모바일에서 조작하기 어려운 면이 있다. 
- 달력 UI보다 사용법이 직관적이다.
