### ISSUE TITLE
지원자 등록시 유효한 이메일인지 인증하는 기능 추가

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#242]
- 테스트 중 가짜 이메일로 등록한 계정으로 비밀번호 찾기를 시도해서 계정 잃어버리는 케이스 발생
- 가입하는 시점에 유효한 이메일인지 검증하는 절차가 추가되면 좋을 것 같다.
   - 이메일 형식 검사
   - 혹은 좀 더 확실하게 확인하는 메일 보내서 인증하도록 -> 이 경우 백엔드까지 확인 필요
 - 중복 이메일 여부를 검사하는 기능도 함께 고려 -> 백엔드까지 확인 필요

**Comment by knae11** [comment]
# 정리

- 이메일 확인방식으로 구현
- 개인정보 입력 후, 다음을 누르는 순간 회원가입이 됨
- 회원가입을 하는 순간 작성된 이메일에 링크를 포함하여 발송
- DB의 APPLICANT 테이블에 `authenticated` 컬럼을 추가하여 처음에는 `false` 값으로 지정
- 이메일에 링크를 누르는 순간 `authenticated=true` 로 변경되어 인증된 사용자가 됨
- 다시 로그인해서 작성해야됨

# 이슈

- `authentificated=false` 인증되지 않은 사용자는 로그인이 되지 않게 한다.
- 모든 로그인 기능에서 `authentificated=true` 인 사용자만 인증된 사용자로 처리한다.
- 로그인을 시도할 때만  `authentificated=true` 를 확인하면 된다.

# 필요한 API

- 이메일 링크에서  `authentificated=true` 로 바꿔줄 [patch] api

**Comment by Sehwan-Jang** [comment]
## 변경 내용
 + 회원가입시 (개인정보 입력 후 다음 누를 시) 메일 인증 메일 발송하도록 변경.
+ Applicant 엔티티에 authenticated, authenticateCode 컬럼 추가
+ authenticated = 인증 과정을 거쳤는지에 대한 여부. 발송 된 메일 버튼 클릭 시 인증 절차 진행
+ authenticateCode = 인증 과정에서 필요한 랜덤 코드
## 추가되어야 할 이슈
+ 현재 인증 API를 인증 메일 버튼을 통해 접근하도록 구성되어 있음. 해당 기능을 위한 프론트 페이지가 필요 [예상 기능(인증 성공, 인증 코드 불일치, 이미 인증된 사용자)]
+ 인증 상태를 등록 할 수는 있으나 인증 관련 정책은 고려하지 않았음(인증 해야만 사용 가능한 기능 등)

**Comment by MyaGya** [comment]
#283 
#284

**Comment by knae11** [comment]
# 예상 시나리오

1. 이메일이 발송되면 `인증` 버튼을 누른다.
2. 새롭게 만들어지는 프론트 페이지로 이동한다.
    1. 페이지가 로드되는 동시에 put, patch 요청으로 authenticated 로 인증되는 요청을 보내고
    2. 사용자는 로그인을 한다.
