### ISSUE TITLE
지원 화면을 Vue -> React로 마이그레이션한다.

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#243]
### 목표
- 현재 Vue 기반으로 구성되어 있는 지원 화면 UI 영역을 React 기반으로 마이그레이션한다.

### 진행 방법
- Vue에 대한 기본적인 학습 선행
- AS-IS 요구사항들을 React로 옮기는 작업 목록 일정 추산
- 마이그레이션 작업 진행
- 아주 작은 단위의 버그 수정&기능 개선은 마이그레이션 작업에 포함하여 진행 
  - 백엔드 작업까지 필요한 큰 단위라면 마이그레이션 완료 이후에 진행

#### components 
- [x] #260
- [x] #261

#### views(마이그레이션 시 폴더명을 pages로 변경)
- [x] #262
- [x] #263
- [x] #264
- [x] #265
- [x] #266
- [x] #267
- [x] #268
- [x] #269

### 관련 이슈
- AS-IS 요구사항 정리 - https://github.com/woowacourse/service-issues/issues/72

**Comment by woowahan-pjs** [comment]
- `develop` -> `refactor/react`: 리액트 마이그레이션을 위한 베이스 브랜치 생성
- `refactor/react` <- `feature/react-project-setting`: 마이그레이션
- `develop` <- `refactor/react`: 마이그레이션 완료

**Comment by SunYoungKwon** [comment]
vue로 된 코드에서 아래 2 부분으로 나눠서 각각 마이그레이션 작업하고, 서로 합쳐서 기존 기능이 정상적으로 동작하는지 확인하는 시간을 따로 가지는 방향으로 작업하려고 합니다.
@woowapark 어떻게 생각하세요?

- components폴더 (refactor/react -> refactor/react/components)
- main.js, App.vue, views폴더, store폴더 (refactor/react -> refactor/react/pages)
- 서로 작업 완료 후 합쳐서 기능 테스트 진행

**Comment by woowapark** [comment]
@SunYoungKwon      
`2 부분으로 나눠서` = 브랜과 썬이 나누어 작업하신다는 뜻일까요?-? 아니면 작업을 2단계로 나누고 작업 자체는 같이 하신다는 뜻일까용?

**Comment by SunYoungKwon** [comment]
@woowapark 각 파트를 한 사람씩 맡아서 한다는 이야기였어요!

**Comment by woowapark** [comment]
@SunYoungKwon 
아하 🤔      
음 그러면 정상동작 테스트를 마지막에 한번에 해야 하다보니, 합치는 과정에서 확인할 포인트들도 많을 것 같은데요 🤔        
한사람씩 맡아서 하더라도, 페이지 단위 정도로 확인은 주기적으로 합쳐가면서 해보는 건 어떨까요?      
ex).   
- views > ApplicationRegisterVue 전환
  - 요 페이지에서 필요한 컴포넌트들 react로 전환
  - store 연결
  - 페이지 동작 확인
- 다음 views > 하위 페이지 전환 진행

**Comment by SunYoungKwon** [comment]
components를 먼저 작업한다고 생각했던 이유가 여러 페이지에 공통적으로 사용되고 있는 컴포넌트들이 들어 있어서 였어요.
처음부터 페이지별로 나누면 공통 컴포넌트를 어느쪽에서 작업할 지 논의해야하고, 그 페이지가 완료되지 않으면 공통 컴포넌트를 가져다 써야하는 다른 페이지 작업은 대기해야 할 것 같아서요. 

> 2. views(pages로 변경예정)파일 각각을 하나의 이슈로 가져가서 페이지 별 동작 확인

요기가 공통 컴포넌트 작업(2명이 반 씩 나눠서 진행)이 완료된 후, 
한 페이지 마이그레이션 + 해당 페이지 동작 확인 + 공통 컴포넌트는 미리 작업된 것 가져다 쓰기
를 하나의 이슈가 되는 것으로 생각한 부분이었습니다.

@woowapark 이런 부분을 고려하더라도 주기적으로 확인하며 진행하기에 처음부터 page별로 나누는게 더 용이할까요?

+) 현재 전역으로 관리하고 있는 상태가 얼마 없어서 브랜과 협의하여 일단 store는 만들지 않고 App에 상태로 가지고 내려주는 방식으로 마이그레이션하기로 했어요(요 부분을 미리 공유하지 않은것 같네요ㅠ)

**Comment by seojihwan** [comment]
페이지와 페이지에 필요한 컴포넌트들을 작업할 때 페이지 단위로 맞추면 더 수월하겠네요 감사합니다!

**Comment by woowapark** [comment]
#### 작업 방식 
아하 새로 정리해주신 방식이라면 크게 문제 없을 것 같습니다.       
통합하는 작업 자체를 단위를 끊어서 가지 않고, 맨 처음에 적어주신 것처럼 앱 전체를 한번에 합쳐서 확인하는 경우에     
확인할 포인트가 한번에 너무 많아질 수 있을 것 같아서 의견 드린 부분이었어요 🙂        
말씀해주신 것처럼 
- 컴포넌트들 전체 전환 (같이)
- 한 페이지 단위로 전환한 컴포넌트들 조립하면서 마이그레이션 -> 동작확인    

이라면 우려했던 부분은 크게 없을 것 같아요.       

#### 상태 관리
우선 협의하신 대로 진행해보시고,      
마이그레이션 작업이 어느정도 진행된 뒤에 한번 필요성을 다시 고민해보아도 좋을 것 같습니다~

**Comment by SunYoungKwon** [comment]
### 작업 일정 이슈 나누기

@seojihwan @woowapark 확인해주세요~

#### components 
- components/form 폴더 내 컴포넌트를 react로 전환한다.
- components 폴더 내 컴포넌트를 react로 전환한다.

#### views(마이그레이션 시 폴더명을 pages로 변경)
- App 컴포넌트를 react로 전환한다.
  - router 설정
  - store폴더에서 관리하던 상태를 App의 상태로 변경하기
  - 기존 constants 파일 가져오기(constants 폴더 따로 만들기)
- Recruits 페이지를 react로 전환한다.
- ApplicantRegister 페이지를 react로 전환한다.
- ApplicationRegister 페이지를 react로 전환한다.
- Login 페이지를 react로 전환한다.
- PasswordEdit 페이지를 react로 전환한다.
- PasswordFind 페이지를 react로 전환한다.
- PasswordFindResult 페이지를 react로 전환한다.

**Comment by woowapark** [comment]
@SunYoungKwon @seojihwan      
크게 문제될 부분은 없을 것 같아요~         
- 다만 상태 관리 같은 경우, 이후에 스토어를 추가하게 될 수도 있으니      
  그런 경우에 어떤 영역이 스토어에 들어갈 법한 부분일 지 잘 구분할 수 있게 해주시면 좋을 것 같습니다.      
  (우선 없이 마이그레이션 작업부터 먼저 진행해본 뒤에 수정이 필요하게 되면,     
  혹은 꼭 여러분이 적용하지 않더라도-다음 기수에 확장하게 되더라도,      
  혹은 여러 컴포넌트에 걸쳐서 관리해야 하는 상태가 늘어나서 상태관리 라이브러리를 도입해야 할 때 수정 범위가 지나치게 크지 않게 등등 여러 경우를 대비해서요~)                 
- 페이지 전환하실 때 사용자가 실제로 사용하게 되는 흐름 순서를 고려해서 작업 진행해주시면 페이지 단위로 마치고 테스트 할 때에도 순차적으로 하기 좀 더 좋지 않을까 싶네요

**Comment by woowapark** [comment]
브랜까지 함께 확인하고 나면     
할 일 목록 형태로 이 이슈 본문에 추가해주시고 체크해가면서 진행해주시면 될 것 같아요~

**Comment by SunYoungKwon** [comment]
@woowapark 
현재 작성해둔 순서가 사용자가 사용하게 되는 순서되로 되어있어 작성된 순서대로 진행하면 될 것 같습니다.

@seojihwan 
확인해주세요~

**Comment by seojihwan** [comment]
넵 순서대로 이슈남겨서 진행하면 될것 같습니다!
컴포넌트간 공유해야할 상태는 우선 App 컴포넌트에서 내려주는 방식으로 작업하면 될 것 같습니다
