### ISSUE TITLE
메인 페이지 디자인 개선

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#244]
- ‘분위기가 우테코 홈페이지와 매우 달라요’ 비슷하게? 혹은 다른 방식으로 개선해보면 좋을 것 같다.

**Comment by SunYoungKwon** [comment]
우테코 홈페이지 디자인과 유사하게
- 배경색 흰색으로 변경
- 본문 영역 box-shadow 추가

**Comment by SunYoungKwon** [comment]
## 개선안

[Figma 링크](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=207%3A2)

- 개선안을 빠르게 반영할 수 있도록, 기존 디자인의 레이아웃을 유지하면서 배경, 선, 여백 위주로 변경
- 회원관리 기능이 도입될 것을 고려함
  - header에 로그인, 회원가입 버튼 배치
  - 로그인 시 회원버튼(내 정보조회, 로그아웃 등) 표시
-  기존 버튼 색상을 키 컬러로 사용(`#0078FF`)

### 기존 메인페이지
![변경 전 메인페이지](https://user-images.githubusercontent.com/45230497/132146544-f862b03f-5c42-4aa7-983b-6eb0ace6f294.png)

### 변경 후 메인페이지
![변경 후 메인페이지](https://user-images.githubusercontent.com/45230497/132146109-0ad84e5e-d59c-4cbf-9220-efd60183a71c.png)
