### ISSUE TITLE
지원자가 같은 기수에 중복 지원할 수 없는 기능을 구현한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/service-apply#254]

**Comment by MyaGya** [comment]
지원시 기수별로 모집 단위를 구별하며
같은 기수라면 한 분야에만 지원이 가능하며
다른 기수라면 이전 지원 이력에 상관없이 지원 할 수 있다

**Comment by woowahan-pjs** [comment]
- 동일한 기수에 대한 중복 지원의 경우 409 응답 상태 코드(https://tools.ietf.org/html/rfc7231#section-6.5.8)를 내려 준다.
- `SameTermApplyException`라는 커스텀 예외를 만든다.
