### ISSUE TITLE
메일 발송 템플릿을 고려해 본다

### ISSUE THREAD

**Issue by MyaGya** [woowacourse/service-apply#255]
#237 
메일 발송에 필요한 템플릿에 대한 협의가 필요하다.

**Comment by SunYoungKwon** [comment]
[Figma에서 보기](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=219%3A2)

파노(@jho2301)와 함께 진행했습니다! 

![image](https://user-images.githubusercontent.com/45230497/132526596-df9c7171-ea6d-44b6-92d6-20eded5e0a05.png)
