### ISSUE TITLE
리액트로 전환하며 리팩터링할 부분을 정리한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#272]

**Comment by SunYoungKwon** [comment]
- 태그 사용이 적절하지 않은 경우 변경하기.
  - 예. `TextField` 컴포넌트의 `<label>`태그 내에서 `<label>`태그를 다시 사용하는 구조.
- `Button` 컴포넌트의 type 기본 값이 'button'이다. 하지만 원래 `<button>`태그 type의 기본값은 submit이므로 혼란을 방지하기 위해 태그의 기본값과 동일하게 지정하기.
- css에 나눠져있는 컬러 상수화가 필요함.
- `Form` 컴포넌트 내에 `footer`를 분리하기
- 스타일링만을 위해 너무 작게 나눠진 컴포넌트의 경우 용도에 따라 적절하게 합치거나 분리하기.

**Comment by SunYoungKwon** [comment]
### [Recruits, ApplicantRegister and ApplicationRegister](https://github.com/woowacourse/service-apply/pull/291) 페이지를 작업하며

- 제어 컴포넌트 로직 공통화
- 매직넘버, 안내/오류 메세지 상수화
- `ruleField` 컴포넌트를 사용하지 않고 있음
- 새로고침 후에도 accessToken을 유지하기
  - (논의필요) 지원서 작성 중에 새로고침 시 화면을 유지시킬것인가? 현재 로직으로는 불가능
- 모집정보를 나타내는 컴포넌트들의 props 형식 통일
  - 모집 객체로 받는 것과 `title`, `startDateTime`, `endDateTime`을 각각 나눠 받는 경우가 혼재되어 있음
- api 요청 변수명 수정
  - 데이터를 가져오는 동작이 아니어도(예, post) `fetch-`형식의 네이밍을 사용함.
