### ISSUE TITLE
부정행위자 정책을 정하고 개발 이슈를 정리한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#274]

**Comment by NewWisdom** [comment]
**전 기수의 부정행위자를 해당 기수에 지원하지 못 하게 막는 방법**

### 현재 부정 행위자에 대한 정책

- 지원서 제출 단계에서는 부정행위 여부를 검토하지 않음
- 부정행위자도 지원서를 제출할 수 있음
- 평가 단계에서 부정 행위 여부를 파악

### 부정 행위자 정책

- 지원서 생성 시점인 `applicationFormService.create(applicant.id, request)` 에서
`applicant.id`를 통해 Cheater를 조회한다.
- 부정행위자(Cheater)로 등록이 되어 있을 시 예외를 발생시킨다.

**Comment by NewWisdom** [comment]
### 부정행위자 관리 정책

* 부정행위자는 이메일로 구분한다.
* 부정행위자 등록시 이메일과 이에 대한 부정행위 내용도 함께 등록한다.
* 지원자가 이메일로 자신의 부정행위여부를 파악하는 것을 막기 위해, 지원 시점에서는 부정 행위자 여부를 알려주지 않는다.
    * 부정행위자도 지원서를 제출할 수 있다.
    * 기존과 같이 평가 단계에서 부정행위 여부를 파악한다.
* 이번 기수 교육 대상자 선정 과정에서 이전 기수 부정행위자들에 대한 정보를 가지고 있어야 한다.
    * 이에 따라 개인정보처리방침 `3. 개인정보 보유 및 이용기간`에 해당 내용을 추가한다.

    ```jsx
    우아한형제들은 개인정보보호법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 등 관련 법령 상의 개인정보보호 규정을 준수하며, 개인정보의 보호에 최선을 다하고 있습니다.

    1. 개인정보의 수집·이용 목적
    - 우아한테크코스 지원자 모집 및 대상자 선정

    2. 개인정보 수집 항목
    - [필수] 이름, 이메일, 연락처, 성별, 생년월일

    3. 개인정보 보유 및 이용기간
    - 우아한테크코스 2기 교육 대상자 선정 이후 파기

    위 개인정보 수집·이용에 동의하지 않으실 수 있으며, 동의하지 않으실 경우 우아한테크코스 지원이 제한됩니다.
    ```

    - 개인정보처리 관련 이슈: [https://github.com/woowacourse/service-apply/issues/66](https://github.com/woowacourse/service-apply/issues/66)

**Comment by NewWisdom** [comment]
## 부정행위자 개발 이슈

### 부정행위자 등록 화면을 수정한다

![image](https://user-images.githubusercontent.com/43840561/128665678-b651c36e-13ba-4946-ab6d-a33771f59241.png)


- 현재 지원자를 선택하고 버튼을 누르기만 하면 부정행위자로 추가가 된다.
- 부정행위자에 대한 설명을 함께 등록할 수 있는 폼을 추가한다.

### 부정행위자 조회 화면을 수정한다

- description(부정행위자 설명) 필드도 함께 조회되도록 변경한다
---

### Cheater 도메인을 수정한다

- email 필드를 추가한다 - 부정행위자의 개인 정보
- description 필드를 추가한다 - 부정행위자 설명
- applicantId 필드가 제거될 수 있다

해당 기수 부정행위자에 대한 applicantId는 가져올 수 있으나, 
선발이 완료되면 개인정보가 파기되니 이전 기수 부정행위자에 대한 applicantId를 가질 수 없다.

때문에 applicantId로 조회 & 저장이 아닌 email만으로 식별해야한다.

### 부정행위자 등록 기능을 수정한다

- applicant.email로 이미 등록된 부정행위자인지 검증한다.
- applicant의 Id, email과 description(부정행위자 설명)을 함께 저장한다.
- 현재 부정행위자 등록 API인 [POST] "/api/cheaters"에서 email과 description을 요청 바디로 받도록 변경한다.

### 부정행위자 조회 기능을 수정한다

- 부정행위자 테이블에 저장된 email으로 현재 존재하는 지원자에 대해서만 목록을 응답한다.
- 응답값에 description(부정행위자 설명) 필드를 추가한다.

### 부정행위자 여부가 포함된 조회 기능들을 수정한다

- ApplicantService#findAllByRecruitmentIdAndKeyword
- EvaluationTargetService#load
- 위 기능들 안의 applicantId로 부정행위자를 조회해오는 로직을 email로 조회해올 수 있도록 변경한다.

**Comment by MyaGya** [comment]
고생하셨습니다! 어떤 기능인지 충분히 이해가 되었어요
다만 부정행위자와 관계있을지는 모르겠지만 개인정보 보유기간에 대한 의문점이 있는데요
자세히 보니 180일간 `개인정보` 를 보유할 수 있는 것 같아요

1. 이메일이 `개인정보` 에 포함되나요? 포함된다면 180일만 보유할 수 있으니 보통 1년단위로 모집하는 우아한 테크코스 지원 시스템에서는 이메일 사용이 불가능하지 않나요?
2. 위와 관련된 문제인데 이메일로만 부정행위자를 특정할 수 있나요? 만약 부정행위자를 이메일로만 특정한다면 부정행위자가 다른 이메일을 통해 지원하는 경우를 특정 할 수 있나요?

**Comment by knae11** [comment]
확인하고 싶은 내용들에 대해 적어보았어요! 혹시 충분히 설명해 주셨는데 제가 중복 질문한 것이라면 봐주세요 🙏 😂

## 1
- 개인정보 유지기간을 연장하도록 변경한다는 이야기일까요? (3번 문항에 추가한다는 말이 개인정보는 모집후 파기가 아니고 몇년간 개인정보를 유지한다 등의 내용으로 변경되는 건가요?)
- 이메일 정보만 유지되고 그 외 생년월일, 핸드폰 번호 등등은 파기되는 건가요?

## 2
>부정행위자 조회 화면을 수정한다
description(부정행위자 설명) 필드도 함께 조회되도록 변경한다

- 부정행위자 설명은 목록처럼 한줄로 간단하게 표시되는 걸까요? 상세보기처럼 해당 부정행위자를 클릭하면 해당 내용에 대한 설명이 나오는 걸까요?
## 3
>현재 지원자를 선택하고 버튼을 누르기만 하면 부정행위자로 추가가 된다.
부정행위자에 대한 설명을 함께 등록할 수 있는 폼을 추가한다.

- 현재 지원자를 선택하는 방법이 궁금합니다! 모집단위로 모든 지원자를 볼 수 있는 것인지, 위에 사진처럼 목록이 셀렉트바에 뜨는 걸까요? (지원자가 몇 천명도 될 수도 있다고 생각해서 궁금합니다.ㅎㅎㅎ 이메일로 검색하게 되는 걸까요?)
- 부정행위자에 대한 설명은 부정행위자로 추가한 뒤, 추가하고 싶을 경우 부가적으로 작성하는 건가요? (이 또한 상세보기 처럼 해당 부정행위자를 선택하면 작성할 수 있게 될까요?)

**Comment by NewWisdom** [comment]
@MyaGya 
말씀하신 180간 개인정보 보호는 관련 이슈에 있는 우아한 형제들 채용에서의 개인정보 보호방침일겁니다! ㅎㅎ
1. 넵 함께 첨부한 우아한테크코스 `2. 개인 정보 수집 항목`에 따르면 `이름, 이메일, 연락처, 성별, 생년월일`들이 정책 상 개인정보로 분류된다고 합이렇게 수집한 정보를 지원 기수 교육 대상자 선정 이후 파기하게됩니다!
현재의 개인정보처리방침의 경우 선정 이후 모든 정보가 파기되기 때문에 이전 기수의 부정행위자에 대한 정보도 파기 됩니다.
따라서 이전 지원 이력 확인을 위한 이메일 보관 기간에 대한 내용이 추가되어야 하는데, 
질문을 받고 보니 이메일 보관 기간을 얼마로 산정할 것인지에 대한 논의도 필요하겠다고 생각되네요 !
추가로 수정해놓았습니다 !
2. 사실 휴대폰 인증도 필요할까를 고민해보았었는데, 저번 회의에서는 휴대폰 인증이나 추가적인 인증들이  결국 비용이기 때문에 이메일 인증으로 구분하기로 결론 짓게 되었습니다! 부정행위자가 지원하는 시점에서 부정행위 이력이 있는지 알려주지 않아 기록이 남은 이메일인지 알 수 없어 이 문제는 어느정도 해결할 수 있다고 이야기가 되었습니다. 하지만 현재 정책으로는 다른 이메일을 통해 지원하는 경우는 막을 수 없어 방법이 있을지는 조금 더 고민해보아야할 것 같습니다 ㅎㅎ ㅠ
리뷰 감사합니다 👏

**Comment by NewWisdom** [comment]
@knae11 
1. 위에 마갸 질문을 먼저 답하고 보니 이 질문이랑 이어지네요! ㅎㅎ 개인정보처리방침에 대한 내용이 모호하게 적혀있어서 수정해보았습니다! 
`이메일 정보만 유지되고 그 외 생년월일, 핸드폰 번호 등등은 파기되는 건가요?`에 대해서는 지원자의 개인 정보를 함부로 보관할 수 없으니 부정행위자를 구분하는 이메일 정보만 보관하면 될 것 같다는 생각입니다!
2. 해당 내용에 대한 명확한 기능이 드러나지 않았었네요!!! 상세내용확인 버튼 클릭시 해당 내용을 띄워주는 방향으로 해당 이슈 내용을 수정해보았습니다!! 감솨함니당
3. 현재 등록 시 키워드를 통해 지원자 검색이 가능하고 셀렉트 박스에서 선택이 가능합니다. 해당 내용인 `현재 지원자를 선택하는 방법`에 대한 자세한 시나리오를 추가하고, 부정행위자에 대한 설명을 함께 등록하는 방법도 해당 이슈 내용에 명시해두었습니다 ㅎㅎ

리뷰 감사합니다 👏

**Comment by Sehwan-Jang** [comment]
정책 고민하고 요구사항까지 도출해내시느라 정말 고생하셨어요 아마찌 👏👏👏
요구사항에 더해 관련 flow 까지 정리해주셔서 이해하기 정말 좋았어요. 
추가적으로 궁금한 사안이나 몇가지 코멘트 남기겠습니다~

### 1. 부정행위자 채점여부
부정행위자들에 대한 조치가 평가 단계에서 이루어지고 있는데, 
이들의 점수를 채점은 하되 추후에 탈락시키는 것인지, 아예 점수를 0점으로 주는 것인지 정할 필요가 있을 것 같아요.
현재 메일 관련 이슈에서 평가대상자의 점수가 0점인 경우 결과 혹은 다음 평가에 대한 안내 메일을 발송하지 않기로 논의가 이루어졌습니다.
그런데, 부정행위자를 0점 처리 해버릴 경우 그들이 미션이나 테스트를 응시하였음에도 메일이 발송되지 않아, 자신의 부정행위 여부를 파악할 수도 있을것이라는 생각이 드네요.
만약 부정행위자들의 점수를 일괄적으로 1 혹은 -1로 고정하는 과정이 있다면, 채점하는 노력을 들이지 않으면서 탈락메일도 발송될 수 있을것 같아요!

### 2. 메일 보관 기간
![image](https://user-images.githubusercontent.com/68985748/128746231-3f8c77d3-20b3-42b7-b5e4-c35c5435385f.png)
우리의 상황이 정확히 이 범주에 들어가는지는 모르겠지만, 이것이 맞다면 개인정보보호 포털에 의하면 지원자의 동의하에 2년까지 보관 가능할 것 같아요!
추가적으로, 이 개인정보들을 자동으로 파기할 것인지, 시간에 맞춰 수동으로 파기할 것인지에 대한 논의도 있으면 좋을 것 같아요~ 😁

**Comment by NewWisdom** [comment]
@Sehwan-Jang
1. 아하 지금 평가대상자 불러오기 `evaluationTargetService.load()`시 부정행위자들은 평가대상자 목록에서 제거가 되고 있네요! 따라서 현재 로직 변경없이 갈 경우 부정 행위자들은 evaluationTarget에 남아 있지 않을거라 메일 발송 이슈를 보니 아예 메일 대상자에서 제외될 것 같습니당.
그런데 말씀대로 부정행위자에게 메일이 발송되지 않는다면 자신의 부정행위 여부를 파악할 수 있는게 맞네요! 부정행위자에게 탈락 메일을 전송하려면 지금 생각으로는 평가 대상자들에게 메일을 보낼 때 해당 평가에서 부정행위자로 등록된 지원자를 따로 조회해 탈락 메일을 발송하는 로직을 추가하고, 부정행위자도 어떤 평가에서 부정행위를 하였는지에 대한 정보를 가지고 있도록 변경할 것 같습니다!
(사실 아니면 부정행위자에 대해서는 따로 탈락메일을 전송하는게 깔끔할수도 있다는 생각도 드네옹)
부정행위자에게 탈락 메일 보내기 메일 발송 정책이 정해진 부분인지 알 수 있을까요?? 탈락 메일 보내기로 정해졌다면 해당 내용들을 반영해 수정해보겠습니다:)  그러면 메일 정책에도 해당 내용을 추가하면 좋을 것 같아요 !! ㅎㅎ
2. 오 감사합니다!!! 저희가 저 범주에 들어간다면 저 내용을 반영해서 약관을 수정할 수 있을 것 같네요 ㅎㅎ
또 제안해주신 추가 논의 사항도 이슈에 함께 적어놓겠습니다!! 

리뷰 감사합니다 👏

**Comment by Rok93** [comment]
먼저 고생 많으셨습니다~! 
전 대부분의 내용은 회의를 통해서 전달받았던터라 이해하는데 그렇게 어렵지는 않았어요~! 

개인정보와 관련된 부분들이 정말 민감해서 `이전 지원 이력 확인을 위한 이메일 보관 기간은 얼마로 산정할 것인지에 대한 논의가 필요` 논의에 대해서 고민해봤는데.... 일단은 법적인 부분이 확실하게 파악을 해야할 것 같은데... 법쪽은 봐도봐도 어렵네요... 😫
참고자료 보면서 최대한 관련 사례들을 가지고와봤는데 저도 아론의 멘트와 마찬가지로 `우리의 상황이 정확히 이 범주에 들어가는지는 모르겠지만`...  1 ~ 3 년 미만 기간동안 보존이 가능하지 않을까? 하고 추측하고 있어요 🤔   이 기간에 맞게 기간을 정하는게 좋을 것 같아요. 
부정행위자는 평생 보관하면 좋겠지만... 어짜피 3년 뒤에도 지원하는 경우는 드물테니... 크게 걱정할 부분은 아니라 생각해요 😃

> 온라인 개인정보 처리 가이드라인 - 방송통신위원회  을 참고한 내용입니다. 

### 개인정보 정의 
![image](https://user-images.githubusercontent.com/47850258/128795038-7e07b247-bc2b-45e6-b406-ae850e164f70.png)

### Q.22 교육접수가 중복되는 것을 방지하기 위해 접수시에는 이름, 생년월일과 성별까 지만수집을하고, 실제교육을신청할때에는이름만받고자할경우동의가 없어도 되나요?

> 실제 교육을 받을 때 이름만 수집한다고 하더라도 접수 시 이미 이름, 생년월일과 성별을 수집하였기 때문에, 개인정보보호법상 특정 개인을 식별할 수 있는 정보에 해당됩니다.
그러므로 특별히 개인정보보호법 제15조 제1항 제2호부터 제6호에 해당하지 않는 한 원칙적으로 정보주체에게 제15조 제2항의 각호 내용을 알리고 동의를 받아서 수집해야 할 것입니다.

### Q. 30 개인정보수집동의서를 받아서 처리할 경우 동의서 내용에 보유 및 이용기간은 개인정보처리자의 필요에 의해 보유기간을 정하면 되는 건가요?

> 개별 법령에 구체적인 보유기간이 명시되어 있지 않은 경우에는 개인정보 보호책임자 의 협의를 거쳐 기관장의 결재를 통하여 결정해야 합니다. 다만, 보유기간은 별표 1의 개인정보파일 보유기간 책정 기준표에서 제시한 기준과 공공기록물 관리에 관한 법률 시행령에 따른 기록관리기준표를 상회할 수 없습니다.

![image](https://user-images.githubusercontent.com/47850258/128795657-ce548d7e-3e6e-442b-a235-728dd814aca8.png)


### Q. 31 서비스 계약과 관련하여 개인정보 보유기간 설정을 어떻게 해야 하나요?

개별 서비스 계약의 특성에 따라 보유기간을 설정하면 됩니다. 만일 특별한 법(예를 들 어 전자상거래소비자보호법 등)에서 정한 기간이 있다면 해당 법률의 정해진 기간에 따 라 보유 가능합니다.

### Q. 32 개인정보의 파기 시기 및 방법은 어떻게 되나요? 

개인정보는 보유기간의 경과, 개인정보 처리목적 달성 등 개인정보가 불필요하게 되었을 때 에는 지체 없이(5일 이내) 파기해야 합니다. 다만, 다른 법령에 따라 보존해야 하는 경우에는 보관할 수 있습니다. 개인정보를 파기할 때에는 복구 또는 재생되지 아니하도록 해야 합니다. 종이에 출력된 개인정보나 가입신청서 등 개인정보가 기재된 문서는 분쇄기로 분쇄하거나 소각해야 합니다.
전자적 파일 형태는 복원이 불가능한 방법(사회통념상 현재 기술 수준에서 적절한 비용 이 소요되는 방법)으로 영구 삭제해야 합니다. 예를 들면, 하드디스크에 기록된 정보를 삭제할 때에는 데이터 복원을 방지하기 위해‘로우레벨포맷’명령으로 포맷을 하거나, 일반 포맷을 한 뒤 불필요한 정보를 여러 번 덮어씌우는 방법으로 다시는 재생할 수 없도록 조치해야 합니다.


출처: [온라인 개인정보 처리 가이드라인 - 방송통신위원회](https://kcc.go.kr/download.do?fileSeq=48641)  (
출처: [개인정보보호법 상담사례집 - 한국인터넷진흥원](https://www.kisa.or.kr/jsp/common/libraryDown.jsp?folder=019144)

**Comment by Sehwan-Jang** [comment]
@NewWisdom 
오 살펴보니까 부정행위자들은 애초에 평가대상자 테이블에 들어가지도 않는군요~ 감사합니다!
이 부분이 문제가 되는 경우는 1차 코딩테스트에 대한 결과 메일을 발송할 때 일것 같은데
그렇다면 확실히 아마찌가 말씀하신대로 메일관련 이슈에서 불합격메일을 발송할때 시험에 응시한 부정행위자들을 포함해주는 것이 좋겠네요.

사실 아직 부정행위자들에게 메일을 발송하는 것에 대한 정책은 없긴해요... (제이슨과 한번 얘기해보면 명확해 질것 같아요 😊)
