### ISSUE TITLE
모집 삭제 정책을 정하고 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#278]

**Comment by knae11** [comment]
# 구현내용
- 제출된 지원서(ApplicationForm)가 있다면 해당 모집(Recruitment)은 삭제될 수 없다.
- 해당 모집이 삭제된다면, 모집항목(RecruitmentItem), 평가(Evaluation), 평가항목(EvaluationItem)이 함께 삭제된다.
    - 지원서가 없다면 ApplicationFormAnswer, EvaluationTarget, EvaluationTargetAnswers 도 존재할 수 없다.

**Comment by knae11** [comment]
# 정책 재변경 사항(기존 로직과 거의 유사)

- ✨ 지원서가 있어도 모집을 삭제할 수 있다. (모집삭제와 관련하여 모집중 이외의 제약사항이 없음)
- 모집 삭제는 `deleted` 라는 컬럼을 추가하여 **논리삭제**로 구현
- 기존 로직대로 모집 중인 모집은 삭제할 수 없다.
