### ISSUE TITLE
모집 상태 정책을 정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#279]
관련 이슈: #64

**Comment by MyaGya** [comment]
# 기본 모집 상태
기본적으로 모집 상태는 3가지로 정리 할 수 있다
1. 모집 전
2. 모집 중
3. 모집 종료

# 모집의 수정 기능
1. 모집은 공개 / 비공개가 가능하며 비공개시 지원자들은 해당 내용을 확인 할 수 없다
2. 모집은 시작 / 중지가 가능하며, 중지시 지원자들에게는 노출되지만 지원은 불가능하다

# 모집이 시작 / 종료되는 시점
1. 모집을 따로 시작 / 종료 상태로 바꾸는 것은 아니며 지정된 시간이 지날 경우 자동으로 "모집 중" 상태와 "모집 종료" 상태로 바뀐다

**Comment by knae11** [comment]
## 작은 질문
- 모집전, 모집종료 -> 지원불가능
- 모집 종료 -> 지원가능
- 상태인 거겠죠?ㅎㅎㅎ

- 모집상태: 모집전, 모집종료, 모집중
- 모집공개: 비공개, 공개
- 지원가능상태: 지원가능, 지원불가능

- 이렇게 3부분이 존재하고, 지원가능(모집중), 지원불가능(모집전, 모집종료) 이렇게 대응되는 걸까요? 모집상태와 지원가능상태가 각각이 값으로 구분이 되는건지, 논리적으로 모집상태에 따라 지원가능상태가 정해지는 건지 궁금합니다. 😄

**Comment by ecsimsw** [comment]
오우 이렇게 시나리오 케이스를 명확히 잡아주시니까 잘보이네요. 고생하셨습니다.
제가 이 작업을 맡았다고 가정하고, 모호한 부분을 질문드리겠습니다.

1. `"비공개" / "지원 가능" 인 경우 지원자에게는 공개되지 않지만 지원은 가능하다` 
이 부분에서 비공개인 상황에서 지원이 가능한 경우가 저한테 약간 모호한데, 어떤 상황을 제가 빠트렸는지 여쭤보고 싶습니다. 

2. 모집이 비공개로 변환된다면 지원자의 지원서 내역, 임시저장 지원서는 어떻게 처리해야 할지 궁금합니다. 
'모집 상태 정책을 정한다'에 안맞는 질문인가요?? 그렇다면 패스 부탁드리겠습니다 ㅎㅎ

3. `모집을 따로 시작 / 종료 상태로 바꾸는 것은 아니며 지정된 시간이 지날 경우 자동으로 "모집 중" 상태와 "모집 종료" 상태로 바뀐다`
모집이 관리자에 의해 임의로 열리고, 바로 닫혀야하는 상황은 없을까요? 임의로 열고 닫지 못하는 정책으로 이해한게 맞는지 궁금합니다!!

**Comment by MyaGya** [comment]
우선 상태를 다시 정리드리자면
1. 모집 시작시간, 모집 끝 시간을 기준으로 "모집 전", "모집 중", "모집 종료" 상태가 나누어집니다. 모집 상태를 저장하는 건 아니고 현재 시간과 비교하는 로직을 통해서 결정됩니다

2. "공개 여부", "지원 가능 여부" 두 가지 추가 옵션이 있으며 해당 내용은 DB로 저장하여 관리합니다.

3. 기간과 2가지 옵션을 통하여 논리적으로 최종 상태를 결정 후 바깥으로 알려줍니다

===

1. "비공개" / "지원 가능" 의 경우에는 새로운 모집을 올려서 해당 모집이 제대로 동작하는지 확인하고 싶으나 아직 공개하고 싶지 않은 경우에 해당됩니다.

2. 비공개로 변환된다고 따로 연관된 값들을 처리하지는 않습니다. 수정사항에서 언제든 공개 / 비공개로 바뀔수 있기 떄문입니다

3. 관리자가 임의로 열고 닫아지는 경우는 공개 / 비공개 옵션과 지원 가능 / 지원 불가능 옵션에서 충분히 대응 가능할거라 생각됩니다.
