### ISSUE TITLE
메일 발송에 대한 개발 이슈를 정리한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#281]
- 합격자 메일 보내기
- 탈락자 메일 보내기
- 추가 합격자 메일 보내기

**Comment by Sehwan-Jang** [comment]
## 3기 모집 발송 메일

- 온라인 코딩테스트 안내
- 온라인 코딩테스트 초대 메일
- 1차 심사 결과 안내
- 프리코스 진행 목적 및 준비 안내
- 각 프리코스 미션 안내
- 미션 수정 사항
- 프리코스 종료 안내
- 최종 코딩테스트 안내
- 최종 코딩테스트 링크 안내 (비대면 시)
- 최종 코딩테스트 미션 공유 (비대면 시)
- 최종 심사 결과 안내 메일
- kdigital, 내일배움카드 안내 메일
- OT 안내 메일

## 관리자 페이지 메일 발송 기능

- `메일 제목`, `내용`, `첨부파일` `템플릿` 입력
    - 템플릿 통일할 수 있도록 하는 법 고민
- `모집`, `평가`, `합격/불합격/보류/대기(모두)` 입력받아 발송 대상자 특정.
    - 해당 정보들을 통해 특정된 지원자들의 메일주소 얻도록 구현

## 1차, 최종 심사 메일 발송 이슈

- 2 건의 메일은 합격 / 불합격 / 보류 지원자에 따라 다른 메일이 발송되어야 함.
- `/api/recruitments/{recruitmentId}/evaluations/{evaluationId}/targets/renew` 호출되는 순간 합격자를 제외한 모든 evaluationTarget 사라짐.
- 따라서 이 방법대로 할 경우 각 평가단위에서 `평가 완료 후 ~ 해당 api가 호출되기 전`에 메일을 발송해야 함.

## 요구된 과제를 수행하지 않았는데 메일이 발송되는 이슈

- 1차 코딩 테스트에 응시하지 않았는데 1차 불합격 메일이 발송되는 경우
- 프리코스를 제출하지 않았는데 최종 코딩테스트 안내 메일이 발송되는 경우
- 최종 코딩테스트에 응시하지 않았는데 최종 불합격 메일이 발송되는 경우
- 각 단계의 제출 여부를 파악할 수 있으면 제출자에 한해서 안내메일 발송 가능.

**Comment by Sehwan-Jang** [comment]
# **프론트엔드**

### 관리자 페이지에 메일 발송 페이지를 구현한다.

1. 그룹 별 메일 발송을 요청할 수 있어야 한다. 
    - 메일 내용 입력 UI를 구현한다.
        - 메일 제목
        - 메일 내용
        - 첨부 파일
    - 발송 대상 그룹 특정 UI를 구현한다.
        - 시스템에 저장된 데이터로 특정한다.
            - 모집
                - 현재 모집 중인 모집의 목록이 표시되어야 한다.
            - 평가
                - 선택된 모집의 평가 목록이 표시되어야 한다.
            - 합격 / 불합격 / 모두
2. 개인 별 메일 발송을 요청할 수 있어야 한다.
    - 메일 내용 입력 UI를 구현한다.
        - 메일 제목
        - 메일 내용
        - 첨부 파일
    - 발송 대상 그룹 특정 UI를 구현한다.
        - 시스템에 저장된 데이터로 특정한다.
            - 모집
                - 현재 모집 중인 모집의 목록이 표시되어야 한다.
            - 평가
                - 선택된 모집의 평가 목록이 표시되어야 한다.
            - 합격 / 불합격 / 모두
            - 대상자
                - 선택된 합/불 상태의 평가대상자 목록이 표시되어야 한다.
3. 메일 주소를 직접 입력하여 메일 발송을 요청할 수 있어야 한다.
    - 발송할 메일 주소 입력 UI를 구현한다.

# 백엔드

### 메일 발송 API를 구현한다.

1. 메일 발송 대상 특정을 위한 API를 구현한다.
    - Evaluation, EvaluationStatus 를 요청받아, 
    EvaluationStatus에 해당하는 평가대상자들의 메일주소를 응답해야 한다.
        - 탈락자 중 요구된 과제(1차 코딩테스트, 프리코스, 최종 코딩테스트) 를 수행하지 않은 평가 대상자는 제외한다.
            - 수행하지 않았음에 대한 검증은 `점수 == 0` 으로 한다.
2. 메일 발송 API를 구현한다.  
    - 메일 제목, 메일 내용, 첨부파일, 발송 대상 을 요청받아, 
    메일을 발송해야 한다.
        - 발송 대상을 복수(배열, 컬렉션 등)로 받을 수 있어야 한다.
        - 숨김참조를 통해 한번에 발송해야 한다.
            - [https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html) , `BCC`
            - 참조 목록에 우테코 메일도 포함해야 한다.(확인용)
        - 첨부 파일을 포함해 발송해야 한다.
            - [https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-email-raw.html](https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-email-raw.html)

### 메일 발송 히스토리를 기록한다.

1-1. Amazon ES + Kinesis 사용해 이메일 전송 내역을 저장한다.

- [https://aws.amazon.com/ko/premiumsupport/knowledge-center/ses-email-sending-history/](https://aws.amazon.com/ko/premiumsupport/knowledge-center/ses-email-sending-history/)
    - 비용이 발생할 수 있음.

1-2. 데이터베이스에 전송 실패 또는 성공 기록을 저장한다.

- 간단하지만, 사용성에 있어 1-1 방식이 더 좋다고 생각함.

**Comment by Rok93** [comment]
# 개발 이슈 정리
## FE 
### 관리자 페이지 `선발 과정` 탭에 신규 버튼을 구현한다. 
* `평가지 다운로드` 버튼
	* 해당 평가의 평가 대상자들을 기준으로 `평가지` (CSV 파일 예정) 다운받는 기능
* `평가지 업로드` 버튼 
	* 다운받은 평가지를 작성하여, 업로드하는 버튼 
	* 업로드하면, 업로드 된 CSV 파일 내용을 반영하여, DB를 업데이트한다.

## BE 
> 평가지는 CSV 확장자 파일로 정했습니다. 
> XLSX 형식이 아닌 CSV 형식을 사용한 이유는 [CSV와 XLS(Excel)의 차이점](https://she11.tistory.com/61) 을 참고해보시면 좋을 것 같습니다. 
> 
> 총 세가지 작업 이슈로 구분했는데, 이 세 작업을 동시에 진행한다면,  작업이전에 긴밀한 협의가 필요해보입니다. 혹은 `평가지를 다운로드 기능` 을 첫 작업으로 진행하여 `평가지 양식`을 우선적으로 fix한 이후에 fix된 평가지 양식을 기준으로 다른 작업 이슈들도 진행하면 좋을 것 같습니다. 

### 1. 평가지를 다운로드 기능을 구현한다. 
* 파일 형식은 CSV로 한다. 
* 평가지 업로드와 동일하게 아래의 정보를 포함한다. 
	* 지원자 식별 정보(applicantId, 지원자 이름, 지원자 이메일)
	* 각 평가에 대한 점수 (최대 점수) 
		* 각 평가마다 최대 점수가 다르다. 
		* 따라서 최대 점수는 `()` 안에 표기한다. 
		* 더 좋은 방식이 있다면, 변경해도 무방하다. 
	* 평가상태
		* 평가상태는 총 3가지 `PENDING`, `PASS`, `FAIL` 이 존재한다. 
		* PENDING은 크게 고려하지 않아도 된다. 
		* 다음 `평가자 불러오기` 버튼을 누를 때에는 이전 평가자들 중 평가 상태가 PENDING인 평가자가 없다고 가정한다. 
		* 평가 상태는 관리자 페이지에서 수동으로 관리가 가능하나 평가지 업로드를 통해서도 수정이 가능하도록 구현한다. 

### 2. 평가지 업로드 기능을 구현한다. 
* 평가지에는 아래의 정보를 포함한다. 
	* applicantId(지원자 식별번호), 
	* 지원자 이름
	* 지원자 이메일
	* 각 평가에 대한 점수 (최대 점수) 
		* 각 평가마다 최대 점수가 다르다. 
		* 따라서 최대 점수는 `()` 안에 표기한다. 
		* 더 좋은 방식이 있다면, 변경해도 무방하다. 
	* 평가상태
		* 평가상태는 총 3가지 `PENDING`, `PASS`, `FAIL` 이 존재한다. 
		* PENDING은 크게 고려하지 않아도 된다. 
		* 다음 `평가자 불러오기` 버튼을 누를 때에는 이전 평가자들 중 평가 상태가 PENDING인 평가자가 없다고 가정한다. 

### 3.  평가지를 기준으로 평가대상자들 상태 업데이트 기능을 구현한다.
* 평가지 업로드 기능 구현을 작업하는 작업자와 소통하여 `평가지 양식`을 먼저 정한다. 
* 다수의 평가 대상자들의 상태를 업데이트해야하기 때문에 `vulk update`방식을 고려한다.
	* 해당 이슈 상단의 참고자료들을 참고

**Comment by MyaGya** [comment]
확인했습니다! 이정도면 구현하는 시점에서 충분한 정보를 줄 수 있는 것 같아요.
주간 회의 때 CU가 제안주었던 부분도 모두 포함되어  있네요. 고생하셨습니다

**Comment by ecsimsw** [comment]
와... 너무 잘 정리해주셔서 이해가 안된 부분이 없습니다.
회의 때 제이슨이 언급해주신 이유가 있었네요.

1. `발송 대상 그룹 특정 UI를 구현한다. 시스템에 저장된 데이터로 특정한다. 선택된 합/불 상태의 평가대상자 목록이 표시되어야 한다.`
발송 대상 그룹을 쪼끔만 더 구체적으로 여쭤봐도 될까요? 예를 들면 '프리코스 합격자' 또는 '코딩 테스트 백엔드 합격자' 처럼 발송 대상, 합/불 상태 외에 다른 그룹 구분 기준이 있진 않을지 궁금합니다.

그 외 정리해주신 것에 대해 이해가 안 간 부분은 없었고, 
이 정책에 대한 내용이 다른 팀원, 파트장과 회의가 이미 되어서 명확히 고정이 된 상황인지가 개인적으로 궁금하네요.
이를 테면 '미제출자는 탈락 안내 메일을 발송하지 않는다'와 같은 사항이 이미 공유가 되어서 고정이 된 부분인지가 궁금했습니다.

**Comment by MyaGya** [comment]
세세하게 정리해주셔서 알아보기 쉬웠습니다.
단, 메일 발송 히스토리 관련해서 질문이 있어서 남깁니다

1. DB를 사용하지 않으면 Amazon ES + Kinesis 를 사용하는건 확정된건가요?

2. 해당 시스템은 도입되지 않았고 처음부터 도입해야 하는 상황인가요?

**Comment by Sehwan-Jang** [comment]
@MyaGya 
1.
> DB를 사용하지 않으면 Amazon ES + Kinesis 를 사용하는건 확정된건가요?

첨부된 링크를 들어가보시면 아마존에서 es 와 kinesis 를 사용해서 전송내역을 관리하라고 알려주더라구요. 하지만 만약 더 좋은 방법이 있다면 그 방법으로 하는 것도 좋을 것 같아요
<br>

2.
> 해당 시스템은 도입되지 않았고 처음부터 도입해야 하는 상황인가요?

아직 지원플랫폼 aws 콘솔이나 기타 인프라 상황들을 잘 몰라 단정지을 순 없겠지만, 정책 회의 중에 히스토리 관련된 부분도 고민해보라는 피드백을 받은 것을 보면 아마 없는 것 같아요

**Comment by NewWisdom** [comment]
정책 정리하시느라 정말 수고 많으셨습니다!! 깔끔하게 정리해주신 내용들 잘 읽어보았습니다 👏👏
아론이 이슈들을 잘 정리해주신 덕분에 명확하게 파악하기 정말 쉬웠어요!! 짱짱 ㅎㅎ
그냥 저의 작은 궁금점과, 제 이슈에서 부정행위자 메일 발송에대해 이야기가 나와서 이부분에 대한 의견을 남겨보겠습니다! 

#### 부정행위자 메일 발송
아론이 제 이슈에 남겨주신 부분을 다시 보니 현재 로직이 1번 평가에서 부정행위자들이 2번 평가자 목록에 반영되지 않는 것이니
1번 평가 대상자 목록에는 기록이 남아있어 이 평가까지는 메일 발송의 대상이 되고 다음 평가부터 대상이 되지 않겠네요. 
일단 이렇게 되면 평가시에 부정행위자 상태를 불합격으로 만들면 될 것 같다는 생각이 들어요! ㅎㅎ
부정행위자가 불합격 상태에 포함시켜 불합격 메일을 주도록 하는 방안 좋다고 생각합니다!

혹시 다른분들도 보시다 제 코멘트에 잘못된 부분 있으면 말씀 부탁드리겠습니다!
부정행위자 메일 발송 내용이 확정이 되면 제 이슈에 부정행위자 상태에 관한 내용도 반영하겠습니다! 
#### Q1
> 탈락자 중 요구된 과제(1차 코딩테스트, 프리코스, 최종 코딩테스트) 를 수행하지 않은 평가 대상자는 제외한다.
요구사항을 이행하지 않았음에 대한 검증은 점수 == 0 으로 한다.

이 부분에서 과제를 수행하지 않은 평가대상자는 어떠한 평가 상태도 가지지 않게 되는지 궁금하네용.
평가 상태를 가지지 않게 되니 자연스럽게 메일 발송 대상자에서 제외되는 흐름인가요??
아니면 평가 점수가 0인 대상자들을 메일 발송 대상자에서 제외하는 로직이 필요한지 궁금합니다! ㅎㅎ

**Comment by knae11** [comment]
정리를 세세하게 잘 해주셨네요! :)

저도 아마찌의 의견처럼 부정행위자는 불합격자로 만들면 될 것 같다는 생각이 드네요! 

### 작은 질문 남겨봅니다. 
- 요구사항을 이행하지 않았음 -> 요구된 과제를 수행하지 않았음을 의미하는 거겠죠? 주어진 과제에 대한 요구사항을 지키지 못한게 아니라요.
- 해당 검증은 `점수 == 0` 으로 한다면 이 사람들에게는 메일이 발송되지 않는 거죠? 더불어 채점시에는 `0점`은 줄 수 없게 되는 걸까요?

**Comment by Sehwan-Jang** [comment]
@NewWisdom 
### 1.
> 아니면 평가 점수가 0인 대상자들을 메일 발송 대상자에서 제외하는 로직이 필요한지 궁금합니다

현재 코드를 봤을 때 점수가 0인 지원자들을 따로 골라내거나 하는 부분은 없습니다.
따라서 `메일 발송 대상 특정을 위한 API를 구현한다.` 이슈에서 점수가 0인 지원자들은 메일 발송 대상자에서 제외하는 로직을 구현해야 할거 같아요!
<br>

### 2.
> 평가시에 부정행위자 상태를 불합격으로 만들면 될 것 같다는 생각이 들어요

오 좋은 방법이네요! 그런데 이 방법으로 했을 때 한가지 문제점이, 이번 기수 모집 중에 부정행위자로 등록된 지원자들은 그렇게 해도 상관 없지만
  저번 기수의 모집에서 부정행위자로 등록된 지원자들의 경우 아예 이번 기수의 평가대상자로 지정되지 않기에 불합격 상태로 관리할 수가 없을 것 같아요 ㅠㅠ 이 부분에 대해서는 조금 더 고민해보겠습니다!

**Comment by Sehwan-Jang** [comment]
@knae11 
### 1.
> 요구사항을 이행하지 않았음 -> 요구된 과제를 수행하지 않았음을 의미하는 거겠죠? 주어진 과제에 대한 요구사항을 지키지 못한게 아니라요.

네 배럴이 말씀해주신게 맞아요! 코딩테스트에 아예 응시하지 않거나 프리코스 미션을 제출하지 않는 것 등이 이에 해당할 거예요.
요구사항을 이행하지 않는다 라는 말이 조금 헷갈릴 수도 있겠네요. 이 부분은 좀 더 고민해보겠습니다. 피드백 고맙습니다!!

###2. 
> 해당 검증은 점수 == 0 으로 한다면 이 사람들에게는 메일이 발송되지 않는 거죠? 더불어 채점시에는 0점은 줄 수 없게 되는 걸까요?

네 맞아요. 점수 == 0 인 경우 제출하지 않은 것으로 간주하기로 했습니다. 
채점에 관한 부분은 저도 잘 모르겠어요 ㅠㅠ 그런데 씨유가 0점을 제출하지 않은 것으로 볼 수 있다고 하신걸 보면 제출하기만 하면 부여되는 기본점수?? 같은 것이 있지 않나 싶어요 ㅎㅎ

**Comment by Sehwan-Jang** [comment]
@NewWisdom 
앗, 좋은 의견 달아주셨는데 너무 늦게 봤네요 ㅠㅠ
만약 부정행위자 정책쪽에서 로직을 그렇게 수정한다면 메일발송 부분에서는 따로 고려할 필요가 없을 것 같네요! 
좋은 아이디어 감사합니다 ㅎㅎ 반영해서 정리해볼게요
