### ISSUE TITLE
평가 결과 업로드 정책을 정하고 개발 이슈를 정리한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#290]

**Comment by Rok93** [comment]
지원플랫폼 관리자페이지 돌려보면서 어떤 정보들이 필요할지 고민하면서 작성해봤는데, 잘 작성한건지 모르겠네요 😅 
(혹시 아래의 이미지 첨부한 것, 노출되면 안된다면 바로 삭제하겠습니다!)


특정 모집에 특정 평가에 대한 평과 결과를 업로드하기 때문에 `recruitmentId`(모집id) `evalutionId`(평가id) 정보가 필요하다. 
(이 부분은 클라이언트 단에서 받을 수 있을 것 같다고 판단되어, 따로 엑셀 폼에 정보를 포함시키지는 않는다.)

## 평가폼 
(아래의 사진과 같이 '평가지 다운로드', '평가자 업로드' 버튼이 필요할듯 함)
![image](https://user-images.githubusercontent.com/47850258/128053484-093eb947-1356-46af-a507-0ac2ab7ffd9c.png)

구글 시트로 간단하게 [평가를 위한 폼 양식](https://docs.google.com/spreadsheets/d/1Q5h6QuhMgw9XzzG5k93rS87_6kLxr8goahRFYH9Q73M/edit?usp=sharing)을 만들어봤습니다. 

### 평가 결과 업로드 전략

- **평가자 `불러오기 버튼`을 눌러서 평가 대상자들을 업데이트 한다.**
- **평가자 `다운로드 버튼`을 눌러 정해진 평가양식의 평가지(엑셀 폼)를 다운받는다.**
    - 해당 평가지에는 평가 대상자들의 정보(이름, 이메일)가 포함되어있다.
- **평가지에 `나머지 정보`를 입력한다.**
    - `각 평가에 대한 점수`, `부정행위 여부` 정보를 입력한다.
    - 부정행위 여부 정보는 해당사항이 있는 경우 'O' 없는 경우 빈칸(= default)으로 둔다.
- `평가 상태`와 상관없이 업로드 된 파일에 평가가 있다면 평가를 update 한다.**
    - update 이후 평가 상태는 PASS, FAIL, PENDING 중 하나가 된다.
    - 합계를 내림차순으로 두고 N명까지 PASS 그 외의 인원은 FAIL로 둔다.
    - 만약 `합격 컷트라인 점수` 와 동일한 평가 대상자들은 평가 상태를 `PENDING` 로 둔다.
        - 부정행위자는 우선적으로 제외한다.
        - 합격 컷트라인 점수에서 인원이 딱 맞게 뽑힌다면 PENDING이 아닌 PASS를 부여한다.
- **부정행위를 했을 경우 `부정행위 여부` 란에 O, X 입력에 따라 해당 지원자를 부정행위자로 업데이트한다.**
    - 평가 상태는 FAIL로 업데이트한다.
    - 대부분은 부정행위자가 아닐 것인데, X를 default로 주는 것이 더 좋을 것 같음.
- **평가 결과로 `평가자`도 입력을 해야하는데, 평가자는 하단의 `시트 이름`으로 구분한다.**
    - 시트 이름 예시: 제이슨, 씨유, 공원 etc...
    - 처음부터 폼을 다운받을 때, 총 평가자 수를 입력하여 평가자 수만큼 적절히 평가 대상자를 나눠서 (특정 평가자의)시트별로 나눠서 작성한 뒤 전달해주면 더 좋을 것 같음.

### 고민해볼 점

- 각 평가마다 `최대 점수`가 존재한다. 이 점수를 명시해줘야할 것 같은데, 각 평가마다 어떻게 부여할까?  지금 떠오르는 방식은 `평가1 (최대점수)` 의 형식으로 표의 헤더에 입력해주는 방법만 생각남. 🤔
- 평가결과 `PENDING` 의 기준을 어떻게 정의할 것인가 ?
- 평가 상태를 업데이트하려면 `모든 평가 대상자의 평가 점수 합계`가 있어야한다.
    - 즉, 평가자들을 순회하면서 평가자의 **점수 합계부터 먼저 계산**해야한다.
    - 그 이후 점수 합계를 기준으로 내림차순으로 정렬하여 평가 상태(PASS, FAIL, FENDING)를 변경해야한다.
    - 더 개선할 수 있는 방법은 없을까?
- 잘못된 평가 결과를 업로드할 수도 있는데, 이 경우 어떻게 할 것인가?
    - `다른 모집` 혹은 `다른 평가`에 대한 평가 결과지를 업로드하는 경우가 발생할 수 있다.
    - `평가 결과를 잘못 업로드한 경우에 발생하는 문제를 방지할 방법`에 대해 고민해봐야할 것 같다.
- 여러 업데이트를 동시에 해야하기 때문에 단순히 매번 쿼리 업데이트를 하는 것 보다 bulk update를 하는 방법을 찾아보는게 좋지 않을까? (그정도까지 대규모 데이터는 아니라서 당장 고민할 필요는 없어보인다)

### JPA Bulk Update 참고자료

- [https://www.baeldung.com/jpa-hibernate-batch-insert-update#batch-update](https://www.baeldung.com/jpa-hibernate-batch-insert-update#batch-update)
- [https://bottom-to-top.tistory.com/51](https://bottom-to-top.tistory.com/51)
- [https://cheese10yun.github.io/jpa-bulk/](https://cheese10yun.github.io/jpa-bulk/)

**Comment by Rok93** [comment]
# 개발 이슈 정리
## FE 
### 관리자 페이지 `선발 과정` 탭에 신규 버튼을 구현한다. 
* `평가지 다운로드` 버튼
	* 해당 평가의 평가 대상자들을 기준으로 `평가지` (CSV 파일 예정) 다운받는 기능
* `평가지 업로드` 버튼 
	* 다운받은 평가지를 작성하여, 업로드하는 버튼 
	* 업로드하면, 업로드 된 CSV 파일 내용을 반영하여, DB를 업데이트한다.

## BE 
> 평가지는 CSV 확장자 파일로 정했습니다. 
> XLSX 형식이 아닌 CSV 형식을 사용한 이유는 [CSV와 XLS(Excel)의 차이점](https://she11.tistory.com/61) 을 참고해보시면 좋을 것 같습니다. 
> 
> 총 세가지 작업 이슈로 구분했는데, 이 세 작업을 동시에 진행한다면,  작업이전에 긴밀한 협의가 필요해보입니다. 혹은 `평가지를 다운로드 기능` 을 첫 작업으로 진행하여 `평가지 양식`을 우선적으로 fix한 이후에 fix된 평가지 양식을 기준으로 다른 작업 이슈들도 진행하면 좋을 것 같습니다. 

### 1. 평가지를 다운로드 기능을 구현한다. 
* 파일 형식은 CSV로 한다. 
* 평가지 업로드와 동일하게 아래의 정보를 포함한다. 
	* 지원자 식별 정보(applicantId, 지원자 이름, 지원자 이메일)
	* 각 평가에 대한 점수 (최대 점수) 
		* 각 평가마다 최대 점수가 다르다. 
		* 따라서 최대 점수는 `()` 안에 표기한다. 
		* 더 좋은 방식이 있다면, 변경해도 무방하다. 
	* 평가상태
		* 평가상태는 총 3가지 `PENDING`, `PASS`, `FAIL` 이 존재한다. 
		* PENDING은 크게 고려하지 않아도 된다. 
		* 다음 `평가자 불러오기` 버튼을 누를 때에는 이전 평가자들 중 평가 상태가 PENDING인 평가자가 없다고 가정한다. 
		* 평가 상태는 관리자 페이지에서 수동으로 관리가 가능하나 평가지 업로드를 통해서도 수정이 가능하도록 구현한다. 

### 2. 평가지 업로드 기능을 구현한다. 
* 평가지에는 아래의 정보를 포함한다. 
	* applicantId(지원자 식별번호), 
	* 지원자 이름
	* 지원자 이메일
	* 각 평가에 대한 점수 (최대 점수) 
		* 각 평가마다 최대 점수가 다르다. 
		* 따라서 최대 점수는 `()` 안에 표기한다. 
		* 더 좋은 방식이 있다면, 변경해도 무방하다. 
	* 평가상태
		* 평가상태는 총 3가지 `PENDING`, `PASS`, `FAIL` 이 존재한다. 
		* PENDING은 크게 고려하지 않아도 된다. 
		* 다음 `평가자 불러오기` 버튼을 누를 때에는 이전 평가자들 중 평가 상태가 PENDING인 평가자가 없다고 가정한다. 

### 3.  평가지를 기준으로 평가대상자들 상태 업데이트 기능을 구현한다.
* 평가지 업로드 기능 구현을 작업하는 작업자와 소통하여 `평가지 양식`을 먼저 정한다. 
* 다수의 평가 대상자들의 상태를 업데이트해야하기 때문에 `vulk update`방식을 고려한다.
	* 해당 이슈 상단의 참고자료들을 참고

**Comment by knae11** [comment]
# 작은 질문
작은 질문 하나 남겨요~ 👍 
## 1
- 실제로 ui 로는 읽기만 하고 파일을 다운받기, 업로드하기를 통해서 해당 내용이 저장, 갱신 되는 부분인가요?
- 혹시 이렇게 한다면, csv 파일을 기존 항목과 벗어나게 하거나 지원자를 csv 파일에서 임의로 추가하면 반영이 어떻게 되는지 조금 궁금합니다 😄

**Comment by Rok93** [comment]
@knae11 

질문에 대해 각각 답변 남길게요! 

Q1. 실제로 ui 로는 읽기만 하고 파일을 다운받기를 통해서 내용을 수정하여, 파일을 업로드 하면 DB에 저장, 갱신 되는 부분인가요?
A1. UI(아마도 관리자 페이지에 `선발 과정` 화면으로 추정되는 것...?)로 읽기만 하는 것은 아닙니다.  지금 현재도 해당 탭에서 부정행위자 칸을 변경할 수 있다고 합니다. 추측컨데, 평가 상태도 변경이 가능할 것이라 생각됩니다. 

파일 업로드 방식은 `일괄적으로 평가`를 업데이트하기 위한 수단입니다. 페이지의 갱신을 말씀하시는 거라면, DB에 반영한 이후, `선발 과정`화면으로 redirect(혹은 새로고침)를 하는 방법으로 대체가 가능하지 않을까요? 바딘의 몇몇 화면이 DB에 CRUD 작업을 한 뒤, redirect를 했던 기억이 어렴풋이 있습니다🤔 

(제가 로컬에서 지원이 잘 안돼서 테스트를 제대로 못해본터라... 부정행위 여부 변경은 가능하다고 얘기를 들었는데, 평가 상태는 오로지 추측입니다)

Q2. 혹시 이렇게 한다면, csv 파일을 기존 항목과 벗어나게 하거나 지원자를 csv 파일에서 임의로 추가하면 반영이 어떻게 되는지 조금 궁금합니다 😄

A2. 먼저 이 부분은 크게 고민해보지는 않은 내용이에요. 왜냐하면 해당 기능은 관리자페이지에서 `관리자`가 작업을 진행하기 때문에, 악의적인(?) 행동을 하리라고 생각되지는 않아요. 😅 혹은 굳이 평가지 양식을 변경한다거나 하지도 않을 것 같아요. 

### 기존 항목과 벗어나게 하는 경우 
평가항목이 다른 경우에는, `반영이 안되게하는 것`이 좋을 것 같습니다.  약간 엄격한 기준이라고 생각할 수 있겠지만 너무 여러가지 상황들이 존재할 것이라 생각해요. (ex. 항목이 다르다거나 항목의 내용이 다르다거나, 항목의 최대 점수가 다르다거나 등등...) 

### 지원자를 CSV 파일에서 임의로 추가하는 경우
평가 대상자들 정보가 존재하기 때문에, 이 정보와 CSV파일의 지원자가 일치하는지 먼저 파악하고, 기존 평가 대상자에 포함되지 않는 지원자라면 업데이트하지 않습니다.

**Comment by Sehwan-Jang** [comment]
정책 정하시느라 수고하셨어요~~ 궁금한점 몇가지 남길게요 🙂

### Q1
제가 잘 이해를 못하고 있는 건지 모르겠는데, `2. 평가지 업로드 기능을 구현한다.` 의 이슈가 잘 와닿지 않아요 ㅠㅠ 파일 업로드를 위한 UI를 구현하는 것이라면 4번 이슈와 겹치는 것 같고, 업로드된 파일을 가지고 백서버로 가져오는 것이라면 3번 이슈와 겹치는 것 같다는 생각이 들었어요. 혹시 이에 대해 어떤 작업을 구상하고 계셨는지 조금 더 설명 부탁드려도 될까요?
<br>

### Q2
최대점수는 파일안에 표시되어서 다운로드 되는 것인가요? 아니면 다운로드 받은 후 직접 넣어줘야하는 것일까요?

**Comment by Rok93** [comment]
@Sehwan-Jang  

### Q1
제가 잘 이해를 못하고 있는 건지 모르겠는데, `2. 평가지 업로드 기능을 구현한다.` 의 이슈가 잘 와닿지 않아요 ㅠㅠ 파일 업로드를 위한 UI를 구현하는 것이라면 4번 이슈와 겹치는 것 같고, 업로드된 파일을 가지고 백서버로 가져오는 것이라면 3번 이슈와 겹치는 것 같다는 생각이 들었어요. 혹시 이에 대해 어떤 작업을 구상하고 계셨는지 조금 더 설명 부탁드려도 될까요?
<br>

>  `평가지 업로드 기능을 구현한다`는 정말로 단순히 CSV 파일을 업로드하여 CSV 파일의 내부 정보들을 읽을 수 있는 기능을 만드는 것입니다. 
아론 말처럼 3번 혹은 4번과 겹친다고 생각할 수 있을 것 같은데, 정확히는 3번과 겹친다고 생각할 수 있을 것 같아요! (4번은 바딘을 이용하여 뷰를 변경해야하기 때문에 별개의 것이라 생각해요!) 

A1. 사실 2번(평가지 업로드 기능을 구현한다)과 3번(평가지를 기준으로 평가대상자들 상태 업데이트 기능을 구현한다)을 하나의 작업으로 뭉치는 것이 직관적으로 이해가 잘된다고 생각해요...하지만 `3번의 작업`이 고려해야할 점도 많고 제 생각에는 조금 어려운 작업이라고 생각했어요. 그래서 최대한 2번, 3번으로 분리를 해서 `업로드한 CSV 파일의 내용을 조회할 수 있게 만드는 작업`과 업로드 된 `평가지 파일의 내용에 따라 평가자들의 상태를 업데이트하는 작업`을 분리하고자 했어요. 

### Q2
최대점수는 파일안에 표시되어서 다운로드 되는 것인가요? 아니면 다운로드 받은 후 직접 넣어줘야하는 것일까요?

A2. 전자로 진행이 돼야할 것 같습니다! (이미 각 항목에 대한 `최대 점수`가 지정되어있기 때문에 그리 어렵지 않을 것이라 생각됩니다) 
단지 평가지 내용대로 평가자들을 업데이트해야하는 작업 담당자들이 이 값을 어떻게 읽어야하는지 조금 고민해야할 부분이 생길 것 같아요  😅 
(ex. 최대 점수보다 높은 점수가 기재되어 있으면 어떻게 할 것인지? etc...)

**Comment by MyaGya** [comment]
다른 분들이 많이 질문을 올려주셔서 질문 한 가지만 추가로 남기겠습니다.

Q1. `PENDING` 이 정확히 어떤상태인가요?

**Comment by Rok93** [comment]
@MyaGya  

Q1. PENDING 이 정확히 어떤상태인가요?

A1. 저도 이 `PENDING` 상태에 대해서 명확하게 정의내리기는 어렵지만, PASS, FAIL인지 보류상태라고 보시면 될 것 같아요. 
당장 PASS 혹은 FAIL로 정하기 힘든 경우, PENDING을 부여하고 추후 PASS 혹은 FAIL로 최종 확정을 짓습니다. 
이전평가에서 `평가자 불러오기`버튼을 누르는 시점에는  PENDING이 없다고 생각하시면됩니다.  
답변이 됐을까요? 🤔

**Comment by NewWisdom** [comment]
정책 정하시느라 정말 수고 많으셨습니다 👏 정리하신 내용과 코멘트 잘 읽어보았습니다! ㅎㅎ
추가로 궁금하거나, 반영하면 좋을 것 같은 부분 남기겠슴다:)

### 1.
사소한 부분인 것 같긴 하지만, 새로 `평가지 다운로드`버튼이 구현된다면 기존에 있던 `다운로드`버튼은 어떤 기능을 하는건지 인식하기 어려울 수도 있겠다는 생각이 들어요. 기존 `다운로드`버튼이 평가 결과 엑셀을 다운로드하는 방식이라면, 텍스트를 `평가결과 다운로드`로 바꾸는 것도 이슈에 명시하면 어떨까요?


### 2.
위에 코멘트에서도 많이 언급되었지만 다운로드 받은 평가지에서 실수로 지원자의 변경되지 말아야 할 정보(id, email 등)가 변경되는 이슈가 있을 수 있고 이에 대한 검증을 꽤 필요할 것이라는 생각이 드네요! 그러다 든 생각인데 평가지 폼을 미리 만들고 저장해두는 것이라면, 엑셀에서는 이에 대해 컬럼 수정 제한 등 다양한 기능으로 이를 막을 수 있을 것 같기도 해서 엑셀 형식을 사용해도 괜찮을 것 같다.?라는 생각이 들기도 하네요. 현재 다운로드 기능도 엑셀 형식이기도 하구요. 하지만 사실 저도 엑셀을 스프링에서 다루는 법이나 엑셀의 기능들을 자세히 알지는 못하는 것 같아 확신해 말할수가 없네요 ㅎㅎ ㅠ 평가지 수정 이슈에 대한 해결책을 생각해보다 떠오른거라서... 이 부분은 진짜 고냥 스루해버리셔도 됩니다!!!

### 3. 
평가지를 손수 작성하기에, 추후에 평가지 업로드 시 `존재하지 않는 평가 상태 입력, 지원자 정보 변경, 평가 항목이 달라 평가자 정보가 업데이트 되지 않는 이슈` 등의 예외 사항들이 여러 부분에서 잡힐 것 같네용. 이럴 때 복합적인 예외상황들을 어떻게 알려주느냐도 고민해보아야 할 것 같지만 지금 단계에서 정의하기 어려운 부분일 것 같아 일단 코멘트만 남겨놓겠습니다!

**Comment by ecsimsw** [comment]
고생 많으셨습니다!!!! 저는 이렇게 꼼꼼히 못 생각했을 것 같아요...
제가 작업한다면~을 가정하고 머릿 속에서 모호한 부분을 질문드리겠습니다. 짜주신 정책에 대한 의의가 아님을 알아주시길. 

1. 이전 평가 불러오기와 추후 평가 상태를 확정 짓는 시점을 잘모르겠습니다., 이 부분 조금만 더 설명 부탁드려도 될까요? 
 
특히 PENDING을 부여한 평가자는 어디서 평가를 결정하는지(관리자 페이지에서만 관리되는 것을 의도하시는 건지), '이전 평가'는 평가 상태 결정이 모두 마친 상태인지 궁금합니다. 

혹시 설명이 번거로우시면 제가 찾아볼 수 있는 키워드만 주시면 공부해오겠습니다.

> 당장 PASS 혹은 FAIL로 정하기 힘든 경우, PENDING을 부여하고 추후 PASS 혹은 FAIL로 최종 확정을 짓습니다. 이전 평가에서 평가자 불러오기버튼을 누르는 시점에는 PENDING이 없다고 생각하시면됩니다.

2. 다른 팀원들에서 얘기가 나온 것처럼, 평가지 업로드시의 예외 처리 걱정, 문제 사항은 이미 로키도, 다른 팀원들도 생각하고 계시는 부분이라고 생각합니다. 

저는 특히 위험할 것 같다고 생각하는 포인트가 벌크 업데이트인데요, 아직 평가되지 않은 부분에 대한 업데이트는 벌크 업데이트 편하지만서도, 이미 평가된 정보에 대한 수정, 삭제 실수가 발생할 수 도 있을 거라고 생각했습니다. 

혹시 기존에 있는 데이터까지 벌크로 전체 수정하는 요청과, 그렇지 않고 아직 평가되지 않은 평가만을 다루는 업로드 요청을 나누는 것은 어떻게 생각하시나요? 이를 테면 평가지 업로드 버튼 입력 시, [새로운 항목에 대해서만 적용 / 기존 항목까지 전체 적용]을 만드는 것은 오버일까요. 

다른 것보다 걱정되는 부분인데도, 저도 특별한 예쁜 대안이 생각이 않나 이렇게라도 제안해봅니다. 

추가로) 이런 평가지로 관리되는 지원자 수가 어느정도 되는지 혹시 아시나요? 그 수에 따라서 대응 방식을 좀 달리 고민할 수 있을 것 같아서요. 

생각보다 적은 수라 실수에 대한 걱정이나, 후처리가 적은 상황인지, 또는 생각했던 것보다도 많아서 실수하기 좋고, 한번 실수가 나오면 후처리가 심각한 상황인지 

저도 한번 고민해보고 다시 대안을 생각해보고 싶어 여쭤봅니다.

**Comment by Rok93** [comment]
@NewWisdom 

답변이 늦었습니다. 🙏

1. 사소한 부분인 것 같긴 하지만, 새로 평가지 다운로드버튼이 구현된다면 기존에 있던 다운로드버튼은 어떤 기능을 하는건지 인식하기 어려울 수도 있겠다는 생각이 들어요. 기존 다운로드버튼이 평가 결과 엑셀을 다운로드하는 방식이라면, 텍스트를 평가결과 다운로드로 바꾸는 것도 이슈에 명시하면 어떨까요?

> 이 부분은 생각하지 못했는데, 아마찌 말대로, 그냥 `다운로드`라는 의미가 헷갈릴 수 있을 것 같네요. 이 부분은 `평가결과 다운로드`로 변경하도록 이슈에 명시하도록 하겠습니다. 👍

2.
위에 코멘트에서도 많이 언급되었지만 다운로드 받은 평가지에서 실수로 지원자의 변경되지 말아야 할 정보(id, email 등)가 변경되는 이슈가 있을 수 있고 이에 대한 검증을 꽤 필요할 것이라는 생각이 드네요! 그러다 든 생각인데 평가지 폼을 미리 만들고 저장해두는 것이라면, 엑셀에서는 이에 대해 컬럼 수정 제한 등 다양한 기능으로 이를 막을 수 있을 것 같기도 해서 엑셀 형식을 사용해도 괜찮을 것 같다.?라는 생각이 들기도 하네요. 현재 다운로드 기능도 엑셀 형식이기도 하구요. 하지만 사실 저도 엑셀을 스프링에서 다루는 법이나 엑셀의 기능들을 자세히 알지는 못하는 것 같아 확신해 말할수가 없네요 ㅎㅎ ㅠ 평가지 수정 이슈에 대한 해결책을 생각해보다 떠오른거라서... 이 부분은 진짜 고냥 스루해버리셔도 됩니다!!!

> 저도 컬럼 수정 제한 등 다양한 기능으로 막는 방식도 있지 않을까 싶었는데, 이 부분은 제가 알아보지 않아서 잘 모르겠네요 😅 
2번(`평가지 업로드 기능을 구현한다`)과 3번(`평가지를 기준으로 평가대상자들 상태 업데이트 기능을 구현한다`)의 이슈를 따로 구분한 이유가 정확히는 3번 이슈의 경우 CSV 파일의 반영은 물론 검증도 고민을 해야하기 때문에 고민해야 할 요소가 많다고 생각했습니다. 따라서 작업 이슈를 조금 더 분리하게 됐습니다. 여기에 관련된 기능을 직접 구현해보지 않고서는 판단이 잘 안될 것 같네요 😅. 그래서 이 부분은 해당 이슈를 맡을 분들에게 위임하려고 해요.... 🙏
아마찌가 말해준 부분과 더불어서 업로드하는 파일을 완전 별개의 CSV 파일을 업로드하는 것은 어떻게 막을지.. (아예 양식이 다르다면 금방 파악할 수 있겠지만, 만약 양식을 비슷하게 만들었다면...?) 
하지만 이 부분에 대해서는 크게 고민을 하지 않아도 된다고 생각하는게, 평가자들은 코치분들 및 포비가 되실 것 같습니다. 이런 부정사례(?)에 대해 고민할 필요가 없지 않을까요? 


3.
평가지를 손수 작성하기에, 추후에 평가지 업로드 시 존재하지 않는 평가 상태 입력, 지원자 정보 변경, 평가 항목이 달라 평가자 정보가 업데이트 되지 않는 이슈 등의 예외 사항들이 여러 부분에서 잡힐 것 같네용. 이럴 때 복합적인 예외상황들을 어떻게 알려주느냐도 고민해보아야 할 것 같지만 지금 단계에서 정의하기 어려운 부분일 것 같아 일단 코멘트만 남겨놓겠습니다!

> 최대한 작성된 부분만 반영을 하게 하면 큰 문제가 없으리라 생각했는데, 제가 생각한 방식대로라면 문제가 될 요소도 있겠네요. 

이 부분도 위와 동일하게 평가자가 가이드대로 제대로 평가를 할 것이라 가정하고 우선적으로 기능을 완성하고 추후 예외처리 등을 고려하면서 견고하게 개선하는 방식으로 진행해야 할 것 같네요 🥲

**Comment by Rok93** [comment]
1. 이전 평가 불러오기와 추후 평가 상태를 확정 짓는 시점을 잘모르겠습니다., 이 부분 조금만 더 설명 부탁드려도 될까요?
특히 PENDING을 부여한 평가자는 어디서 평가를 결정하는지(관리자 페이지에서만 관리되는 것을 의도하시는 건지), '이전 평가'는 평가 상태 결정이 모두 마친 상태인지 궁금합니다.

혹시 설명이 번거로우시면 제가 찾아볼 수 있는 키워드만 주시면 공부해오겠습니다.

> 당장 PASS 혹은 FAIL로 정하기 힘든 경우, PENDING을 부여하고 추후 PASS 혹은 FAIL로 최종 확정을 짓습니다. 이전 평가에서 평가자 불러오기버튼을 누르는 시점에는 PENDING이 없다고 생각하시면됩니다.

### A1. 
> 예를들어 저희 우테코 3기 기수들이 선발되는 과정을 예로들어보면, 프리코스 `숫자야구`, `로또`, `지하철노선도` 미션을 예로 들어보겠습니다. 
먼저 `이전 평가 불러오기`를 하는 시점은 첫 번째 미션인 `숫자야구` 미션 제출 마감일 이후, 다음 로또 미션이 시작하기 전까지 모든 평가가 완료된 상태에서 진행됩니다. 즉, PENDING의 경우가 없이, `PASS`, `FAIL`의 경우만 존재하게 됩니다. 숫자야구 미션에서 `PASS`를 받은 평가자들은 다음 평가(= `로또 미션`)의 대상자가 됩니다. 이 때, `평가자 불러오기` 버튼으로 해당 평가의 평가자들을 불러오게 됩니다. (이렇게 작성을 하고 보니, 평가자를 가져오는 시점이 조금 애매하기는 하네요 😅, 일단은 이상적으로는 다음 미션인 로또 미션이 시작되기 전까지는 완료가 되야할 것 같습니다. (지금 이야기하는 것과는 관계가 없기는 하지만 추후 다음 평가 대상자들에게 다음 미션에 대한 안내 메일을 일괄적으로 발송하는 기능을 추가한다면 좋을 것 같네요 😃)
PENDING은 평가자들만 알고있는 내용이기 때문에 당연하게도 관리자페이지에서만 (임시적으로) 관리되는 상태입니다. 또한 이 평가 상태는 지금도 관리자페이지에서 수정이 가능합니다. (시나리오를 가정해보면... 결과지를 업데이트하여 일괄적으로 평가 상태를 업데이트하고 추후 PENDING된 평가자들을 PASS 혹은 FAIL로 결정하게 될 것 같습니다. )결과적으로 추후에 남게 되는 상태는  `PASS`, `FAIL` 이 두가지만 존재한다고 생각하시면 됩니다. (PENDING 때문에 이해가 어렵다면 아예 없다고 생각을 하셔도 크게 문제될 것 같지는 않습니다) 



2. 다른 팀원들에서 얘기가 나온 것처럼, 평가지 업로드시의 예외 처리 걱정, 문제 사항은 이미 로키도, 다른 팀원들도 생각하고 계시는 부분이라고 생각합니다.
저는 특히 위험할 것 같다고 생각하는 포인트가 벌크 업데이트인데요, 아직 평가되지 않은 부분에 대한 업데이트는 벌크 업데이트 편하지만서도, 이미 평가된 정보에 대한 수정, 삭제 실수가 발생할 수 도 있을 거라고 생각했습니다. (필수적인 것을 이해하면서도, 무서움..?)

혹시 기존에 있는 데이터까지 벌크로 전체 수정하는 요청과, 그렇지 않고 아직 평가되지 않은 평가만을 다루는 업로드 요청을 나누는 것은 어떻게 생각하시나요? 이를 테면 평가지 업로드 버튼 입력 시, [새로운 항목에 대해서만 적용 / 기존 항목까지 전체 적용]을 만드는 것은 오버일까요. 이렇게 나뉜다면 평가자 작업자가 기존 항목 수정에 대한 위험을 덜 느끼면서 새로운 항목 평가를 작성할 수 있지 않을까 싶었습니다.

걱정이 되면서도, 저도 특별한 예쁜 대안이 생각이 않나 이렇게 부족하게라도 제안해봅니다.

> 당연하게도 위험을 방지할 수 있다면 도입하고 싶은 마음이 굴뚝같지만 그렇다면 이 이슈를 담당하는 사람들에게 너무 가혹한(?) 업무 부담이 될 것 같아요 😂 .... 아직 직접 작업을 해본 상황이 아니라서 그 방식이 접목하기 쉬울지 어려울지 감이 잘 안잡히네요 🤔 개인적인 생각으로는 처음부터 모든 예외사항을 다 잡게다는 생각으로 진행하는 것 보다는, 우선 동작하는 코드를 일차적으로 만들고 추후 더 견고하게 리팩토링하는 것이 더 좋은 방법일 것 같아요 😃


추가로) 이런 평가지로 관리되는 지원자 수가 어느정도 되는지 혹시 아시나요? 그 수에 따라서 대응 방식을 좀 달리 고민할 수 있을 것 같아서요.

생각보다 적은 수라 실수에 대한 걱정을 덜해도 되는 상황인지, 반대로 생각했던 것보다도 많아서 실수하기 좋고, 한번 실수가 나오면 후처리가 심각한 상황인지

> 이 부분은 제가 직접들은 이야기는 아니지만, 저희가 프리코스를 진행할 때, PR 갯수를 세어보면 백엔드 기준으로 경쟁률이 약 2:1 이었습니다. 즉, 약 100명 정도의 평가 대상자가 존재했다고 추측됩니다. 😃  (이런 코멘트를 달아도 될지 모르겠네요 😅)
