### ISSUE TITLE
부정행위자 입력 폼을 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#296]
- '추가' 버튼을 눌렀을 때 입력 폼을 띄울 수 있어야한다.
- 새로운 부정행위자 입력 폼을 구현한다.
    - 기존 부정행위자 화면에 있던 input box, 검색 버튼, 셀렉트 박스는 새로운 입력 폼으로 옮긴다.
        - input box
        - 검색 버튼
        - 지원자 선택 셀렉트박스
        - 부정행위자 설명을 입력하는 텍스트 박스
        - 저장, 취소
- 예시

![image](https://user-images.githubusercontent.com/43840561/128741452-6c565f6a-8b71-4c23-9d6b-0b013f1d5d0e.png)

### ➕ 기존의 부정행위자 등록 흐름

![image](https://user-images.githubusercontent.com/43840561/128741495-135aca08-cf79-4fd1-bb1e-25c691721cc1.png)

1. input box에 키워드(이름/이메일)를 입력한다.
2. 검색 버튼을 누른다.
3. 키워드로 조회된 지원자를 셀렉트 박스에서 선택하고 '추가' 버튼을 눌러 부정행위자로 등록한다.

관련 이슈: #274

**Comment by Sehwan-Jang** [comment]
## FormLayout

- [공식 문서](https://vaadin.com/components/vaadin-form-layout/java-examples)
- addFromItem() 대신 add()를 사용한다.
    - [관련 이슈](https://github.com/woowacourse/service-apply/issues/13)

    > FormLayout은 컴포넌트를 추가하는 방법으로 add()와 addFormItem()를 제공한다. 그러나 vaadin-form-item은 화면에 몇 가지 문제가 있다. 따라서 add()를 사용한다.

## BindingFormLayout

- **BindingFormLayout** : (Form의 Component 필드들 ↔  Data 클래스의 필드들 ) 끼리의 전환, 바인딩을 하기위한 클래스

    ```jsx
    Class EvaluationTargetForm() : BindingFormLayout<EvaluationTargetData>(EvaluationTargetData::class) {
        private val evaluationItemScores: MutableList<EvaluationItemScoreForm> = mutableListOf()
        private val note TextArea = TextArea("기타 특이사항")
        private val evaluationStatus: Select<EvaluationStatus> = createItemSelect<EvaluationStatus>("평가 상태").apply {
            setItems(*EvaluationStatus.values())
            setItemLabelGenerator { it.toText() }
        }
    ...
    ```

    ```jsx
    data class EvaluationTargetData(
        @field:NotNull
        @field:Valid
        var **evaluationItemScores**: List<EvaluationItemScoreData> = emptyList(),

        @field:Size(max = 255)
        var **note**: String = "",

        @field:NotNull
        var **evaluationStatus**: EvaluationStatus = EvaluationStatus.WAITING
    )
    ```

- 규칙
    - 각 필드들의 이름은 서로 같아야 한다.
    - (특히) boolean 타입의 필드의 경우 `isHidden` 의 형식이 아닌 `hidden` 과 같이 네이밍 해야 바인딩이 동작 한다
        - [관련 이슈](https://github.com/woowacourse/service-apply/issues/64#issuecomment-699655940)
    - 바인딩하고자 하는 DATA 클래스는 자바빈즈 규약을 따라야 함 (`BeanValidationBinder`)
        - 기본 생성자 포함, getter setter 접근 가능 등등
        - [자바빈즈](https://ko.wikipedia.org/wiki/%EC%9E%90%EB%B0%94%EB%B9%88%EC%A6%88), [관련 이슈](https://github.com/woowacourse/service-apply/pull/84/files)
    - 기본 생성자를 통해 인스턴스 생성 후 추후에 각 필드들을 바인딩하는 방식
        - 따라서 Data Dto들은 `var` 타입으로 지정해야 추후에 바인딩이 정상적으로 동작한다.
    - Data 클래스의 `@field:`  어노테이션으로 폼 입력값 검증을 할 수 있다.
        
       ![image](https://user-images.githubusercontent.com/68985748/133263297-784a4750-7347-4415-b5e7-c3445134c70e.png)
      ```jsx
       data class EvaluationData(
          @field:NotBlank
          @field:Size(min = 1, max = 31)
          var title: String = "",

          @field:NotBlank
          var description: String = "",

          @field:NotNull
          var recruitment: RecruitmentSelectData = RecruitmentSelectData(),

          var beforeEvaluation: EvaluationSelectData = EvaluationSelectData(),

          @field:NotNull
          @field:Valid
          var evaluationItems: List<EvaluationItemData> = emptyList(),
          var id: Long = 0L
      )
       ```
- override methods
    - `fill(data: DATA)` : 폼의
        - 기본 : `fillDefault(data: DATA)`
        - 폼 양식에 추가적으로 기입할 데이터가 있다면 채우도록 구현.
            - 특히 DATA 클래스 안에 DATA 클래스가 있는 경우

                ```jsx
                data class RecruitmentData(
                    @field:NotBlank
                    @field:Size(min = 1, max = 31)
                    var title: String = "",

                    ...

                    @field:NotNull
                    @field:Valid
                    var recruitmentItems: List<RecruitmentItemData> = emptyList(),
                    var id: Long = 0L
                )
                ```

                ```jsx
                class RecruitmentForm() : BindingIdentityFormLayout<RecruitmentData>(RecruitmentData::class) 
                {
                	...
                		private val recruitmentItems: MutableList<RecruitmentItemForm> = mutableListOf()
                			...
                		
                		override fun fill(data: RecruitmentData) {
                		      fillDefault(data)
                		      term.isReadOnly = true
                		      data.recruitmentItems.forEach { addRecruitmentItemForm(it) }
                		}
                ```

    - `bindOrNull()` : 폼의 필드들을 DATA 객체로 바인딩하여 반환 (필요한 필드가 없는 등의 문제 발생 시 null)
        - 기본 : `bindDefaultOrNull()`
        - 기본 바인딩만으로는 부족하거나, 추가적인 작업을 해야한다면 구현.
