### ISSUE TITLE
부정행위자 조회 테이블을 수정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#297]
- 부정행위자 설명도 조회할 수 있도록 수정한다.
   - 각각의 부정행위자 row에서 `삭제` 버튼 옆에 `상세 내용 조회` 버튼을 구현한다.
      - 버튼을 누르면 부정행위자 설명(description) 모달을 띄우도록 구현한다.

### ➕ 기존의 부정 행위자 조회 화면

![https://user-images.githubusercontent.com/43840561/128705726-84316639-0e09-49f6-bbf0-c09034e13ab9.png](https://user-images.githubusercontent.com/43840561/128705726-84316639-0e09-49f6-bbf0-c09034e13ab9.png)

관련 이슈: #274

**Comment by ecsimsw** [comment]
작업 명세 변경 사항
1. `부정행위자 설명(description) 모달을 띄우도록 구현`에서 삭제 버튼 옆에 설명을 표시하는 컬럼을 추가하는 것으로 변경한다.
    - 설명이 긴 경우 표에 어떻게 표시되는지 확인할 필요가 있다.
2. 부정행위자 표 내부에 행위자 이름을 출력하는 방법을 변경한다.
    - 현재 사용자 정보가 남아있는 경우에는 이름을 출력하고, 남아있지 않은 과거의 부정행위자의 경우 `(이름 없음)`으로 표시한다.
