### ISSUE TITLE
아주 간단한 클래스 다이어그램을 그려 본다. - 8월 26일(수)

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#3]
아래 내용을 참고하여 아주 간단한 클래스 다이어그램을 그려 본다.

### 지원자

- 지원하기
   - 개인정보 수집 및 이용 동의
   - 개인정보
      - 이름, 이메일, 연락처, 성별, 생년월일
   - 항목
      - 파일 첨부
   - 지원서 작성 내용 사실 확인
   - 임시 저장
   - 자동 저장
- 나의 지원서
   - 지원서 수정 및 결과 확인
   - 이메일 찾기
   - 비밀번호 찾기
   - 조회 결과

### 관리자

- 부정 행위자
- 지원 관리
   - 지원 만들기
- 평가 관리
   - 평가 만들기
   - 이전 평가 연결하기
- 선발 과정
   - 전체 지원자
      - 엑셀 다운로드
   - 이전 평가 합격자 불러오기
- 메일 발송

### 참고

- [UML: 클래스 다이어그램과 소스코드 매핑](http://www.nextree.co.kr/p6753)
- [[UML] 클래스 다이어그램 작성법](https://gmlwjd9405.github.io/2018/07/04/class-diagram.html)

**Comment by LTTTTTE** [comment]
![image](https://user-images.githubusercontent.com/7259103/91302988-4b4a3100-e7e2-11ea-8e23-6f3f461259ef.png)

**Comment by lalize** [comment]
<img width="814" alt="스크린샷 2020-08-26 오후 9 27 33" src="https://user-images.githubusercontent.com/58076838/91303514-19859a00-e7e3-11ea-8df3-e205f0802222.png">

**Comment by hotheadfactory** [comment]
<img width="937" alt="스크린샷 2020-08-26 오후 4 11 19" src="https://user-images.githubusercontent.com/13493184/91309308-63727e00-e7eb-11ea-9ee7-3d981d49a086.png">

**Comment by lowoon** [comment]
![Apply](https://user-images.githubusercontent.com/45028630/91310530-f364f780-e7ec-11ea-812d-589b1c1d3767.png)

**Comment by toneyparky** [comment]
<img width="1304" alt="Screen Shot 2020-08-26 at 22 10 59" src="https://user-images.githubusercontent.com/37579660/91307578-1b525c00-e7e9-11ea-8dd7-0d4db8dcf0ee.png">

평가 대상자, 지원 항목, 관리자에 대해서는 조금 더 논의가 필요할 듯 합니다.

굳나잇!

**Comment by woowahan-pjs** [comment]
# Recruitment

![recruitment](https://user-images.githubusercontent.com/48229284/91674231-d9237480-eb72-11ea-8153-3a1cfce25302.png)

```uml
@startuml
class Applicant {
  id
  name
  email
  phoneNumber
  gender
  birthday
}

class Application {
  id
  submitted
  createdDateTime
  submittedDateTime
  modifiedDateTime
}

enum Result {
  UNDER_REVIEW
  ONLINE_TEST
  PRECOURSE
  FINAL_TEST
  PASS
  FAIL
}

class Recruitment {
  id
  title
  canRecruit
  startDateTime
  endDateTime
}

class RecruitmentItem {
  id
  title
  description
  order
}

class Answer {
  contents
}

class Cheater

Applicant <-- "*" Application : applicant
Application --> Recruitment : recruitment
Applicant <-- Cheater : applicant
Recruitment <-- "*" RecruitmentItem : recruitment
Application --> "*" Answer : answers
Application --> Result : result
Answer "*" --> RecruitmentItem : recruitment item
@enduml
```

# Evaluation

![evaluation](https://user-images.githubusercontent.com/48229284/91674152-7500b080-eb72-11ea-98bd-d0558b71b786.png)

```uml
@startuml
class Administrator {
  id
}

class Evaluation {
  id
  title
  description
}

class EvaluationItem {
  id
  title
  description
  maximumScore
  order
}

class Target {
  id
  note
}

enum EvaluationStatus {
  WAITING
  PENDING
  PASS
  FAIL
}

class Answer {
  score
}

class Recruitment

class Applicant

Evaluation "*" --> Recruitment : recruitment
Evaluation -- Evaluation : before evaluation
EvaluationItem "*" --> Evaluation : evaluation
Target "*" --> Evaluation : evaluation
Target --> Applicant : applicant
Target --> EvaluationStatus: evaluation status
Answer "*" <-- Target : answers
Answer --> EvaluationItem : evaluation item
Target "*" --> Administrator : evaluator
@enduml
```
