### ISSUE TITLE
부정행위자 조회 기능을 수정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#300]
- 부정행위자(Cheater) 목록 중 현재 존재하는 지원자(Applicant)에 대해서만 목록을 응답한다.
- 부정행위자 조회 API인 [GET] "/api/cheaters" 변동사항 없음
- `cheaterService.findAll()` 를 수정한다.
    - email을 통해 applicant를 조회하도록 수정한다.
- CheaterResponse에 description(부정행위자 설명) 필드를 추가한다.

관련 이슈: #274

**Comment by ecsimsw** [comment]
이 이슈 다 구현되어 있음을 확인했습니다.

다만 명세에서 `현재 존재하는 지원자에 대해서만` 부분을 언급하고 싶은데
현재 코드 정책은 모든 부정 행위자를 조회하되, 존재하지 않는 지원자는 CheaterResponse의 name 필드가 null로 들어가고 있습니다.

``` kotlin
class CheaterService{
    fun findAll(): List<CheaterResponse> = cheaterRepository.findAll().map {
        val applicant = applicantRepository.findByEmail(it.email)
        CheaterResponse(it, applicant)
    }
}
```
