### ISSUE TITLE
메일 발송 API를 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#305]
1. 메일 발송 API를 구현한다.  
    - 메일 제목, 메일 내용, 첨부파일, 발송 대상 을 요청받아, 메일을 발송해야 한다.
        - 발송 대상을 복수(배열, 컬렉션 등)로 받을 수 있어야 한다.
        - 숨김참조를 통해 한번에 발송해야 한다.
            - [https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html) , `BCC`
            - 참조 목록에 우테코 메일도 포함해야 한다.(확인용)
        - 첨부 파일을 포함해 발송해야 한다.
            - [https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-email-raw.html](https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-email-raw.html)

관련 이슈: #281

**Comment by MyaGya** [comment]
AWS 키 관련해서 관리 이슈로 인해 잠시 중단된 상태입니다

**Comment by MyaGya** [comment]
## step1
메일 파싱, 50명 단위로 분리하여 메일 전송. 메일 형식은 `raw mail`으로 사용

## step2
메일 요청 과정에서 데이터 파일을 입력받아 전송하도록 변경

**Comment by MyaGya** [comment]
해당 기능은 테스트용으로 `JavaMailSender` 를 사용한 시점의 이미지이며, 차후 다른 메일 시스템이 도입될 경우 내용이 바뀔 수 있습니다.

# 메일 송수신
* 숨은 참조로 발송시 아래와 같이 발송인은 참조 인원을 모두 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/38939015/134484419-7472b25d-3eb8-4536-9d31-cbb47bcac4ae.png)


* 수신측은 아래와 같이 다른 수신자를 확인할 수 업습니다.
![image](https://user-images.githubusercontent.com/38939015/134484482-39224405-046c-46fa-908b-f7d80a01bec4.png)

송신 시 첨부파일을 추가할 경우 사용자는 첨부파일을 확인할 수 있습니다.
첨부파일의 제한은 아래와 같습니다
* 동시 파일 전송의 수 제한 없음
* 한 파일의 용량 제한은 없으나 메모리에 올라갈 수 있는 파일 용량은 10MB 로 제한되어 있음
![image](https://user-images.githubusercontent.com/38939015/134485332-04243c11-fe99-4fc4-8ba5-a94d4fc21ef6.png)

* 동시에 50명의 인원까지 묶어서 전송하며, 50명 이상의 인원이 존재할 경우 50명 단위로 전송합니다.
![image](https://user-images.githubusercontent.com/38939015/134485795-116e21f0-4a9d-4911-989f-a77f5776a9c4.png)
* 중복된 사용자가 50명 안에 포함되어 있을 경우 해당 인원은 중복해서 메일을 보내지는 않습니다. 그러나 새롭게 50명은 채우지는 않으며(50명중 중복인원이 1명 있을 경우 49명만 발송) 50명 묶음에서만 중복 메일을 검사합니다

**Comment by MyaGya** [comment]
AWS SES 사용 시 수신자 그룹인 `Destination` 은 필수입니다. 그러나 CC, BCC, ToAddress 각각은 필수 조건이 아닙니다.
![image](https://user-images.githubusercontent.com/38939015/136125687-6340b068-d6db-47cd-b0fe-0e49b92fa4ed.png)
![image](https://user-images.githubusercontent.com/38939015/136125691-47e7a689-70e9-42a1-906e-ed63524628c5.png)

참고 레퍼런스
https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html
https://docs.aws.amazon.com/ses/latest/APIReference/API_Destination.html

**Comment by MyaGya** [comment]
메일 발송 시 `mailService` 의 비동기 설정 때문에 파일 업로드가 완료되기 이전 메일을 발송하려다 실패하는 오류가 발생했습니다.
`Multipart file upload` -> `Tomcat` 임시 폴더에 파일 저장 -> 해당 파일 데이터를 통해 추가 작업 
이 과정중 `Tomcat` 에 파일이 저장되기 이전에 추가 작업을 하다 생긴 문제이므로 비동기 처리를 하기 이전 미리 `upload` 된 파일을 `ByteArray` 형태로 바꿔준 후에 비동기로 추가 작업을 진행하도록 변경했습니다.
자세한 사항은 `MailRestController` 를 참고 해 주세요

**Comment by woowahan-pjs** [comment]
### Amazon SES 전송 할당량

| 할당량 이름 | 적용된 할당량 값 | AWS 기본 할당량 값 |
| -- | -- | -- |
| 일일 전송 할당량 | 100,000 | 200 |
| 최대 전송 속도 | 14 | 1 |

- https://docs.aws.amazon.com/ko_kr/ses/latest/dg/manage-sending-quotas-errors.html
- https://aws.amazon.com/ko/blogs/messaging-and-targeting/how-to-handle-a-throttling-maximum-sending-rate-exceeded-error
- https://leoheo.github.io/AWS-SES

#### 일일 전송 할당량

현재 AWS 리전의 이 계정에 대하여 24시간 동안 보낼 수 있는 이메일의 최대 개수입니다.

#### 최대 전송 속도

Amazon SES가 현재 AWS 리전의 이 계정에 대해 초당 수락할 수 있는 최대 이메일 개수입니다.

**Comment by woowahan-pjs** [comment]
Amazon SES의 기본 메시지 크기 한도는 이메일 전송 시 10MB, 이메일 수신 시 30MB
