### ISSUE TITLE
인증 코드 요청을 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#326]
- 인증 코드 요청 HTTP API를 구현한다.
- 이메일이 중복인지 확인한다.
- `AuthenticationCode`을 생성한다.
   - `AuthenticationCode`의 `authenticated`은 `false`이다.
   - 필요한 경우 생성 일시, 만료 일시 등을 추가한다.
- 인증 코드 메일을 발송한다.

**Comment by knae11** [comment]
이메일 중복을 확인하는 이유는 이미 가입된 사용자인지 확인하기 위함이다.
