### ISSUE TITLE
회원 가입을 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#329]
- 회원 가입 HTTP API를 구현한다.
- `AuthenticationCode`의 `authenticated`가 `true`이어야 한다.

**Comment by NewWisdom** [comment]
### 기존 지원자 생성 로직 변경
- 기존 : 이메일로 지원자 존재 여부 확인 > 존재시 authenticate 후, 없을 시 지원자 저장 후 > 토큰 발급
- 변경 : 이메일 중복 체크 > 이메일에 해당하는 authenticationCode의 인증 여부 확인 > 지원자 저장 후 토큰 발급
- 기존 지원자 생성(register) http api는 applicants -> users 이외에 변경사항 없음
  
```json
POST "/api/users/register"

{
  "name": "아마찌",
  "email": "mazzi@gmail.com",
  "phoneNumber": "010-0000-0000",
  "gender": "FEMALE",
  "birthday": "2021-12-21T00:00:00",
  "password": "qwe123"
}
```

**Comment by NewWisdom** [comment]
### 회원 가입 후 토큰 발급
다음과 같은 프론트 의견 하에 **가입  후 토큰 발급으로 결정**
- 로그인과정을 생략하는 것이 지원하는 흐름에 있어서 좀 더 좋은 사용자 경험이 될 수 있을 것 같다
- 아이디/비밀번호를 반복해서 입력하는 과정이 부담으로 작용할 수 있을 것 같다
- 지원사이트는 회원가입 시점이 지원직전이니 편의성을 위해 바로 로그인해도 좋을 것 같다
