### ISSUE TITLE
토큰 유효기간이 만료되었을 경우를 대응한다.

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-apply#339]
### 이슈
- 백엔드에서 발급하는 토큰의 유효기간이 12시간
- 현재 프론트에서는 토큰 발급 후 localStorage에 저장하여 로그인 상태를 유지한다.
- 유효기간이 지난 이후에는 저장해둔 토큰을 정상적으로 사용할 수 없게 될 이슈 있음

### 작업 필요사항
- localStorage에 저장해둔 토큰 > 사용하는 시점에 토큰의 유효성 검사
- 토큰의 유효기간이 만료되었을 경우 어떻게 처리해줄 것인지 논의
  - **로그인 페이지로 이동**
  - ~~토큰 갱신~~
- 논의 사항 적용

**Comment by woowahan-pjs** [comment]
- https://github.com/woowacourse/service-apply/issues/44
- https://github.com/woowacourse/service-apply/pull/75#discussion_r491660272
- https://javadox.com/io.jsonwebtoken/jjwt/0.4/io/jsonwebtoken/JwtParser.html#parseClaimsJws-java.lang.String-
