### ISSUE TITLE
회원가입부터 과제 제출까지 스토리보드를 작성한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#347]
관련 이슈: #321

**Comment by SunYoungKwon** [comment]
[피그마 링크](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=207%3A2)

**Comment by SunYoungKwon** [comment]
### 기존에 만들어둔 이슈

- #244 
  - `Header`에 로그인 버튼 추가
  - 로그인 시 나타나는 버튼 툴팁 컴포넌트 구현
  - 모집 필터링 `Navigation` 컴포넌트 구현
  - 변경된 모집 디자인 반영
  - `Footer`의 Copyright 문구 변경

### 새로 생성할 이슈

- 사용자 입력 관련 컴포넌트 리팩토링
  - `TextInput` 컴포넌트 분리(`<input>`, `<textarea>`)
  - `TextField`
  - `SummaryCheckField` 
  -  `BirthFiled`
  - `GenderField`
  - 변경된 디자인 반영
- 로그인 & 회원가입 UI 구현
  - 이메일 인증 관련 UI 추가
    - 이메일 인증코드 발급  버튼
    - 이메일 인증 코드 입력창 & 인증 버튼
    - 이메일 인증 코드 유효시간 표시(새로고침하면 어떻게하지???)
  - 입력창 순서 변경(피그마 참고)
  - 비밀번호 찾기 화면 변경된 디자인 반영
- 마이페이지 UI 구현
  - 회원 정보 표시
  - 정보 수정화면 UI 구현
  - 비밀번호 변경 화면 변경된 디자인 반영
- 내 지원현황 & 과제 제출 UI 구현
  - `Panel` 컴포넌트 구현
  - 과제제출 폼 UI 구현
- 로그인/회원가입 기능 구현
  - 로그인
  - 로그인 시 `Header`의 버튼 구성 변경
  - 비밀번호 찾기
  - 회원가입 시 이메일 인증
  - 회원가입
- 마이페이지 기능 구현
  - 회원 정보 조회
  - 회원 정보 수정
  - 비밀번호 변경
  - 탈퇴하기
- 내 지원현황 & 과제 제출 기능 구현 
  - 내 지원 정보(지원한 모집과 모집 별 서류 합격 여부 및 과제 진행상황) 조회
  - 과제 제출
    - 과제 제출 이전 -> 제출하기
    - 과제 제출 이후 ~ 과제 기간 마감 이전 -> 수정하기
    - 과제 기간 마감 이후(제출o) -> 제출완료
    - 과제 기간 마감 이후(제출x) -> 미제출
