### ISSUE TITLE
내 정보 수정 페이지 UI가 깨진다.

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/service-apply#399]
현상: 내 정보 수정 페이지 UI가 깨진다.
재현 스텝: 로그인 > 마이페이지 > 내 정보 수정
예상되는 원인: 
스크린샷:

<img width="998" alt="137240738-e2a1a454-6c12-454c-b5cd-9b62197e0be8" src="https://user-images.githubusercontent.com/48229284/142829808-944537b4-9cf3-49d8-8822-b9d5cadcdff4.png">

**Comment by jho2301** [comment]
모바일 해상도 이슈로 확인됩니다.
