### ISSUE TITLE
회원 가입 화면에서 취소 버튼을 눌러도 반응이 없다.

### ISSUE THREAD

**Issue by YounghoonKwon** [woowacourse/service-apply#401]
현상: 회원 가입 화면에서 회원 가입 화면에서 취소 버튼을 눌러도 반응이 없다.
재현 스텝: 회원 가입 > 취소 버튼
예상되는 원인: 링크 누락
스크린샷: 

<img width="855" alt="Screen Shot 2021-10-14 at 11 54 16 AM" src="https://user-images.githubusercontent.com/28701943/137242965-37123c85-3d2e-45f1-a709-8e9dd60fe02b.png">

**Comment by woowapark** [comment]
취소 버튼 클릭시 링크 이동 로직이 누적된 것으로 보입니다.
