### ISSUE TITLE
임시 비밀번호가 오지 않는다.

### ISSUE THREAD

**Issue by YounghoonKwon** [woowacourse/service-apply#406]
현상: 임시 비밀번호가 오지 않는다.
재현 스텝: 임시 비밀번호 요청
예상되는 원인: `tempPassword` 속성이 누락되었다.
스크린샷:

<img width="648" alt="Screen Shot 2021-10-14 at 12 00 53 PM" src="https://user-images.githubusercontent.com/28701943/137243629-5cd7fecf-f6a1-4906-b432-593ce61f005c.png">

**Comment by woowapark** [comment]
- 템플릿에 값이 비어있는 상태입니다. 값이 있는 경우 정상적으로 렌더됩니다.
- 비밀번호 생성에 문제가 있거나, 단순히 이메일 템플릿에 데이터 전달이 잘못 이루어지고 있을 수 있을 것 같습니다.
