### ISSUE TITLE
임시 저장된 지원서 불러오기 시 사실 확인 여부에 동의하지 않아도 제출 버튼이 활성화된다.

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse/service-apply#412]
현상: 임시 저장된 지원서 불러오기 시 사실 확인 여부에 동의하지 않아도 제출 버튼이 활성화된다.
재현 스텝: 모든 지원 항목 작성 > 임시 저장 > 지원서 불러오기
예상되는 원인: 
스크린샷:

![image](https://user-images.githubusercontent.com/37354145/137244534-850006cc-47de-4e07-8cc3-4eae0a47a3e8.png)

**Comment by jho2301** [comment]
필수가 아닌 url  input 입력 -> 임시저장 -> 새로고침시 해당 이슈 발생합니다
