### ISSUE TITLE
지원 가능한 모집과 지원할 수 없는 모집을 구분하기 어렵다.

### ISSUE THREAD

**Issue by YounghoonKwon** [woowacourse/service-apply#413]
현상: 이미 지원한 모집, 지원하지 않은 모집, 지원하지 못하는 모집을 구분하기 어렵다.
재현 스텝: 
예상되는 원인: 
스크린샷:

<img width="895" alt="Screen Shot 2021-10-14 at 12 14 08 PM" src="https://user-images.githubusercontent.com/28701943/137244804-4190f935-e6fe-4ac5-8b76-a225773f39b1.png">

<img width="886" alt="Screen Shot 2021-10-14 at 12 12 26 PM" src="https://user-images.githubusercontent.com/28701943/137244701-60984d72-0229-43c0-a719-73c3b901c4f7.png">

<img width="916" alt="Screen Shot 2021-10-14 at 12 12 31 PM" src="https://user-images.githubusercontent.com/28701943/137244703-99f564e6-ff78-41a8-bbd9-49dfc8a869dd.png">

<img width="895" alt="Screen Shot 2021-10-14 at 12 12 19 PM" src="https://user-images.githubusercontent.com/28701943/137244706-05fbf353-7412-4b67-8316-5f1e93378907.png">

**Comment by devJang** [comment]
<img width="836" alt="스크린샷 2021-10-14 오전 11 57 49" src="https://user-images.githubusercontent.com/23068523/137244998-9b57aac9-fc12-4e1b-9f19-9dd7c3518cc4.png">

저도 그러네용

**Comment by woowapark** [comment]
- 같은 기수 다른 모집에 지원하는 경우 이슈
  - 지원 화면으로 이동 후 오류 팝업 노출 '해당하는 지원서가 없습니다'
  - 상황에 맞는 오류 메시지로 수정 가능한지 확인이 필요합니다. 
  - 이동하지 않고 팝업 노출되도록 수정 필요하지 않을까 합니다. 
- 이미 지원 완료한 모집에 다시 지원하는 경우 이슈 
  - 지원 화면으로 이동 후 오류 팝업 노출 '이미 제출한 지원서는 열람할 수 없습니다'
  - 이동하지 않고 팝업 노출되도록 수정 필요하지 않을까 합니다. 
  - <img width="836" alt="스크린샷 2021-10-14 오전 11 57 49" src="https://user-images.githubusercontent.com/23068523/137244998-9b57aac9-fc12-4e1b-9f19-9dd7c3518cc4.png">
