### ISSUE TITLE
프론트 지원 형식이 깨져있어요

### ISSUE THREAD

**Issue by Be-poz** [woowacourse/service-apply#415]
현상: 프론트 지원 형식이 깨져있어요
재현 스텝: 프론트 지원!
예상되는 원인: 프론트 문제...요..
스크린샷:
![image](https://user-images.githubusercontent.com/45073750/137244810-7d4f3ee6-ccde-47a7-be00-d5ca757fe44b.png)

**Comment by SunYoungKwon** [comment]
어떤 부분이 깨져있는건지 자세히 써주실수 있나요?
