### ISSUE TITLE
[지원자] 이메일 인증시 인증코드 유효시간이 남아있지만, 인증에 실패하는 현상

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/service-apply#433]
현상: 지원자 화면에서 인증코드 유효시간이 남아있지만, 실제로는 가입이 되지 않는 현상
재현 스텝: 화면상 유효시간은 남아있으나, 실제 시간은 10분이 지난경우 회원가입에 실패합니다.
예상되는 원인: #431 와 관련이 있어보입니다.
스크린샷:

![image](https://user-images.githubusercontent.com/43930419/137255584-01021bdb-5e94-4541-a069-a0f8d63f2f9d.png)

**Comment by woowapark** [comment]
https://github.com/woowacourse/service-apply/issues/431 에서 같이 확인하겠습니다.
