### ISSUE TITLE
LNB 스타일이 깨진다.

### ISSUE THREAD

**Issue by pocojang** [woowacourse/service-apply#434]
현상: LNB 스타일이 깨진다.
재현 스텝: 관리자 콘텐츠를 늘어지도록 한다.
예상되는 원인: 마크업 스타일
스크린샷:

<img width="361" alt="스크린샷 2021-10-14 오후 2 09 17" src="https://user-images.githubusercontent.com/23068523/137255782-b9963d8a-e5d8-4190-b08a-55a0be1a7f55.png">

**Comment by woowahan-pjs** [comment]
https://developer.mozilla.org/ko/docs/Web/CSS/overflow
