### ISSUE TITLE
[지원자] 인증코드가 일치하지 않습니다 라는 메시지가 뜬 순간부터, 인증코드 유효시간이 줄어들지 않는 현상

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/service-apply#436]
현상: alert창이 뜬뒤로 인증코드 유효시간이 차감되지 않습니다. 즉, 일치하지 않습니다 창을 10초간 띄워두면, 인증 코드 유효시간이 10초가 차감되어야하는데 alert창이 뜬순간부터 시간이 멈춥니다.
재현 스텝: 잘못된 이메일 인증코드를 입력 후 인증코드가 일치하지 않습니다. alert창을 띄운뒤 대기하면 발생
예상되는 원인: 페이지에 머물러 있는 시간을 기반으로 유효시간이 줄어드는것으로 파악되어짐
스크린샷:

![image](https://user-images.githubusercontent.com/43930419/137256051-932642cf-22b2-41db-9727-8ff1db0309eb.png)

**10초뒤**

![image](https://user-images.githubusercontent.com/43930419/137256059-f1662901-e35c-4724-8457-eb0293e4ebcf.png)

- 1초 줄어든것이 아닙니다. 빠르게 찍지 못해서 11초가 되었으나, 12초였습니다.

**Comment by woowapark** [comment]
https://github.com/woowacourse/service-apply/issues/431 에서 같이 확인하겠습니다
