### ISSUE TITLE
생년월일에 공백을 포함할 수 있다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/service-apply#438]
현상: 생년월일에 공백을 포함할 수 있다. 생년월일에 공백을 입력하면 텍스트를 입력할 때와 같이 경고 표시가 나타나지 않는다.
재현 스텝: 생년월일에 공백을 입력
예상되는 원인: 사파리에서 숫자 입력 시 숫자 이외의 문자 입력이 가능하다.
스크린샷:

![image](https://user-images.githubusercontent.com/43930419/137256417-a6412e8a-a915-4d8e-b085-d94139d72f39.png)

**Comment by jho2301** [comment]
사파리에서 number 타입 input에 숫자외 입력이 가능해 발생한 현상으로 파악했습니다
