### ISSUE TITLE
지원자 등록 기능을 추가한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#44]
- 지원자 등록 API를 호출한다.
   - 지원자 정보를 Body에 추가한다.
   - 토큰을 전역 상태에 저장한다.
- 성공했을경우 지원서 작성 페이지로 이동한다.
- 실패했을 경우
   - 중복된 지원자 정보를 입력한 경우 '이미 등록한 지원자 입니다' 알림을 띄운다.
   - 유효하지 않은 값을 요청한 경우 '잘못된 요청입니다' 알림을 띄운다.

**Comment by ddaaac** [comment]
논의할 내용

1. Token 방식(atdd-subway의 JwtTokenProvider 사용?)
1. 만약 기존 JwtTokenProvider 사용한다면 버전 업그레이드
1. secret값 및 유효시간 관리 -> 서브 모듈 사용?
1. 버전 업그레이드 했을 때, 기존 코드의 보안 이슈
    - secret 값을 지정해 주는 방식보다 랜덤한 secret 값을 주는 게 더 안전하다 [링크](https://github.com/jwtk/jjwt)
    > However, raw password strings like this should be avoided whenever possible because they can inevitably result in weak or susceptible keys. Secure-random keys are almost always stronger. 
1. Applicant 엔티티의 password 필드와 그 저장 방식(이슈 분리?)
1. 엔티티 create 할 때, dto를 넘길지 / 파라미터를 넘길지 / 엔티티를 넘길지

**Comment by ddaaac** [comment]
# 토큰 관련 결정사항
![image](https://user-images.githubusercontent.com/43440195/93284373-8baf3480-f80d-11ea-8dff-96d98ad99ff2.png)
- 위와 같은 이유로 토큰의 유효기간은 비교적 짧게 12시간으로 설정
- secret 값을 지정하는 방식의 장점은 서버 재시작시 SecretKey 값이 변하지 않는다는 장점이 있음
  그런데, 어차피 토큰 유효기간도 짧고 해서 좀 더 안전한 랜덤한 키를 부여하는 방식을 선택
