### ISSUE TITLE
[지원자] 생년월일에 처음부터 문자열을 입력을하면, 경고메시지가 나타나지 않습니다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/service-apply#440]
현상: 생년월일 창에 처음부터 문자열을 입력하는 경우, 경고표시가 나오지 않습니다.
재현 스텝: 생년월일에 바로 문자열을 입력합니다.
예상되는 원인: 
스크린샷:

![image](https://user-images.githubusercontent.com/43930419/137257427-5a792a48-f211-48cb-9a72-8f904d2db235.png)

**Comment by woowapark** [comment]
https://github.com/woowacourse/service-apply/issues/438 에서 같이 확인합니다.
