### ISSUE TITLE
[지원자] 모바일 해상도 지원 미비

### ISSUE THREAD

**Issue by jho2301** [woowacourse/service-apply#442]
## 추후 모바일해상도 대응할 것인지 판단해보면 좋을 것 같습니다

- 네비게이션바, 본문 지원 아이템 박스 잘려서 나오는 현상
![image](https://user-images.githubusercontent.com/44419181/137258260-443ceeaf-b4c5-4730-9203-b1f2d8c28b36.png)

- 핀치시, footer 짤려서 나오는 현상
![image](https://user-images.githubusercontent.com/44419181/137258269-e87f0ad4-e295-4a5f-a3a8-3cc2b09df57d.png)

**Comment by zereight** [comment]
중복: https://github.com/woowacourse/service-apply/issues/424
