### ISSUE TITLE
메일에서 그룹 불러오기 시 특정 대상자가 불러와 지지 않는다.

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/service-apply#459]
현상: 메일에서 그룹 불러오기 시 특정 대상자가 불러와 지지 않는다.
재현 스텝: 과제 생성 > 지원자 부정 행위자 등록 > 지원자 과제 제출 > 메일 보내기 > 그룹 불러오기 > '웹프론트 4기 (서니)', '과제2', '탈락' 지정 

- '웹 프론트 4기(서니)'에는 총 2개의 과제가 등록되어 있으며, 1차 과제는 합격, 2차 과제는 탈락이고, 지원자는 부정 행위자로 등록하였습니다.
- 이후에 메일 보내기에서 그룹 불러오기를 하면 1차 과제에서는 합격자와 불합격자 모두 잘 검색되지만 2차 과제에서는 지원자가 검색되지 않습니다.

예상되는 원인: 탈락자 중 과제를 미제출한 사람(점수가 0점)은 불러오지 않는다.
스크린샷:

![](https://user-images.githubusercontent.com/67677561/137265683-af49eb4d-5392-4c13-95cd-d429bbb7ae5d.png)

![](https://user-images.githubusercontent.com/67677561/137265695-d6d2bbb6-d914-4179-aa7f-90cb2bcf029d.png)

**Comment by knae11** [comment]
올려주신 내용은 확인 결과 버그가 아니며 정상동작으로 판단하였습니다. 하지만 탈락자를 선택 시, 조건에 맞는 경우만 불러와지는데 사용자가 오해할 수 있을 것 같아 문구를 추가하는 방식으로 해결하였습니다. 😄
