### ISSUE TITLE
비공개 모집의 지원서를 임시로 저장해도 지원 완료 메일이 온다.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse/service-apply#462]
현상: 비공개 모집에 지원서를 임시로 저장했는데 지원 완료 메일이 온다.
재현 스텝: 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/33603557/137267353-1d1c64a9-ce76-4eae-bfac-e89702fa7b28.png">

예상되는 원인: 
스크린샷:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/33603557/137267864-e8fe94c2-4b25-4c17-80f0-4a8597008f50.png">

**Comment by woowahan-pjs** [comment]
비공개라도 지원이 가능하면 지원 가능합니다.
