### ISSUE TITLE
네비게이션에서 하위 메뉴를 클릭하면 메뉴가 많을 경우 bg-color가 전체적으로 적용되지 않는다.

### ISSUE THREAD

**Issue by wmakerjun** [woowacourse/service-apply#470]
현상: 네비게이션에서 하위 메뉴를 클릭하면 메뉴가 많을 경우 bg-color가 전체적으로 적용되지 않는다.
재현 스텝: 과제 관리 메뉴를 클릭하면 발생한다.
예상되는 원인: 색상을 지정하는 CSS 부분에서 높이 설정을 변경해야 할 것 같아요.
스크린샷:

<img width="332" alt="스크린샷 2021-10-15 오전 10 34 46" src="https://user-images.githubusercontent.com/50367798/137418274-7e80ff98-5f76-46d9-bbdc-e23a93cff448.png">

**Comment by wmakerjun** [comment]
오! height을 100%가 아닌 auto로 하니 문제가 해결되는 것 같아요~!

<img width="1789" alt="스크린샷 2021-10-15 오전 10 43 44" src="https://user-images.githubusercontent.com/50367798/137419212-0df76757-929b-4c53-9d4e-ac7622fdedd5.png">

**Comment by woowapark** [comment]
https://github.com/woowacourse/service-apply/issues/434 에서 같이 확인하겠습니다.
