### ISSUE TITLE
이미 제출한 지원서 페이지에 불필요한 텍스트가 표시된다.

### ISSUE THREAD

**Issue by kang-hyungu** [woowacourse/service-apply#476]
현상:

- 이미 지원서를 제출한 모집을 클릭하면 완료된 지원서가 노출된다.
- '임시 저장되었습니다.()'이라는 문구가 나타난다.

재현 스텝: 특정 모집의 지원서 제출 > 같은 모집 클릭
예상되는 원인: 지원서를 조회한 후 열람 여부를 결정한다.
스크린샷:

![image](https://user-images.githubusercontent.com/15669435/137456993-aced6861-d096-45ba-bf80-3a69771ea6ce.png)

**Comment by woowapark** [comment]
https://github.com/woowacourse/service-apply/issues/413 에서 같이 확인하겠습니다
