### ISSUE TITLE
사용자 입력에 대한 유효성 검사 및 제약 조건을 점검한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#495]
### 과제 제출물

- GitHub username: `^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}$/i`, 최대 39자
   - https://github.com/shinnn/github-username-regex

```   
- Github username may only contain alphanumeric characters or hyphens.
- Github username cannot have multiple consecutive hyphens.
- Github username cannot begin or end with a hyphen.
- Maximum is 39 characters.
```

- 소감: 공백만 입력할 수 없다, 최대 1000자
- Pull Request URL: `https:\/\/github\.com(\/[\w\-]+){2}\/pull\/[1-9]\d*`, 최대 255자

### 지원서

- 포트폴리오: 최대 255자
- 답변
   - 제출 시: 비워둘 수 없다, 모집 항목의 최대 글자 수를 초과할 수 없다.
   - 임시 저장 시: 모집 항목의 최대 글자 수를 초과할 수 없다.

### 회원

- 생년월일: 미래일 수 없다.
- 이메일: 최대 255자
- 성별: 최대 6자(FEMALE)
- 이름: `[가-힣]{1,30}`, 최대 30자
- 휴대폰 번호: `010-\d{4}-\d{4}`, 13자
- 비밀번호: 영문, 숫자, 특수 문자 포함, 최소 8자, 최대 20자, 암호화

관련 이슈: #408 #409 #410 #441 #455 #464 #479

**Comment by jho2301** [comment]
## 사파리 textarea에 줄바꿈시 value.length가 2증가하는 현상

일반적으로 브라우저에서는 textarea의 개행문자가 LF, 서버로 전달되는 textarea의 개행문자는 CRLF이다.
https://if1live.github.io/posts/what-is-textarea-newline/

LF -> CRLF, CRLF -> CRLF로 변환됨.

사파리는 CRLF를 브라우저에서도 개행문자로 사용하고있는 것이아닐까 추측. 확인해볼예정
