### ISSUE TITLE
사용자 입력 관련 컴포넌트를 수정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#497]
관련 이슈: #397 #401 #402 #404 #408 #409 #410 #412 #420 #426 #438 #441 #444 #451 #461 #464 #432

**Comment by jho2301** [comment]
## 사파리 textarea에 줄바꿈시 의도한 maxLength에 도달하기 전에 입력이 되지 않는 현상

일반적으로 브라우저에서는 textarea의 개행문자가 LF, 서버로 전달되는 textarea의 개행문자는 CRLF이다.
https://if1live.github.io/posts/what-is-textarea-newline/

LF -> CRLF, CRLF -> CRLF로 변환됨.

사파리는 CRLF를 브라우저에서도 개행문자로 사용하고 있다.

그래서 maxLength 속성에서 판단하기를 개행을 \r\n 두 개의 문자로 판단하는 것.

그래서 일관된 동작을 위해서는 textarea에 네이티브속성으로 전달하지말고 onChange 핸들러함수에서 최대길이를 제어하도록한다
