### ISSUE TITLE
관리 화면에 대한 스토리보드를 작성한다. - 9월 2일(수)

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#5]
https://ovenapp.io/view/BjM1mNQwXRl5aQ6Ww3mPsSHJPibTUBIo

**Comment by toneyparky** [comment]
제이슨 프론트 관련 이슈를 도출하다보니 논의하면 좋을 사항이 생겨 말씀드립니다. 세가지 입니다.

1. 모집 항목 생성과 평가 항목 생성 +와 - 버튼이 어색합니다.
항목들 마지막에 추가하면 되는 +는 괜찮은데 - 버튼이 눌렸을 때에 어떤 항목이 삭제되는지 불분명합니다. 
삭제 버튼을 항목별로 추가하는게 더 낫다는 생각이 들었습니다.
기존 + 버튼은 그대로 둬도 좋을 듯 합니다. 혹은 추가하기라는 버튼으로 만들어도 좋을듯합니다.

예시) 
![image](https://user-images.githubusercontent.com/37579660/91790160-0c393700-ec4b-11ea-8079-0710a785eec9.png)


2. 평가에 대한 뷰가 있으면 좋을 것 같습니다. 현재 테이블의 컬럼만 적혀있어서 평가에 대한 프론트 이슈를 세부적으로 도출하는데에 어려움을 겪고있습니다. 평가를 조회하는 뷰와 평가를 하는 뷰에 대한 프로토타입이 있으면 좋을 것 같습니다.

해당 화면
![image](https://user-images.githubusercontent.com/37579660/91790187-152a0880-ec4b-11ea-9ddf-c73b0645695a.png)


3. 선발 과정의 평가하는 페이지에 부정행위자로 추가하는 버튼이 있다면 보다 쉽게 부정행위자를 추가할 수 있을 거라는 생각이 들어 의견을 전합니다.
부정행위자를 색출해내는 과정이 평가 중에 발생할 것으로 예상되니 2번 질문에서 제작을 부탁드린 평가하는 페이지에 부정행위자 추가 버튼이 들어가도 좋을 것 같다는 생각이 듭니다.

감사합니다

**Comment by woowahan-pjs** [comment]
@toneyparky @lowoon 
반영했습니다. 확인 부탁드려요.

**Comment by toneyparky** [comment]
확인했습니다.
빠른 반영 감사드려요. 제이슨 최고👍

**Comment by lowoon** [comment]
확인했습니다 👍
