### ISSUE TITLE
지원 화면 UI/UX 워크숍을 진행한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#532]
### 목표
지원 플랫폼 3.0.0에서 
- 지원 페이지 사용성 개선 목표 및 이슈를 정리한다. 

### 작업 목록
- UX 워크샵을 약식으로 진행할 수 있도록 준비한다. 
- 7월 11일 월요일 워크샵을 진행한다. 

### 참고 사항
- 지원 페이지 논의가 끝난 뒤 가능하다면 같은 진행 방식으로 관리 페이지 사용성 개선 논의도 진행한다.
  - 시간이 된다면 워크샵에서 같이, 부족하다면 별도 일정으로 잡을 예정

**Comment by woowapark** [comment]
포인트 추정: 2

**Comment by soyi47** [comment]
# UI/UX 워크샵 결과 정리

## 아이디어

- 제출한 지원서 미열람 이슈 + 지원서 제출 기간 내 최종 제출 후 미리보기 또는 수정
    - 모집기간 내 미리보기 (또는 수정)
    - 최종 제출 이후 수정 불가 정책 관련 → 백엔드 상황 점검 필요
    - 최종 제출 버튼 클릭 시 Confirm 절차 추가

- 프리코스 제출 과정이 직관적이지 않다
    - 합격자들에 대해서는 메인 페이지에서 내 지원현황을 노출시키면 어떨까?
        - 마이페이지에서 내 지원현황을 빼고, 메인 페이지에서 바로 노출하자.
    - Header에서 내 지원현황에 바로 접근할 수 있으면 좋겠다. Header를 조금 더 활용해서 메뉴를 넣어보자.
    - 메인 페이지의 nav 탭(전체, 모집예정, 모집 중, 모집 종료)을 구분해야하나? 줄이자.
        - 모집 중, 모집 예정은 합쳐서 기간 순으로 정렬하고
        - 모집 종료를 없애자

- 모집의 구분이 더 뚜렷하고 명확하면 좋겠다. → UI 디자인 수정면

- QnA 접근성
    - Footer에 카카오톡 문의하기 링크 추가하기

- 모집일정과 인원, 모집공고에 대한 소개가 나와있어야 한다.
    - 모집과정별 정보 제공 안내 페이지가 있으면 어떨까?
        
        → 어떤 정보가 필요한가에 대한 논의 필요
        
        - 과제별 일정 지원/진행기간

<br >

## 우테코 사이트와 관련된 불편함

- 우테코 사이트와 지원 사이트의 구분이 어렵다
- 지원 사이트 버튼이 숨겨져 있다.

<br >

## 정책과 관련된 불편함

- PR에 후기를 적는 것과 지원 사이트에 후기를 적는 것이 혼란스럽다.
- 제출 중에 단 하나의 링크만 제출할 수 있는 것이 불편하다 → 노션으로 정리해서 제출해야했다.
- 공지가 사이트를 통해 확인할 수 없었다. → 공지는 과정별, 단계별 합격자에게만 노출되도록 해야한다.

**Comment by soyi47** [comment]
## 이슈
- QnA 접근성
    - Footer에 카카오톡 문의하기 링크 추가한다.

## 논의사항
- 지원서 제출 기간 내 최종 제출 후 미리보기 또는 수정을 가능하게 하자.
    - 현재 상황 : 제출한 지원서를 열람할 수 없다.
    - 아이디어
        - 모집기간 내 미리보기 (또는 수정)
        - 최종 제출 이후 수정 불가 정책 관련 → 백엔드 상황 점검 필요
        - 최종 제출 버튼 클릭 시 Confirm 절차 추가
    - 논의 대상
        - 코치분들, 백엔드 크루들, 프론트 크루들
        
- 메인 페이지 UI에 대해서 얘기해보자.
    - 현재 상황 : 메인 페이지에 불필요한 정보가 존재한다.
    - 아이디어
        - 내 지원현황 접근성 높이기
            1. 합격자들에 대해서는 메인 페이지에서 내 지원현황을 노출시키면 어떨까?
                
                마이페이지에서 내 지원현황을 빼고, 메인 페이지에서 바로 노출하자.
                
            2. Header에서 내 지원현황에 바로 접근할 수 있으면 좋겠다. Header를 조금 더 활용해서 메뉴를 넣어보자.
        - Nav 탭을 줄이자
            1. 전체, 모집예정, 모집중, 모집 종료 를 통합하거나 불필요하면 삭제한다.
    - 논의 대상
        - 공원, 프론트 크루들

- 모집 과정에 관한 정보를 제공하자.
    - 현재 상황 : 모집 과정에 관련된 정보가 전혀 없다라고 볼 수 있다.
    - 아이디어
        - 모집일정과 인원, 모집공고에 대한 소개가 나오면 좋을 것 같다.
        - 모집과정별 정보 제공 안내 페이지가 있으면 좋을 것 같다. (과제별 일정 지원/진행기간)
    - 논의 대상
        - 코치분들, 프론트 크루들, 백엔드 크루들

- 공지사항을 유저들에게 노출했으면 좋겠다.
    - 현재 상황  : 공지사항은 메일로만 전달되고 있다.
    - 아이디어
        - 사이트를 통해 공지를 확인할 수 있게하자.
        - 공지는 과정별, 단계별 합격자에게만 노출되도록 해야한다.
    - 논의 대상
        - 코치분들, 프론트 크루들, 백엔드 크루들

## 기타 피드백
- 모집의 구분이 더 뚜렷하게 하자
    1. 텍스트 외에 아이콘 등을 사용해서 ui적으로 이쁘게 하자
- 정책
    - PR에 후기를 적는 것과 지원 사이트에 후기를 적는 것이 혼란스럽다.
    - 제출 중에 단 하나의 링크만 제출할 수 있는 것이 불편하다 → 노션으로 정리해서 제출해야했다.
- 우테코 사이트(지원 사이트 ❌)
    - 우테코 사이트와 지원 사이트의 구분이 어렵다
    - 지원 사이트 버튼이 숨겨져 있다.

**Comment by woowapark** [comment]
@soyi47 
### 논의 사항 관련 
논의사항에 있는 내용들 중에서도 3.0.0에서 진행할 항목과 논의 내용 정도만 정리해둘 항목을 구분해두면 좋을 것 같습니다 🙂      
개발 이슈로 만들 항목들을 정하고 -> 해당 이슈와 관련해 논의해야 하는 항목들이 이미 정해진 게 있다면 이슈에 대한 '설명', 혹은 '할 일'로 함께 적어두는 것으로 생각해주시면 될 것 같아요. 

- 신규 기능 외에 TS 전환 및 리팩토링 등의 기술 과제도 있다는 점을 감안해서 3.0.0에서 어디까지 해볼 수 있을 것 같은지
- 작업 일정을 고려했을 때 몇 가지만 선택해야 한다면 우선순위가 어떻게 될지           

의견을 정리해주시면 저랑 같이 주간회의에서 결정해보시죠~! 

### 기타 피드백 관련
- 모집에 대한 UI 개선은 작업의 크기도 크지 않을 것 같아 이슈로 추가해서 진행해도 좋을 것 같은데요~? 
- 정책에 대한 부분은 코치분들과 따로 논의해보고 결정 사항을 다시 공유드릴게요 🙂
