### ISSUE TITLE
Kotest의 테스트 스타일을 소개하고 상황에 맞는 스타일을 선택한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#533]
> Some teams prefer to mandate usage of a single style, others mix and match. There is no right or wrong - do whatever

- https://kotest.io/docs/framework/testing-styles.html
- https://johngrib.github.io/wiki/junit5-nested

**Comment by jojogreen91** [comment]
### JUnit 의 단점

<img width="675" alt="스크린샷 2022-07-05 오후 9 50 25" src="https://user-images.githubusercontent.com/82805588/177331646-ad8f8fbe-6d6f-4e97-b10b-a7924d54b819.png">

- 테스트코드가 중복될 경우가 많다.
- 한눈에 알아보기 어렵다.
- 테스트 스타일이 한정적이다, 단위테스트에 특화되어 있다.

### Kotest 로 왜 전환해야 하는가?
- 기존 nested test 의 가독성을 개선할 수 있고 중복을 줄일 수 있다.
- DSL 을 활용해서 더 가독성 높은 테스트를 작성할 수 있다.
- 다양한 테스트 스타일을 테스트 상황에 맞게 설정하여 더 효과적인 테스트 코드를 작성할 수 있다.
- Kotest 를 사용하면 빠트린 테스트 코드를 찾기 쉽고 테스트 코드를 관리할 때 스코프 범위만 신경쓰면 된다.
- 다른 플랫폼에서 호환이 가능하다.
- 쓰면서 장점을 알아가고 싶다.

### 상황별 Kotest 적용 예상
> 단위 테스트(domain, application, presentation)
- Annotation Spec, String Spec
  - Annotation Spec : JUnit 에서의 migration 이 간단하고 익숙하다.
  - String Spec : display name 의 명시를 강제할 수 있다(Should), 간결하고 가독성이 좋다, 테스트 함수명을 일관되게 유지할 수 있다.
> 통합 테스트(인수)
- Describe Spec(DCI 패턴), Behavior Spec

### DCI 패턴의 장점

[DCI 패턴](https://johngrib.github.io/wiki/junit5-nested/)

<img width="430" alt="스크린샷 2022-07-05 오후 9 42 31" src="https://user-images.githubusercontent.com/82805588/177330081-8d213f74-fa37-4492-8c40-de6920d13bf8.png">

- 단순한 주석을 사용했을 때 보다 강제성을 부여할 수 있다.
- 테스트 코드와 결과를 indent 로 계층 구조화할 수 있기 때문에 이해하기 쉽다.

### Behavior Spec 의 장점
- 익숙한 given, when, then 을 명시적으로 테스트코드에 표현할 수 있다.
- 간결하고 가독성이 좋다.
- BDD 스타일의 테스트 코드 작성에 용이하다.
