### ISSUE TITLE
기존 테스트를 Kotest의 주석 스타일로 마이그레이션한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#534]
3일

**Comment by cjlee38** [comment]
## A. Set Up

- build.gradle 에 다음 의존성을 추가한다.

```kotlin
// 1.6.10 버전 기준. 1.5.X 버전으로 사용할 경우 kotest의 버전을 4.X.X로 낮춰야 한다.
testImplementation("io.kotest:kotest-runner-junit5:5.3.2")
testImplementation("io.kotest:kotest-assertions-core:5.3.2")
```

- intellij의 kotest plugin 을 설치한다.(실행용)

## B. Trouble Shooting

### 1. 생성자로 Bean을 주입 받을 수 없다.

`Could not create instance of class apply.domain.cheater.CheaterRepositoryTest. Specs must have a public zero-arg constructor.`

- 증상
    - AnnotationSpec()을 상속받고 실행하려고 하면, zero-arg constructor(default constructor)가 필요하다.
    - 한 편, 기존 코드는 생성자를 통해 Spring Bean을 주입받는다
    - `@TestConstructor*(*autowireMode = TestConstructor.AutowireMode.*ALL)*`
    - 이를 해결하려면, Spring Bean을 필드 주입을 통해 입력받을 수도 있으나, 이 방법도 문제가 있음(2번에서 설명)
- 원인
    - 아마 다음 이슈와 비슷한 이유지 않을까싶다.
    - [https://minkukjo.github.io/framework/2020/06/28/JUnit-23/](https://minkukjo.github.io/framework/2020/06/28/JUnit-23/)
- 해결 방법
    - 다음과 같이, kotest에서 Spring Extension에 대한 의존을 추가해주면 된다.
    - `testImplementation("io.kotest.extensions:kotest-extensions-spring:1.1.1")`
    
![image](https://user-images.githubusercontent.com/52564093/178106318-2cd836b4-d635-4b8e-a36c-32bf2811ea17.png)

    

### 2. `@Autowired` 로 필드 주입을 받을 수 없다.

`kotlin.UninitializedPropertyAccessException: lateinit property evaluationTargetRepository has not been initialized`

- 증상
    - `@Autowired` 어노테이션을 통해 주입받으려 하는 경우 예외가 발생한다(lateinit 변수가 초기화되지 않았다고 예외를 던진다)
- 원인
    - 실행 주체인 kotest가  `@Autowired` 를 활성화시키지 않는다.
- 해결
    - 아래와 같이 명시적으로 전역 설정을 추가해준다.
    
    ```kotlin
    // ProjectConfig.kt
    
    object ProjectConfig : AbstractProjectConfig() {
        override fun extensions(): List<Extension> = listOf(SpringExtension)
    }
    ```
    

### 3. `ProjectConfig`를 등록하면, 다시 생성자로 주입 받을 수 없다.

`java.lang.ClassNotFoundException: kotlinx.coroutines.test.TestDispatcher`

- 증상
    - 1번과 2번 항목을 반영한 뒤, 다시 테스트를 실행하면 위와 같은 예외가 발생한다.
    - 그런데 캐시의 영향인지, 알 수 없는 이유로 `ProjectConfig`를 제거해도 같은 문제가 발생한다.
- 원인
    - 스프링부트에서 설정된 `kotlin-coroutines` 의 버전이 올바르지 않다.
    - kotest에서는 1.6.0 이상을 요구하는데, 스프링에서 가져온 버전은 그 미만이다.
    - [https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot-dependencies/build.gradle](https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot-dependencies/build.gradle) (987 line)
- 해결
    - 따라서 다음과 같이 명시적으로 버전을 지정해야 한다.
    - build.gradle.kts 에 다음을 추가한다.
    - `extra["kotlin-coroutines.version"] = "1.6.0"`
    - (참고자료) [https://github.com/kotest/kotest/issues/2782#issuecomment-1016466398](https://github.com/kotest/kotest/issues/2782#issuecomment-1016466398)

## 1~3번 관련 이슈

[https://github.com/jojogreen91/service-apply/pull/1](https://github.com/jojogreen91/service-apply/pull/1)

## 4.@Nested 어노테이션을 붙이면 테스트 객체가 생성되지 않는다.

`java.lang.IllegalArgumentException: object is not an instance of declaring class`

- 증상
    - `Nested` 어노테이션을 붙이면, 위와 같은 예외가 발생한다.
    - 해당 예외는 존재하지 않는 객체에 대해 메소드를 호출하려 하는 경우 발생한다.
- 원인
    - kotest에서 제공하는 Nested 어노테이션은 `inner class` 케이스에 대해 고려하지 않는다.
    - 즉, 해당 어노테이션을 붙인 클래스는 (바깥 클래스와 연관이 없는) nested 클래스여야 한다.
- 해결
    - describe spec을 활용한다.
- 관련 자료
    - https://github.com/kotest/kotest/issues/2367

## 5. verify 메소드가 올바르게 동작하지 않는다.

- 증상
    - mock 객체의 메소드가 몇 번 실행되었는지 확인하는 메소드 verify(exactly = 1) 가 올바르게 동작하지 않는다. (2번 호출되었다는 예외를 던진다)
- 원인
    - 테스트가 격리되지 않아서 발생하는 문제. 하나의 클래스에, 서로 다른 테스트 케이스에 해당 메소드를 호출하는 코드가 있었다.
    - 매 테스트 실행(메소드 실행)마다 인스턴스를 새로 생성하는 JUnit과 달리, Kotest는 하나의 인스턴스로 모든 테스트를 수행한다.
- 해결
    - mock 객체를 `@BeforeEach` 단계에서 매 번 새로이 초기화하였다. `mockkClass(XXX::class`

# 참고자료

[https://kotest.io/docs/extensions/spring.html](https://kotest.io/docs/extensions/spring.html)

**Comment by cjlee38** [comment]
## 미해결 사항
- 현재 RestControllerTest 에는 restdocs를 위한 Junit 어노테이션이 남아있는 상태이다. Junit에 대한 종속성을 완전히 제거하기 위해 이를 제거해야 할까 ? 아니면 작성하는 테스트 코드를 kotest로 활용하기 위해 그대로 사용해도 괜찮을까? (RecruitmentFormTest 또한 MockK에 대한 extension을 사용한다)
- kotest 를 사용할 경우 빌드 시간이 너무 오래 걸린다. 원인이 무엇이고, 어떻게 해결할 수 있을까 ?

**Comment by woowahan-pjs** [comment]
주석 스타일로 마이그레이션하지 않고 바로 #535 를 진행하기로 결정했습니다.
