### ISSUE TITLE
모집 과정이 존재하지 않을 경우 안내 메시지를 보여준다.

### ISSUE THREAD

**Issue by lokba** [woowacourse/service-apply#545]
- [x] API 응답 확인
  - 상태 관리가 어떻게 되고 있는지 확인  
- [x] 안내 메시지 디자인
- [x] 디자인 적용 
- [x] 테스트 > 스토리북

**Comment by woowapark** [comment]
포인트 추정: 3

**Comment by greenblues1190** [comment]
> 요 컴포넌트 button- prop들이 어떤 의미인지 살짝 모호한데 (아이템컴포넌트인데 버튼에 관련한 prop? -> 무슨 버튼이지? -> 컴포넌트를 봐야 알수있게됨) 리팩토링 혹시 관심있으신가유

_Originally posted by @jho2301 in https://github.com/woowacourse/service-apply/pull/569#discussion_r923402988_

`RecruitmentItem`에서 button 관련 props를 받아 컴포넌트에 내려주고 있음. 리팩토링 논의 필요.
