### ISSUE TITLE
회원가입, 마이페이지, 내 정보 수정의 생년월일을 어떤 형식으로 통일할지 (YYYYMMDD, YYYY-MM-DD)

### ISSUE THREAD

**Issue by lokba** [woowacourse/service-apply#548]
- [x] 어떤 형식으로 통일할지 논의
- [x] 적용 
- [x] storybook 테스트  

### 참고  
- 라이브러리 추가는 이 이슈에서 진행하지 않음

**Comment by woowapark** [comment]
포인트 추정: 3

**Comment by greenblues1190** [comment]
`BirthField` PropTypes 중 value 타입 warning. 타입 변경 필요

**Comment by woowapark** [comment]
@greenblues1190 
- 어떤 형식으로 결정했는지 
- 결정한 이유    

도 이슈에 함께 적어주시면 감사합니다~! 🙂 
(이슈만 봐도 히스토리와 결정 사항을 확인할 수 있도록이요!)

**Comment by greenblues1190** [comment]
## 3.0.0에서 폼 리팩토링 진행 및 논의 필요

- 현재 빈 문자열인 폼 초기값 null로 통일
- 폼마다 별개의 커스텀 훅으로 관리하여 유지보수 어려움.

**Comment by hwangstar156** [comment]
## 회원가입에서 Date 입력시 나오는 이슈

- 8개의 숫자를 모두 입력하여도 더 입력이 가능하다.
- 숫자외의 문자도 들어간다.
