### ISSUE TITLE
모집 픽스처를 생성하는 API를 설계한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#549]
1일

**Comment by summerlunaa** [comment]
모집 픽스쳐 API 설계

```kotlin
val recruitment = recruitment {
    title = "웹 백엔드 3기"
    term = term {
        name = "단독 모집"
    }
    startDateTime = LocalDateTime.now().minusYears(1)
    endDateTime = LocalDateTime.now().plusYears(1)
    recruitable = true
    hidden = true
    items = items {
        item {} // default 값으로 생성
        item {
            position = 2
            maximumLength = 1500
        }
        item {
            title = "프로그래밍 학습 과정과 현재 자신이 생각하는 역량은?"
            position = 3
             maximumLength = 2000
            description = "우아한테크코스는..."
        }
    }
}

// 이렇게 하면 default 값으로도 생성 가능
val recruitment = recruitment {}
```

**Comment by summerlunaa** [comment]
## 고민했던 부분

### 1. term 생성
term을 직접 지정만 가능해게 해두면 계속 post 요청을 보내 생성해야 한다. 따라서 termId만으로 기존에 존재하는 term을 가져올 수 있게 만들었다.

i) `termId`만 들어온 경우
- 받은 termId를 저장한다.

ii) `term`만 들어온 경우
- term을 생성하고, 생성한 term id를 저장한다.

iii) **`termId`와 `term`이 둘 다 들어온 경우**
- 우선 termId의 우선순위가 높다고 생각하고 termId를 저장하기로 결정했다. 이후 구현할 때 termId와 term 둘 중 하나만 받게 만들 방법을 생각해보면 더 좋을듯.

---
### 2. startDateTime & endDateTime 형식
일시를 문자열로 받을지, `LocalDateTime`으로 받을지 고민했다. 문자열이 가독성이나 사용성이 더 좋을 수 있다. 하지만 문자열로 특정 일시를 받는 경우 시간이 지남에 따라 모집의 종료 여부가 달라질 수 있다. 따라서 `LocalDateTime` 형식으로 받는다.

---
### 3. item 생성 시 소괄호 사용 VS 중괄호 사용
처음엔 객체를 전부 중괄호를 통해 생성하려 했다. 하지만 모든 필드를 default 값으로 생성하는 경우 빈 중괄호를 사용해야 한다는 문제가 생겼다. 이런 경우 소괄호를 사용하는 것이 더 자연스럽기 때문이다. 따라서 세 가지 방안이 나왔다.

i) item 객체 생성 시에만 소괄호를 사용한다.
- `장점`: default 값으로 생성할 때와 필드를 직접 지정할 때 모두 소괄호를 사용하면 일관성을 유지할 수 있다.
- `단점`: recruitment 객체를 생성할 때는 중괄호를 사용하므로 객체 별로 다른 괄호를 사용해야 하므로 일관성이 깨진다.

ii) 모든 객체 생성 시 중괄호를 사용한다.
- `장점`: 모든 객체를 생성할 때 중괄호를 사용하므로 일관성을 유지할 수 있다.
- `단점`: default 값으로 생성할 때는 소괄호를 쓰는 것이 더 자연스러운데 빈 중괄호를 사용해야 한다.

iii) **모든 객체 생성 시 default 값으로 생성할 때는 소괄호, 아닌 경우 중괄호를 사용한다.**
- `장점`: 기본적으로 중괄호를 사용하되 default 값으로 생성할 때는 소괄호를 사용하여 코드가 자연스럽다.
- `단점`: 소괄호와 중괄호를 섞어 사용해야 한다.

백엔드 코치, 크루들과 상의한 결과 3안이 가장 많은 표를 받아 3안으로 진행하기로 결정했다.
