### ISSUE TITLE
adoc 파일의 형식을 정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#551]
2일

**Comment by kth990303** [comment]
## adoc 형식
###  toc: left  (Table Of Contents)
- 왼쪽이 디자인, 가독성 측면에서 좋아보인다.
### toclevel: 2
- indent 4까지 할 경우, 불필요하게 toc가 길어진다.
### `:sectlinks:`를 달아주자.
- 문서를 보는 입장에서 링크로 편리하게 이동할 수 있게 제공하는 것이 좋아보임.
### 요청/응답까지만 adoc으로 관리해서 보여주자.
- api 자동 문서화를 빠르게 구현하는 것에 집중하자.
- 요청/응답 작성이 완료된 이후에, request/response의 **필드값에 대한 설명을 adoc으로 관리해서 보여주는 부분은 새로운 이슈로 등록해서 작성하면 좋을 듯.**
  - 양식을 adoc으로 보여주는 것이 client 입장이나, 코드를 처음 보는 입장에서 더 잘 이해하면서 코드를 작성할 수 있어보임.
  - `requestFields`에서 `optional`을 달아주어 설정해보자.
  
### adoc 형식 문법은 include가 아닌 operation을 사용하자
- operation이 관리하기엔 쉽다. 또한, operation으로 작성할 경우 코드량을 줄일 수 있다.
- operation을 사용할 경우 커스텀한 경우를 작성하기 힘들다. 그렇지만, 커스텀한 경우를 작성할 때가 많진 않을 것 같다.

참고
- [우아한형제들 기술블로그](https://techblog.woowahan.com/2597/)

**Comment by kth990303** [comment]
```adoc
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:
```
