### ISSUE TITLE
관리자 추가에 대한 개발 이슈를 정리한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#582]
## 최종 이슈 목록

- [ ] 관리자 계정을 생성하고 전체, 단건으로 조회한다.
   - 예상 소요 시간: `5시간`
- [ ] 관리자 정보를 수정한다.
- [ ] 관리자 계정을 삭제한다.
- [ ] 관리자 로그인 API를 설계한다.

**Comment by asebn1** [comment]
# 관리자 생성은 어떻게 진행되어야 할까?

## 1. 기존 방법

1. DB 접속
2. ADMINISTRATOR에 값 직접 넣어주기

```java
insert into ADMINISTRATOR values(1, 'admin', '{noop}1234')
```

## 2. 개선방법

### 2-1. 우아한형제들 도메인 이메일 인증을 통해 계정을 생성한다.

1. 관리자 페이지에서 `회원가입` 버튼을 누른다.
2. 회원가입 페이지에서 `이메일 인증`을 한다.
3. 이메일 인증 및 회원 정보를 입력하여 `계정을 생성`한다.

### 2-2. 가입 요청 후 관리자가 승인하여 계정을 생성한다.

1. 관리자 페이지에서 `회원가입` 버튼을 누른다.
2. 회원가입 페이지에서 회원정보를 입력하여 `가입을 신청`한다.
3. 관리자가 회원가입을 `승인`한다.

### 2-3. 설정한 인증 코드를 통과를 통해 계정을 생성한다.

1. 관리자 페이지에서 `회원가입` 버튼을 누른다.
2. 회원가입 페이지에서 `인증코드를 입력` 한다.
3. 인증코드 인증 및 회원 정보를 입력하여 `계정을 생성`한다.

### 2-4. 관리자가 관리자 계정을 생성한다.  ✔

1. 관리자 페이지에서 `관리자 계정관리` 버튼을 누른다.
2. 관리자 생성 버튼을 눌러 `계정을 생성`한다.

## 3. 관리자 계정관리 페이지

> 메인관리자와 추가된 관리자의 권한차이는 없다.
>

**1. 관리자 생성**
   - 관리자명
   - 아이디
   - 비밀번호

**2. 관리자 조회**
   - 관리자명
   - 아이디
   - 비밀번호 → 보여줄 필요가 없을 것 같다

**3. 관리자 정보 수정**
   - 관리자명
   - 비밀번호

**4. 관리자 삭제**

**Comment by jojogreen91** [comment]
생성, 수정, 삭제 API 에 접근할 때 접근 권한을 확인하도록 설계를 잘 해야될 것 같네요(아마 Spring Security 가 막아줄 것 같지만)
그리고 아이디, 비밀번호의 규칙은 있으면 좋지만 빡빡하게 정할 필요도 없을거 같습니다. 관리자 계정은 몇개 없을테니까요.
파랑, 제로 수고하셧습니다 :)

**Comment by dongho108** [comment]
안녕하세요 파랑, 제로!
관리자 생성기능 설계 하느라 고생하셨습니다!

해당 설계는 화면의 ui 설계(바딘코드)만 존재하는 것 같아요!

api명세나 기능목록정리가 있으면 다같이 리뷰하고 이슈를 할당받은 크루가 바로 개발할 수 있을 것 같아요.

이외의 의견은 조조그린과 동일합니다.👍

**Comment by kth990303** [comment]
파랑 제로 꼼꼼하게 이슈 정리해주셨네요! 덕분에 수월하게 잘 읽었습니다.

개인적으론 Api 명세는 조조그린, 애쉬 의견도 좋지만 개발을 맡을 크루들과 제이슨과 같이 논의하는 것도 좋다고 생각돼서 지금도 괜찮은 것 같아요!

관리자 삭제 부분을 논리적 삭제를 안해도 되는지 (개인정보 보관 등) 궁금하긴 하네요.

수고 많으셨습니다!

**Comment by SuyeonChoi** [comment]
파랑 제로 관리자 추가 이슈 설계하시느라 고생많았습니다!
저는 애쉬의 의견과 동일해요. 
관리자 추가는 완전히 새로운 기능이라서 1차적인 API 명세서를 설계해주시면 개발 담당 크루가 더 수월하게 시작할 수 있다고 생각합니다.
`바로 개발할 수 있는 상태` 관점에서 생각해보면 현재보다는 좀 더 구체적인 정보가 필요할거 같아요!

**Comment by kbsat** [comment]
파랑 제로 고생많으셨어요! 😁
저도 애쉬, 페퍼 의견처럼 API 관련 명세도 추가로 작성되었으면 바로 개발에 들어갈 수 있을 것 같아요!
나머지도 다른 분들의 의견과 동일해서 따로 남길 말은 없네요 😊

**Comment by summerlunaa** [comment]
# API

### `1-1. 관리자 조회 - 전체`

### 요청

```jsx
GET /admin/administrators  HTTP/1.1   
```

### 응답

```jsx
200 OK

{
	administrators: [
		{
			id: 1,
			name: '제이슨',
			administratorId: 'jason123' 
		},
		{
			id: 2,
			name: '공원',
			administratorId: 'kongwon123'
		},
		{
			id: 3,
			name: '네오',
			administratorId: 'neo123'
		}
	]
}
```

### `1-2. 관리자 조회 - 단건`

### 요청

```jsx
GET /admin/administrators/{id}  HTTP/1.1   
```

### 응답

```jsx
200 OK

{
		id: 4,
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'
}
```

### `2. 관리자 생성`

### 요청

```jsx
POST /admin/administrators  HTTP/1.1   

{
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'	
}
```

### 응답

```jsx
201 CREATED

header: {
	location: /admin/administrators/4
} 

{
		id: 4,
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'
}
```

### `3. 관리자 정보 수정`

### 요청

```jsx
PUT admin/administrators  HTTP/1.1   

{
		id: 4,
		name: '코파랑',
		password: 'password1234'
}
```

### 응답

```jsx
201 NO CONTENT

{
	id: 4,
	name: '코파랑',
	password: 'password1234'
}
```

### `4. 관리자 삭제`

### 요청

```jsx
DELETE admin/administrators  HTTP/1.1   

{
	id: 4
}
```

### 응답

```jsx
201 NO CONTENT
```

**Comment by summerlunaa** [comment]
## 1. 관리자 계정을 생성한다.

- 관리자 생성 버튼을 누르면 관리자를 생성할 수 있는 창이 뜬다.
- 관리자 생성 시 필요한 정보는 아래와 같다. 규칙에 어긋나는 경우 error를 띄운다.
    - 관리자명
        - 1-20자, 영어/한글/숫자 가능
        - 중복 불가능.
    - 아이디
        - 중복 불가능.
        - 규칙 ? Vaadin or security에서 제공하는 기본 규칙이 있다면 그걸 따른다.
    - 비밀번호
        - 규칙 ? Vaadin or security에서 제공하는 기본 규칙이 있다면 그걸 따른다.
        - 두 번 입력받아 확인한다.

### 요청

```jsx
POST /admin/administrators  HTTP/1.1   

{
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'	
}
```

### 응답

```jsx
201 CREATED

header: {
	location: /admin/administrators/4
} 

{
		id: 4,
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'
}
```

## 2. 관리자 계정 목록을 조회한다.

- 관리자명
- 아이디

### `1. 관리자 조회 - 전체`

### 요청

```jsx
GET /admin/administrators  HTTP/1.1   
```

### 응답

```jsx
200 OK

{
	administrators: [
		{
			id: 1,
			name: '제이슨',
			administratorId: 'jason123' 
		},
		{
			id: 2,
			name: '공원',
			administratorId: 'kongwon123'
		},
		{
			id: 3,
			name: '네오',
			administratorId: 'neo123'
		}
	]
}
```

### `2. 관리자 조회 - 단건`

### 요청

```jsx
GET /admin/administrators/{id}  HTTP/1.1   
```

### 응답

```jsx
200 OK

{
		id: 4,
		name: '파랑',
		administratorId: 'parang123',
		password: 'password123'
}
```

### 3. 관리자 정보를 수정한다.

- 입력받은 정보로 수정할 수 있다.
    - 새로운 관리자명
    - 새로운 비밀번호

### 요청

```jsx
PUT admin/administrators  HTTP/1.1   

{
		id: 4,
		name: '코파랑',
		password: 'password1234'
}
```

### 응답

```jsx
201 NO CONTENT
```

### 4. 관리자 계정을 삭제한다.

- 관리자 조회 페이지에 삭제 버튼을 함께 둔다.
- 삭제 전 경고 창을 띄운다.

### 요청

```jsx
DELETE admin/administrators  HTTP/1.1   

{
		id: 4
}
```

### 응답

```jsx
201 NO CONTENT
```

---

> 메인관리자와 추가된 관리자의 권한차이는 없다.
>

**Comment by kbsat** [comment]
전체 리스트 조회 API 응답 값 수정

### AS-IS
200 OK
``` jsx
{
   administrators: [
      {
         "id": 1,
         "name": "제이슨",
         "username": "jason123"
      },
      {
         "id": 2,
         "name": "공원",
         "username": "kongwon123"
      },
      {
         "id": 3,
         "name": "네오",
         "username": "neo123"
      }
   ]
}
```
###TO-BE
``` jsx
[
    {
       "id": 1,
       "name": "제이슨",
       "username": "jason123"
    },
    {
       "id": 2,
       "name": "공원",
       "username": "kongwon123"
    },
    {
       "id": 3,
       "name": "네오",
       "username": "neo123"
    }
 ]
```
