### ISSUE TITLE
타입스크립트에 대한 환경을 구성한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#587]
## 목표
- 1 현재 프로젝트 코드 그대로 컴파일에 문제 없도록    
- 2 ts(x) 추가해도 문제 없도록   
      
## 할 일
- [x] CRA 상태에서 TS 빌드 세팅 추가 
- [x] tsconfig 세팅  
    - allowJS, any 허용. 최대한 너그럽게
    - ts, tsx 1개 정도 바꿔서 문제 없는지 확인  
- [x] 필요한 타입 패키지들 설치 
  - react, react-router 등등 기본 타입들 

## 참고 사항 
- `// @ts-check`
- tsconfig에서 엄격하게 가져갈 설정들  
- types, d.ts 관리 컨벤션

**Comment by woowapark** [comment]
포인트: 2
