### ISSUE TITLE
api 레이어의 모듈들을 타입스크립트로 마이그레이션한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#592]
### 작업 목록
- api 스펙 확인
- 기존 기능 동작 확인
- 타입스크립트 마이그레이션
- 마이그레이션 이후 동작 테스트
- 포인트: 3

**Comment by greenblues1190** [comment]
## 로그인한 유저가 지원서 작성 페이지로 이동 시 메인페이지로 이동되는 버그

### 현상

로그인한 유저가 지원서 작성 페이지로 이동 시 메인페이지로 다시 이동됨.

### 실행 환경
macOS Big Sur 11.5.1
Chrome 64 104.0.5112.101 arm64
Node v16.15.1

### 재현 스텝

```bash
# 서버 실행 필요
git checkout 934ec4e0
cd "$(git rev-parse --show-toplevel)/frontend"
yarn install
yarn start
```

### 예상되는 원인

`useApplicationRegisterForm.js`의 `currentRecruitment`가 null 값이 되어 [useEffect의 분기](https://github.com/woowacourse/service-apply/blob/5c26962ea530c21479e15ed4c1bfdccb6a8fe9f5/frontend/src/hooks/useApplicationRegisterForm.js#L146)에서 랜딩페이지로 이동되었습니다. `react-router-dom`의 버전을 v6로 업그레이드하면서 `useHistory`에서 `useNavigate`로 마이그레이션하는 과정에서 state 전달 동작 방식이 달라져 발생하는 것으로 예상됩니다. #541

### 스크린샷
![Aug-30-2022 16-03-18](https://user-images.githubusercontent.com/44823900/187371976-7f157ee4-59f1-4e4d-8cc8-b0644e4c442c.gif)
