### ISSUE TITLE
Header, Footer 컴포넌트 스타일과 링크를 변경한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#599]
추정 포인트: 2

#### Header

<img width="782" alt="스크린샷 2022-08-16 오후 5 05 58" src="https://user-images.githubusercontent.com/44823900/184829736-2a0d359e-6b03-4d4e-be55-f96073cc5d19.png">

- `position: fixed`
- 로고와 버튼메뉴 `space-between`

#### Footer

![Footer](https://user-images.githubusercontent.com/19251499/183906842-c098372d-6678-45fa-bfb3-822f740264f1.png)

- 인스타그램 링크 추가
- 저작권 문구 최하단으로 이동
- 기존 버튼 원형 border 제거한 스타일로 통일
- 링크 사이 divide line 추가

관련 이슈: #584

**Comment by soyi47** [comment]
### 하단 카피라이트 문구 관련
(기존) Copyright 2021. 우아한테크코스. All rights reserved.
(변경) Copyright. 우아한테크코스. All rights reserved

- '한국 저작권 보호원'의 올바른 콘텐츠 표기법을 참고하여 변경
  - 카피라이트 기호, 저작권자 이름, 최초의 발행연도를 적당한 방법으로 적당한 위치에 표시한다.
  - https://www.kcopa.or.kr/lay1/program/S1T231C359/copyrightok/contents/view.do?ntt_id=1749
