### ISSUE TITLE
지원 리스트, 아이템 스타일을 수정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#600]
추정 포인트: 2

<img width="600" alt="스크린샷 2022-08-16 오후 2 34 45" src="https://user-images.githubusercontent.com/44823900/184805255-174e967e-5c87-45f1-ba78-bf63b82f6f4a.png">

#### 리스트

- 모집 상태 별 탭을 제거한다.

#### 아이템

- hover 스타일 (ease-in 300ms)
- 아이템 전체 링크 영역

#### 지원 상태 인디케이터 (이름 논의 필요) 컴포넌트를 추가한다.

- `span` 혹은 `p`

#### active

<img width="172" alt="스크린샷 2022-08-16 오후 2 32 28" src="https://user-images.githubusercontent.com/44823900/184804973-b412ecaa-292e-4888-97e7-3e773d71505c.png">

#### inactive

<img width="202" alt="스크린샷 2022-08-16 오후 2 32 31" src="https://user-images.githubusercontent.com/44823900/184804951-2d3f729e-fa37-48bc-b384-5df9579cb260.png">

관련 이슈: #584

**Comment by hwangstar156** [comment]
- RecruitmentItem hover에 대한 스타일링 
- listItem의 변경된 스타일링
