### ISSUE TITLE
배경색 변경 및 카카오톡 문의하기 플로팅 버튼, 필터링 UI를 추가한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#601]
추정 포인트: 2

#### 배경색을 변경한다.

- 기존색상에서 더 연한 색상으로 배경색을 변경한다. `#f5f5f5`

<img width="615" alt="스크린샷 2022-08-16 오후 4 57 33" src="https://user-images.githubusercontent.com/44823900/184828180-ab2c9f53-99b0-4aeb-845c-0e2edc025df0.png">

#### 카카오톡 문의 오버레이를 추가한다.

- https://pf.kakao.com/_budWj
- 리액트 아이콘 추가

#### 필터링 기능을 추가한다.

- 필터링된 과정에 따라 소개문구와 지원리스트가 변경된다. ([토스채용 지원공고 사이트](https://toss.im/career/jobs?company=%EC%A0%84%EC%B2%B4) 참고)

<img width="529" alt="스크린샷 2022-08-16 오후 5 00 16" src="https://user-images.githubusercontent.com/44823900/184828638-c468b9b0-c296-4477-bba6-02b2dcedbe8f.png">

관련 이슈: #584

**Comment by hwangstar156** [comment]
- 모바일 탭 디자인 체크
- 필터링 기능에 대해 백엔드 api로 할것인지 프론트에서 처리할지 논의
