### ISSUE TITLE
최종 제출 전에 지원서를 미리 볼 수 있는 기능을 기획하고 구현한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#614]
- 지원서 페이지의 최종 제출 전 지원서 미리보기 기능
    - 지원서 미리보기 모달 - 피그마 작업
    - 최종 제출 버튼 클릭 시 Confirm 절차의 역할을 해야 한다. - 최종 제출 후 수정이 불가함을 안내하는 문구 추가

**Comment by greenblues1190** [comment]
## 지원서 미리보기 모달창을 추가한다.

### 프로토타입
<img width="755" alt="스크린샷 2022-09-20 오후 2 46 08" src="https://user-images.githubusercontent.com/44823900/191176871-211dec6e-59ae-4bc3-98f1-92819482a594.png">

### 상세 요구 사항
- 지원서 최종 제출 버튼을 누르면 지원서 미리보기 모달창을 보여준다.
- 지원서 제출 확인 체크박스를 누르면 모달창의 최종 제출 버튼을 활성화한다.
- 모달창 백그라운드에 dimmer를 추가한다.
- dimmer를 클릭하거나 `ESC`를 누르면 모달창을 닫는다.
- 모달창의 최종 제출 버튼을 누르면 지원서를 제출하고 내 지원 현황 페이지로 라우팅한다.
- 자세한 동작 및 스타일은 [Figma present](https://www.figma.com/proto/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90-%ED%94%8C%EB%9E%AB%ED%8F%BC?node-id=2193%3A4166&scaling=scale-down&page-id=1429%3A72006&starting-point-node-id=1448%3A73008&show-proto-sidebar=1) 기능을 이용하여 확인한다.
