### ISSUE TITLE
코틀린 mock 라이브러리 사용을 고려해 본다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#63]
Mockito는 확장 함수를 스터빙(stubbing)할 수 없다. (https://github.com/woowacourse/service-apply/pull/58#discussion_r487625787)
따라서 코틀린 mock 라이브러리 사용을 고려해 본다.

2021년 7월 8일 기준

- mockito-kotlin(https://github.com/nhaarman/mockito-kotlin -> https://github.com/mockito/mockito-kotlin)
   - star: 2.6k, 마지막 커밋: 2019년 9월 8일 -> 2021년 5월 26일
- mockk(https://mockk.io)
   - star: 3.9k, 마지막 커밋: 2021년 7월 7일

---

> To mock Kotlin classes, MockK is recommended. If you need the `Mockk` equivalent of the Mockito specific `@MockBean` and `@SpyBean` annotations, you can use SpringMockK which provides similar `@MockkBean` and `@SpykBean` annotations.

https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-kotlin-testing

**Comment by woowahan-pjs** [comment]
### Springmockk

- https://github.com/Ninja-Squad/springmockk
- 현재 버전: 2.0.3 (MockK 1.9.3)
- 최신 버전: 3.0.1 (Spring Boot 2.4.0 필요, MockK 1.10.2)

### MockK

- 현재 버전: 1.9.3
- 최신 버전: 1.12.0

**Comment by knae11** [comment]
Mockito에서 Mockk 전환시 참고할만한 작은 팁

# Mockito → Mockk

- `@Mock` → `@MockK`
- anyLong() →  ofType(Long::class)
- given → every {}
- `@MockBean` → `@MockkBean`
- willReturn() → returns 또는 answers { }

# 객체비교

- Mock 테스트 대상의 인자 값으로 객체를 넣을 경우 객체비교가 필요(이때 주소가 다르면 다른 객체로 인식)
- 동등성으로 객체 비교
    - eq() : 객체를 deepEquals 비교
     

# Return Void

- willDoNothing()은 Void 리턴으로 대체가능

[https://notwoods.github.io/mockk-guidebook/docs/tips/unit/](https://notwoods.github.io/mockk-guidebook/docs/tips/unit/)

```kotlin
every { evaluationRepository.deleteById(ofType(Long::class)) } returns Unit
every { evaluationRepository.deleteById(ofType(Long::class)) } just Runs
```

**Comment by knae11** [comment]
# ApplicationRestController 암호화 사용시 테스트 문제발생

```kotlin
    @Test
    fun `잘못된 비밀번호 변경 요청에 응답으로 Unauthorized를 반환한다`() {
        every { jwtTokenProvider.isValidToken("valid_token") } answers { true }
        every { jwtTokenProvider.getSubject("valid_token") } answers { applicantRequest.email }
        every { applicantService.getByEmail(applicantRequest.email) } answers { applicantRequest.toEntity() }
        every {
            applicantService.editPassword(ofType(Long::class), eq(inValidEditPasswordRequest))
        } throws ApplicantAuthenticationException()

        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()

        mockMvc.post("/api/applicants/edit-password") {
            content = objectMapper.writeValueAsString(inValidEditPasswordRequest) // -> 재생성 필요
            contentType = MediaType.APPLICATION_JSON
            header(AUTHORIZATION, "Bearer valid_token")
        }.andExpect {
            status { isUnauthorized }
        }
    }

    private fun createInValidEditPasswordRequest(): HashMap<String, String> {
        val inValidEditPasswordRequest: HashMap<String, String> = HashMap()
        inValidEditPasswordRequest["password"] = WRONG_PASSWORD
        inValidEditPasswordRequest["newPassword"] = NEW_PASSWORD
        return inValidEditPasswordRequest
    }
```

- Password 객체가 사용되는 inValidEditPasswordRequest는 만들어질때 sha-256으로 암호화가 됨
- objectMapper로 request를 만들 때, 기존에 작성해둔 `private val inValidEditPasswordRequest = validEditPasswordRequest.copy(password = Password(WRONG_PASSWORD))` 를 사용하면 암호화된 내용이 또 암호화가 진행되어 내부 값이 달라짐
- 예시)

    ```kotlin
    inValidEditPasswordRequest // wrongPassword(text) → 4e12(암호화)
    objectMapper.writeValueAsString(inValidEditPasswordRequest) 
    // 컨트롤러와 매핑하기 위한 json -> Object 변환과정에서 값으로 4e12(기존 암호화된 값)가 들어와서 이것이 암호화 됨
    // 4e12를 비교하기 원하나 새로운 암호값인 9rw1(암호화)가 되어 eq()비교에도 다른 값으로 인식해 Mock 설정 값을 거치치 않음
    ```

- 새롭게 key-value 형태의 문자 값으로 다시 객체를 만들어(`createInValidEditPasswordRequest()`) 이것을 json → Object 작업을 통해 암호화가 이루어져야 내부 값이 같음을 비교가능
