### ISSUE TITLE
브라우저별 지원 상태 페이지의 헤더 렌더링 버그를 수정한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#632]

**Comment by greenblues1190** [comment]
## 브라우저 별 스크린샷

### 크롬 모바일

![chrome mobile](https://user-images.githubusercontent.com/44823900/191178617-346e04a8-6e3e-4790-b951-dace01e76aad.jpeg)

### 삼성 인터넷 브라우저

![삼성 인터넷 브라우저](https://user-images.githubusercontent.com/44823900/191178644-7b9c5012-d62b-404b-b54d-6a6de7cb8006.jpeg)

## 모바일 크로미움 디버깅 스텝

1. USB 연결 (?!)
2. `chrome://inspect` 접속
3. `inspect` 클릭해 개발자도구 팝업창 열기

<img width="543" alt="debug" src="https://user-images.githubusercontent.com/44823900/191178826-9f424d2c-61e3-445c-930a-615d6c05192d.png">

### 참고
- [Chrome DevTools - Chrome Developers](https://developer.chrome.com/docs/devtools/#remote-debugging)
- [Remote debugging with Chrome Developer Tools](https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html)

**Comment by hwangstar156** [comment]
![Screenshot_20221011-153154_Samsung Internet.jpg](https://user-images.githubusercontent.com/85891751/195013442-1ff0be08-a14a-4f07-8c05-895ad83e5bd0.jpg)

삼성 모바일 브라우저
