### ISSUE TITLE
API 문서가 자동화되지 않는 현상을 수정한다.

### ISSUE THREAD

**Issue by kth990303** [woowacourse/service-apply#688]
# 어떤 버그인가요?
- Spring REST Docs로 api 자동 문서화를 했을 때, index.html이 업데이트되지 않습니다.

## 예상 결과
- 애플리케이션을 빌드하면 스니펫이 생성되고 index.html이 해당 스니펫에 맞게 업데이트돼야 합니다.
- `http://localhost:8080/docs/index.html`로 접속할 경우 아래 그림처럼 api 문서가 보여야 합니다.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/57135043/200242999-ff112ff2-d70b-4244-b550-2210857202d4.png">

## 실제 결과
- 스니펫은 생성이 되지만, index.html 이 생성 또는 업데이트되지 않습니다. (기존 index.html 파일이 있을 경우 업데이트가 되지 않음. index.html 파일이 없을 경우 생성이 안됨.)

- 아래 그림은 브랜치를 최신으로 맞춘 후 build한 모습입니다.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/57135043/200242725-623b7670-b2a9-47c1-a370-bbf1c82f31ba.png">
<img width="252" alt="image" src="https://user-images.githubusercontent.com/57135043/200241738-c6fa9f83-5b48-4f17-8bd4-843836cf4920.png">
- `src/main/resources/static/docs` 폴더에 `index.html`이 생성되지 않습니다.

### REST Docs의 index.html이 생성되지 않는 모습
<img width="252" alt="image" src="https://user-images.githubusercontent.com/57135043/200241738-c6fa9f83-5b48-4f17-8bd4-843836cf4920.png">

### 로컬 환경에서 실행 시 `http://localhost:8080/docs/index.html`로 접속할 경우
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/57135043/200242075-fd63d545-c7a9-4b63-beb6-aef4b50edfa2.png">

# 버그를 재현하는 방법
1. 기존에 있는 `src/main/resources/static/docs` 폴더의 `index.html`을 지웁니다.
2. develop 브랜치를 최신으로 업데이트해준 후 `./gradlew clean bootJar` 또는 `./gradlew clean build`를 해줍니다.

3-1. `src/main/resources/static/docs` 폴더에 `index.html`이 생성되는지 확인합니다. -> 현재 생성되지 않는 이슈 존재
3-2. docker 실행 후 애플리케이션 실행하여 `http://localhost:8080/docs/index.html` 에 접속 시 API 문서가 뜨는지 확인합니다. -> 현재 로그인창이 뜨는 이슈 존재

# 어떤 환경에서 발생했나요?

- 브라우저 및 버전: Chrome 브라우저 버전 107.0.5304.87(공식 빌드) (arm64)
- 기기 및 OS: MacBook Pro(14형, 2021년 모델) 버전 12.3.1(21E258)

**Comment by woowahan-pjs** [comment]
로컬에서 API 문서를 확인하려면 `./gradlew clean copyDocs`를 실행한 후 확인할 수 있습니다. 현재로서는 문제가 발견되지 않아 이 이슈를 종료합니다.
https://github.com/woowacourse/service-apply/pull/566#issuecomment-1195728004
