### ISSUE TITLE
지원 화면에 header와 footer를 붙인다.

### ISSUE THREAD

**Issue by hotheadfactory** [woowacourse/service-apply#82]
페이지에 헤더와 푸터를 붙여서 사이트 정보를 표시하고 완성도를 높인다.
 * 페이지에 header를 붙인다.
 * 페이지에 footer를 붙인다.

**Comment by woowahan-pjs** [comment]
header와 footer는 [우아한테크코스](https://woowacourse.github.io)와 동일하게 만들면 어떨까요?
