### ISSUE TITLE
선발 대상자 도메인을 구현한다.

### ISSUE THREAD

**Issue by toneyparky** [woowacourse/service-apply#89]
#24 의 구현에 필요한 사전 이슈

- 요구사항 명세서를 반영하여 선발 대상자 도메인을 구현한다.
  - EvaluationAnswer (UML 상에서 Answer)를 구현한다.
  - EvaluationTarget (UML 상에서 Target)을 구현한다.
  - EvaluationTargetRepository를 구현한다.
  - EvaluationTargetService의 불러오기 로직을 구현한다.  

---

![evaluation](https://user-images.githubusercontent.com/48229284/91674152-7500b080-eb72-11ea-98bd-d0558b71b786.png)

**Comment by woowahan-pjs** [comment]
### 불러오기를 하지 않은 경우

1. 이전 평가 대상자를 불러온다.
   - 이전 평가가 없는 경우 특정 모집의 지원자를 불러온다.
2. 부정 행위자를 제외한다.
3. 평가 대상자를 수정한다.

### 이미 불러오기를 한 경우

1. 이전 평가 대상자를 불러온다.
   - 이전 평가가 없는 경우 특정 모집의 지원자를 불러온다.
2. 부정 행위자를 제외한다.
3. 기존 평가 대상자와 비교한다.
4. 평가 대상자를 수정한다.
   - 기존 평가 대상자 중 일부를 삭제한다.
   - 새로운 평가 대상자를 추가한다.

---

불러오기를 하지 않았다면 기존 평가 대상자가 0명이고, 이미 불러오기를 하였다면 기존 평가 대상자가 n명이라는 점 외에는 차이가 없는 것 같아요. 어떻게 생각하세요?

**Comment by toneyparky** [comment]
현재 두개의 분기가 이전 평가의 유무로 나눈 상황인데 이를 1번으로 묶어 하나의 프로세스로 가져가고

분기는 이전에 불러온 정보가 있는지라는 기준으로 나누게 된다면 부정행위자 처리에 대한 경우도 쉬워지겠네요..!

로직 수정을 하면 훨씬 좋은 코드로 바뀔거 같아요!

달아주신 코멘트와 함께 고려해보겠습니다. 
지금 구조보다는 훨씬 나을거 같아요!

**Comment by toneyparky** [comment]
`이미 불러오기를 한 경우`의 4번에 대해서 기본적으로 삭제를 진행하고 저장이 필요할 경우에만 저장하도록 구현해봤습니다.
