### ISSUE TITLE
관리 화면에 대한 개발 이슈를 정리한다. - 9월 3일(목)

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#9]

**Comment by toneyparky** [comment]
# 내일 수정이 예정 되어있습니다.

## 이슈 쪼개기 - 프론트

- 프론트 재사용가능한 컴포넌트 제작 (1일)
    - 사이드바, 모달, 페이지네이션, 테이블, 입력 폼, 검색창, 버튼
- 한 페이지 당 (2~3일)
- 메인 페이지
    - 대쉬보드 (우선 순위 하)
- 모집 관리
    - 생성 뷰
        - 입력 폼
            - 예외처리
            - 기간은 캘린더 뷰
        - 모집 항목 동적으로 추가, 삭제(삭제 UI가 이상하다 - 어떤 항목이 삭제될지 모른다)
        - 모집 항목 동적으로 순서 조정
        - 관리할 객체는 모집, 모집 항목의 리스트
    - 수정 뷰
        - 모집 id가 필요
        - 처음에 백에서 받아서 보여주기
    - 테이블 뷰
        - 모집 시작, 중지, 삭제시 컨펌 모달 처리 + api 쏘기
        - 페이징
        - 정렬 (프로토타입에는 없음)
- 평가 관리
    - 생성 뷰
        - 입력 폼
            - 예외처리
            - 기간은 캘린더 뷰
        - 평가 항목 동적으로 추가, 삭제(삭제 UI가 이상하다 - 어떤 항목이 삭제될지 모른다)
        - 평가 항목 동적으로 순서 조정
        - 관리할 객체는 평가, 평가 항목의 리스트
        - 평가에서 api 쏴서 option 가져오기
            - 이전 평가가 없을 경우에 대한 옵션 처리
    - 수정 뷰
        - 평가 id가 필요
        - 처음에 백에서 받아서 보여주기
    - 테이블 뷰
        - 페이징
        - 정렬 (프로토타입에는 없음)
- 선발 과정
    - 테이블 뷰
        - 검색
        - 페이징
        - 정렬
        - 평가하기
        - 지원서 보기
            - 첨부파일 보여주기 (링크)
        - 부정행위자로 추가하기 버튼 추가 (평가를 하며 부정행위자인지 알게 되니까)
    - 엑셀 다운로드
    - 평가자 불러오기?

- 부정행위자
    - 페이징
    - 검색 및 추가
        - 전체 지원자에서 검색해서 그 대상을 부정행위자로 추가하는 기능
    - 정렬

**Comment by hotheadfactory** [comment]
토니 로운~ 잘 살펴보았어요!
알기 쉽게 잘 정리해 두었네요. 적은 대로 스토리보드 업데이트만 하면 될 것 같아요!
