### ISSUE TITLE
페이지 URL에 대해 논의한다.

### ISSUE THREAD

**Issue by lalize** [woowacourse/service-apply#99]
전체적인 페이지 URL 구조에 대해 논의가 필요합니다.

현재는 아래와 같은 구조로 되어있습니다.

모집 목록 페이지 `/recruits`

지원자 등록 페이지 `/register/applicant?recruitmentId=?`

지원서 작성 페이지 `/register/application?recruitmentId=?`

지원서 수정 페이지 `/register/application/edit?recruitmentId=?`

지원자 확인 페이지 `/login`

비밀번호 찾기 페이지 `/find`

---

## 모집 목록
모집 목록 페이지는 메인 페이지이므로 `/recruits` -> `/` 로 수정할 필요가 있어보입니다.

## 지원자 등록
`/applicants/:recruitmentId/new`
`/applicants/recruitments/:recruitmentId/new`
`/recruitments/:recruitmentId/applicants/new`
`/applicants/new?recruitmentId=?`

## 지원서 작성 및 수정
`/applications/:recruitmentId/[new|edit]`
`/applications/recruitments/:recruitmentId/[new|edit]`
`/recruitments/:recruitmentId/applications/[new|edit]`
`/applications/[new|edit]?recruitmentId=?`

---

제이슨이 얘기한 것처럼 무언가를 생성하고 삭제하는 페이지에 대해 `/new`, `/edit` 구조로 가는 게 좋아보여요.

등록하는 페이지에서 `/register`를 붙이지 않아도 접미사로 붙는 `/new` 가 의미를 부여합니다. 또 비슷한 페이지에 대해 일관성있게 작성할 수 있을 것 같습니다.

네이밍도 다시 한번 고려해볼 필요도 있어보입니다. 
복수형/단수형도 고려해볼 필요가 있고
두개 이상으로 단어로 이루어진 경우는 어떻게 할 것인지 예를들면 `/application-forms` , `/applicationForms`, `/ApplicationsForms` 등

**Comment by dks301** [comment]
- token을 통해 관련 데이터를 가져올 때 url: `/me`

**Comment by ddaaac** [comment]
저는 마지막 방식(`/applications/[new|edit]?recruitmentId=?`)이 제일 직관적인 것 같네요.
쿼리파리미터가 필터링을 위해 주로 사용된다고 해도, 저희 팀이 알아보기 쉬운 url을 쓰면 될 것 같다는 생각이 드네요!

네이밍 관련해서는 관례대로(?) 복수형에 url은 하이픈(-)을 사용하는게 좋을 것 같습니다

**Comment by toneyparky** [comment]
@ddaaac 
```
네이밍 관련해서는 관례대로(?) 복수형에 url은 하이픈(-)을 사용하는게 좋을 것 같습니다
```
카멜 케이스 대신 -로 연결하는게 낫겠다는 이야기신거지요?

**Comment by woowahan-pjs** [comment]
경로는 케밥 표기법을 따르는 것을 찬성하고요, 파라미터는 소문자 카멜 표기법을 따르면 어떨까요? 현재 요청 본문(request body)은 소문자 카멜 표기법을 따르고 있어요.

**Comment by lalize** [comment]
현재까지 나온 의견을 종합해보면 표기법은 아래처럼 하도록 합니다.

|유형|표기법|
|---|---|
|url|*kabab-case*|
|request param|*camelCase*|
|request body|*camelCase*|


생성 및 수정 페이지(`지원자 등록`, `지원서 등록`, `지원서 수정`)는 `/도메인명/new|edit`로 경로가 끝나도록 합니다.

도메인이 다른 도메인에 의존적인 경우는 `/다른도메인명/다른도메인아이디/도메인명/new|edit`가 아닌 `/도메인명/new|edit?다른도메인아이디=?`처럼 `request param`을 쓰도록 합니다.

다른 의견은 추가 코멘트 부탁드려요.

**Comment by woowahan-pjs** [comment]
아쉽게도 Vaadin 14는 URL 템플릿을 지원하지 않아요. (e.g. `/orders/:id/edit`)
가장 간단한 해결 방법은 URL 구조를 `/orders/edit/:id`로 변경하는 거라고 해요.

- `https://github.com/vaadin/flow/issues/2740`
- `https://github.com/vaadin/flow/issues/3474`
- `https://github.com/vaadin/flow/issues/4213`

하지만 버전 14(LTS)가 아닌 버전 17은 지원합니다.
(https://vaadin.com/docs/v17/flow/routing/tutorial-router-templates.html)

혹은 확장 컴포넌트가 존재합니다.
https://vaadin.com/directory/component/url-parameter-mapping

**Comment by woowahan-pjs** [comment]
http://microformats.org/wiki/rest/urls

**Comment by woowahan-pjs** [comment]
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/IanaLinkRelations.java

**Comment by woowahan-pjs** [comment]
### In Vaadin

```kotlin
const val NEW_VALUE: String = "new"
const val EDIT_VALUE: String = "edit"
val FORM_URL_PATTERN: Regex = Regex("^(\\d*)/?($NEW_VALUE|$EDIT_VALUE)$")

fun String.toDisplayName(): String {
    return when (this) {
        NEW_VALUE -> "생성"
        EDIT_VALUE -> "수정"
        else -> throw IllegalArgumentException()
    }
}
```

```kotlin
UI.getCurrent().navigate(RecruitmentsFormView::class.java, NEW_VALUE)
UI.getCurrent().navigate(RecruitmentsFormView::class.java, "${recruitment.id}/$EDIT_VALUE")
```
